/*
 * Copyright 2023 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.layout;

import java.awt.event.ActionEvent;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import jcs.JCS;
import jcs.entities.TileBean;
import jcs.entities.TileBean.Direction;
import jcs.entities.TileBean.TileType;
import org.tinylog.Logger;

/**
 * This canvas / Panel is used to draw the layout
 *
 * @author frans
 */
public class LayoutPanel extends JPanel {

  private final boolean readonly;

  public LayoutPanel() {
    this(false);
  }

  public LayoutPanel(boolean readonly) {
    this.readonly = readonly;
    initComponents();
    postInit();
  }

  private void postInit() {
    this.straightBtn.setSelected(true);
    this.canvas.setTileType(TileType.STRAIGHT);
    this.setMode(readonly ? LayoutCanvas.Mode.CONTROL : LayoutCanvas.Mode.SELECT);

    if (this.readonly) {
      this.canvas.setDrawGrid(!readonly);

      this.saveBtn.setEnabled(!readonly);
      this.saveBtn.setVisible(!readonly);
      this.toolBar.remove(this.saveBtn);

      this.loadBtn.setEnabled(!readonly);
      this.loadBtn.setVisible(!readonly);
      this.toolBar.remove(this.loadBtn);

      this.repaintBtn.setEnabled(readonly);
      this.repaintBtn.setVisible(readonly);

      this.routeBtn.setEnabled(readonly);
      this.routeBtn.setVisible(readonly);

      this.selectBtn.setEnabled(!readonly);
      this.selectBtn.setVisible(!readonly);
      this.toolBar.remove(this.selectBtn);

      this.addBtn.setEnabled(!readonly);
      this.addBtn.setVisible(!readonly);

      this.deleteBtn.setEnabled(!readonly);
      this.deleteBtn.setVisible(!readonly);

      this.gridBtn.setEnabled(!readonly);
      this.gridBtn.setVisible(!readonly);

      this.straightBtn.setEnabled(!readonly);
      this.straightBtn.setVisible(!readonly);

      this.curvedBtn.setEnabled(!readonly);
      this.curvedBtn.setVisible(!readonly);

      this.blockBtn.setEnabled(!readonly);
      this.blockBtn.setVisible(!readonly);

      this.sensorBtn.setEnabled(!readonly);
      this.sensorBtn.setVisible(!readonly);

      this.signalBtn.setEnabled(!readonly);
      this.signalBtn.setVisible(!readonly);

      this.leftSwitchBtn.setEnabled(!readonly);
      this.leftSwitchBtn.setVisible(!readonly);

      this.rightSwitchBtn.setEnabled(!readonly);
      this.rightSwitchBtn.setVisible(!readonly);

      this.crossLBtn.setEnabled(!readonly);
      this.crossLBtn.setVisible(!readonly);

      this.crossRBtn.setEnabled(!readonly);
      this.crossRBtn.setVisible(!readonly);

      this.endTrackBtn.setEnabled(!readonly);
      this.endTrackBtn.setVisible(!readonly);

      this.straightDirectionBtn.setEnabled(!readonly);
      this.straightDirectionBtn.setVisible(!readonly);

      this.moveBtn.setEnabled(!readonly);
      this.moveBtn.setVisible(!readonly);

      this.flipVerticalBtn.setEnabled(!readonly);
      this.flipVerticalBtn.setVisible(!readonly);

      this.flipHorizontalBtn.setEnabled(!readonly);
      this.flipHorizontalBtn.setVisible(!readonly);

      this.rotateBtn.setEnabled(!readonly);
      this.rotateBtn.setVisible(!readonly);
    } else {

      this.toolBar.remove(this.autoPilotBtn);
      this.autoPilotBtn.setEnabled(readonly);
      this.autoPilotBtn.setVisible(readonly);

      this.toolBar.remove(this.startAutoPilotBtn);
      this.startAutoPilotBtn.setEnabled(readonly);
      this.startAutoPilotBtn.setVisible(readonly);
    }

    if (readonly) {
      loadLayout();
    }
  }

  public void saveLayout() {
    this.canvas.saveLayout();
  }

  public void loadLayout() {
    this.canvas.loadLayoutInBackground();
  }

  public void loadTiles() {
    this.canvas.loadTiles();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    straightPopupMenu = new javax.swing.JPopupMenu();
    verticalMI = new javax.swing.JMenuItem();
    horizontalMI = new javax.swing.JMenuItem();
    curvedPopupMenu = new javax.swing.JPopupMenu();
    rightMI = new javax.swing.JMenuItem();
    leftMI = new javax.swing.JMenuItem();
    operationsPM = new javax.swing.JPopupMenu();
    xyMI = new javax.swing.JMenuItem();
    propertiesMI = new javax.swing.JMenuItem();
    rotateMI = new javax.swing.JMenuItem();
    flipHorizontalMI = new javax.swing.JMenuItem();
    flipVerticalMI = new javax.swing.JMenuItem();
    moveMI = new javax.swing.JMenuItem();
    deleteMI = new javax.swing.JMenuItem();
    tileBtnGroup = new javax.swing.ButtonGroup();
    topPanel = new javax.swing.JPanel();
    toolBar = new javax.swing.JToolBar();
    saveBtn = new javax.swing.JButton();
    loadBtn = new javax.swing.JButton();
    repaintBtn = new javax.swing.JButton();
    routeBtn = new javax.swing.JButton();
    autoPilotBtn = new javax.swing.JToggleButton();
    startAutoPilotBtn = new javax.swing.JToggleButton();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
    selectBtn = new javax.swing.JButton();
    addBtn = new javax.swing.JButton();
    deleteBtn = new javax.swing.JButton();
    filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
    gridBtn = new javax.swing.JToggleButton();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
    straightBtn = new javax.swing.JToggleButton();
    curvedBtn = new javax.swing.JToggleButton();
    blockBtn = new javax.swing.JToggleButton();
    sensorBtn = new javax.swing.JToggleButton();
    signalBtn = new javax.swing.JToggleButton();
    leftSwitchBtn = new javax.swing.JToggleButton();
    rightSwitchBtn = new javax.swing.JToggleButton();
    crossLBtn = new javax.swing.JToggleButton();
    crossRBtn = new javax.swing.JToggleButton();
    straightDirectionBtn = new javax.swing.JToggleButton();
    endTrackBtn = new javax.swing.JToggleButton();
    crossingBtn = new javax.swing.JToggleButton();
    filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
    moveBtn = new javax.swing.JButton();
    flipVerticalBtn = new javax.swing.JButton();
    flipHorizontalBtn = new javax.swing.JButton();
    rotateBtn = new javax.swing.JButton();
    canvasScrollPane = new javax.swing.JScrollPane();
    canvas = new LayoutCanvas(this.readonly);

    verticalMI.setText("Vertical");
    verticalMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        verticalMIActionPerformed(evt);
      }
    });
    straightPopupMenu.add(verticalMI);

    horizontalMI.setText("Horizontal");
    horizontalMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        horizontalMIActionPerformed(evt);
      }
    });
    straightPopupMenu.add(horizontalMI);

    rightMI.setText("Right");
    rightMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rightMIActionPerformed(evt);
      }
    });
    curvedPopupMenu.add(rightMI);

    leftMI.setText("Left");
    leftMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        leftMIActionPerformed(evt);
      }
    });
    curvedPopupMenu.add(leftMI);

    xyMI.setText("x: y:");
    operationsPM.add(xyMI);

    propertiesMI.setText("Properties");
    propertiesMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        propertiesMIActionPerformed(evt);
      }
    });
    operationsPM.add(propertiesMI);

    rotateMI.setText("Rotate");
    rotateMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rotateMIActionPerformed(evt);
      }
    });
    operationsPM.add(rotateMI);

    flipHorizontalMI.setText("Flip Horizontal");
    flipHorizontalMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        flipHorizontalMIActionPerformed(evt);
      }
    });
    operationsPM.add(flipHorizontalMI);

    flipVerticalMI.setText("Flip Vertical");
    flipVerticalMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        flipVerticalMIActionPerformed(evt);
      }
    });
    operationsPM.add(flipVerticalMI);

    moveMI.setText("Move");
    moveMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        moveMIActionPerformed(evt);
      }
    });
    operationsPM.add(moveMI);

    deleteMI.setText("Delete");
    deleteMI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteMIActionPerformed(evt);
      }
    });
    operationsPM.add(deleteMI);

    setMinimumSize(new java.awt.Dimension(1000, 160));
    setOpaque(false);
    setPreferredSize(new java.awt.Dimension(1400, 900));
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentHidden(java.awt.event.ComponentEvent evt) {
        formComponentHidden(evt);
      }
      public void componentResized(java.awt.event.ComponentEvent evt) {
        formComponentResized(evt);
      }
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });
    setLayout(new java.awt.BorderLayout());

    topPanel.setMaximumSize(new java.awt.Dimension(32767, 50));
    topPanel.setMinimumSize(new java.awt.Dimension(1000, 50));
    topPanel.setPreferredSize(new java.awt.Dimension(1000, 50));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout1.setAlignOnBaseline(true);
    topPanel.setLayout(flowLayout1);

    toolBar.setDoubleBuffered(true);
    toolBar.setMargin(new java.awt.Insets(1, 1, 1, 1));
    toolBar.setMaximumSize(new java.awt.Dimension(1200, 42));
    toolBar.setMinimumSize(new java.awt.Dimension(1150, 42));
    toolBar.setName(""); // NOI18N
    toolBar.setPreferredSize(new java.awt.Dimension(1100, 42));

    saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/save-24.png"))); // NOI18N
    saveBtn.setToolTipText("Save");
    saveBtn.setFocusable(false);
    saveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    saveBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    saveBtn.setMinimumSize(new java.awt.Dimension(40, 40));
    saveBtn.setPreferredSize(new java.awt.Dimension(40, 40));
    saveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    saveBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveBtnActionPerformed(evt);
      }
    });
    toolBar.add(saveBtn);

    loadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/load-24.png"))); // NOI18N
    loadBtn.setToolTipText("Load");
    loadBtn.setFocusable(false);
    loadBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    loadBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    loadBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    loadBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    loadBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    loadBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loadBtnActionPerformed(evt);
      }
    });
    toolBar.add(loadBtn);

    repaintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/CS2-3-Sync.png"))); // NOI18N
    repaintBtn.setToolTipText("Repaint");
    repaintBtn.setFocusable(false);
    repaintBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    repaintBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    repaintBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    repaintBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    repaintBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    repaintBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        repaintBtnActionPerformed(evt);
      }
    });
    toolBar.add(repaintBtn);

    routeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/river-black.png"))); // NOI18N
    routeBtn.setToolTipText("Route");
    routeBtn.setFocusable(false);
    routeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    routeBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    routeBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    routeBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    routeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    routeBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        routeBtnActionPerformed(evt);
      }
    });
    toolBar.add(routeBtn);

    autoPilotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/pilot.png"))); // NOI18N
    autoPilotBtn.setToolTipText("Auto mode");
    autoPilotBtn.setFocusable(false);
    autoPilotBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    autoPilotBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    autoPilotBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    autoPilotBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    autoPilotBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/pilot-green.png"))); // NOI18N
    autoPilotBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    autoPilotBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        autoPilotBtnActionPerformed(evt);
      }
    });
    toolBar.add(autoPilotBtn);

    startAutoPilotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cruise-control-on-black.png"))); // NOI18N
    startAutoPilotBtn.setToolTipText("Auto mode");
    startAutoPilotBtn.setFocusable(false);
    startAutoPilotBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    startAutoPilotBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    startAutoPilotBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    startAutoPilotBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    startAutoPilotBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cruise-control-on-green.png"))); // NOI18N
    startAutoPilotBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    startAutoPilotBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        startAutoPilotBtnActionPerformed(evt);
      }
    });
    toolBar.add(startAutoPilotBtn);
    toolBar.add(filler1);

    selectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cursor-24-y.png"))); // NOI18N
    selectBtn.setToolTipText("Select");
    selectBtn.setFocusable(false);
    selectBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    selectBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    selectBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    selectBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    selectBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    selectBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectBtnActionPerformed(evt);
      }
    });
    toolBar.add(selectBtn);

    addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/add-24.png"))); // NOI18N
    addBtn.setToolTipText("Add");
    addBtn.setFocusable(false);
    addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    addBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    addBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    addBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addBtnActionPerformed(evt);
      }
    });
    toolBar.add(addBtn);

    deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/delete-24.png"))); // NOI18N
    deleteBtn.setToolTipText("Delete");
    deleteBtn.setFocusable(false);
    deleteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    deleteBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    deleteBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    deleteBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    deleteBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    deleteBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteBtnActionPerformed(evt);
      }
    });
    toolBar.add(deleteBtn);
    toolBar.add(filler3);

    gridBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/grid-2-24.png"))); // NOI18N
    gridBtn.setSelected(true);
    gridBtn.setToolTipText("Grid");
    gridBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gridBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/grid-dot-24.png"))); // NOI18N
    gridBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    gridBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gridBtnActionPerformed(evt);
      }
    });
    toolBar.add(gridBtn);
    toolBar.add(filler2);

    tileBtnGroup.add(straightBtn);
    straightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straight.png"))); // NOI18N
    straightBtn.setToolTipText("Straight Track");
    straightBtn.setDoubleBuffered(true);
    straightBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    straightBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    straightBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    straightBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    straightBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straight_Y.png"))); // NOI18N
    straightBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    straightBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        straightBtnActionPerformed(evt);
      }
    });
    toolBar.add(straightBtn);

    tileBtnGroup.add(curvedBtn);
    curvedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-diagonal.png"))); // NOI18N
    curvedBtn.setToolTipText("Curved Track");
    curvedBtn.setDoubleBuffered(true);
    curvedBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    curvedBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    curvedBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    curvedBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    curvedBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-diagonal_Y.png"))); // NOI18N
    curvedBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    curvedBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        curvedBtnActionPerformed(evt);
      }
    });
    toolBar.add(curvedBtn);

    tileBtnGroup.add(blockBtn);
    blockBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-block.png"))); // NOI18N
    blockBtn.setToolTipText("Block");
    blockBtn.setDoubleBuffered(true);
    blockBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    blockBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    blockBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    blockBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    blockBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-block_Y.png"))); // NOI18N
    blockBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    blockBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        blockBtnActionPerformed(evt);
      }
    });
    toolBar.add(blockBtn);

    tileBtnGroup.add(sensorBtn);
    sensorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straight-feedback.png"))); // NOI18N
    sensorBtn.setToolTipText("Sensor");
    sensorBtn.setDoubleBuffered(true);
    sensorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    sensorBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    sensorBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    sensorBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    sensorBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straight-feedback_Y.png"))); // NOI18N
    sensorBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    sensorBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sensorBtnActionPerformed(evt);
      }
    });
    toolBar.add(sensorBtn);

    tileBtnGroup.add(signalBtn);
    signalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straight-signal.png"))); // NOI18N
    signalBtn.setDoubleBuffered(true);
    signalBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    signalBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    signalBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    signalBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    signalBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straight-signal_Y.png"))); // NOI18N
    signalBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    signalBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        signalBtnActionPerformed(evt);
      }
    });
    toolBar.add(signalBtn);

    tileBtnGroup.add(leftSwitchBtn);
    leftSwitchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-L-turnout.png"))); // NOI18N
    leftSwitchBtn.setDoubleBuffered(true);
    leftSwitchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    leftSwitchBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    leftSwitchBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    leftSwitchBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    leftSwitchBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-LY-turnout.png"))); // NOI18N
    leftSwitchBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    leftSwitchBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        leftSwitchBtnActionPerformed(evt);
      }
    });
    toolBar.add(leftSwitchBtn);

    tileBtnGroup.add(rightSwitchBtn);
    rightSwitchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-R-turnout.png"))); // NOI18N
    rightSwitchBtn.setToolTipText("");
    rightSwitchBtn.setDoubleBuffered(true);
    rightSwitchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    rightSwitchBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    rightSwitchBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    rightSwitchBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    rightSwitchBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-RY-turnout.png"))); // NOI18N
    rightSwitchBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    rightSwitchBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rightSwitchBtnActionPerformed(evt);
      }
    });
    toolBar.add(rightSwitchBtn);

    tileBtnGroup.add(crossLBtn);
    crossLBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-cross-L.png"))); // NOI18N
    crossLBtn.setToolTipText("");
    crossLBtn.setDoubleBuffered(true);
    crossLBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    crossLBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    crossLBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    crossLBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    crossLBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-cross-LY.png"))); // NOI18N
    crossLBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    crossLBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        crossLBtnActionPerformed(evt);
      }
    });
    toolBar.add(crossLBtn);

    tileBtnGroup.add(crossRBtn);
    crossRBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-cross-R.png"))); // NOI18N
    crossRBtn.setToolTipText("");
    crossRBtn.setDoubleBuffered(true);
    crossRBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    crossRBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    crossRBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    crossRBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    crossRBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-cross-RY.png"))); // NOI18N
    crossRBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    crossRBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        crossRBtnActionPerformed(evt);
      }
    });
    toolBar.add(crossRBtn);

    tileBtnGroup.add(straightDirectionBtn);
    straightDirectionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straightDirection.png"))); // NOI18N
    straightDirectionBtn.setDoubleBuffered(true);
    straightDirectionBtn.setFocusable(false);
    straightDirectionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    straightDirectionBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    straightDirectionBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    straightDirectionBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    straightDirectionBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-straightDirection_Y.png"))); // NOI18N
    straightDirectionBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    straightDirectionBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        straightDirectionBtnActionPerformed(evt);
      }
    });
    toolBar.add(straightDirectionBtn);

    tileBtnGroup.add(endTrackBtn);
    endTrackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-end-track.png"))); // NOI18N
    endTrackBtn.setFocusable(false);
    endTrackBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    endTrackBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    endTrackBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    endTrackBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    endTrackBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-end-track_Y.png"))); // NOI18N
    endTrackBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    endTrackBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        endTrackBtnActionPerformed(evt);
      }
    });
    toolBar.add(endTrackBtn);

    tileBtnGroup.add(crossingBtn);
    crossingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-crossing.png"))); // NOI18N
    crossingBtn.setFocusable(false);
    crossingBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    crossingBtn.setMaximumSize(new java.awt.Dimension(38, 38));
    crossingBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    crossingBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    crossingBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    crossingBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        crossingBtnActionPerformed(evt);
      }
    });
    toolBar.add(crossingBtn);
    toolBar.add(filler4);

    moveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/drag-24.png"))); // NOI18N
    moveBtn.setToolTipText("Move");
    moveBtn.setFocusable(false);
    moveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    moveBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    moveBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    moveBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    moveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    moveBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        moveBtnActionPerformed(evt);
      }
    });
    toolBar.add(moveBtn);

    flipVerticalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/flip-vertical-24.png"))); // NOI18N
    flipVerticalBtn.setToolTipText("Flip Vertical");
    flipVerticalBtn.setFocusable(false);
    flipVerticalBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    flipVerticalBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    flipVerticalBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    flipVerticalBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    flipVerticalBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    flipVerticalBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        flipVerticalBtnActionPerformed(evt);
      }
    });
    toolBar.add(flipVerticalBtn);

    flipHorizontalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/flip-horizontal-24.png"))); // NOI18N
    flipHorizontalBtn.setToolTipText("Flip Horizontal");
    flipHorizontalBtn.setFocusable(false);
    flipHorizontalBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    flipHorizontalBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    flipHorizontalBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    flipHorizontalBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    flipHorizontalBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    flipHorizontalBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        flipHorizontalBtnActionPerformed(evt);
      }
    });
    toolBar.add(flipHorizontalBtn);

    rotateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/rotate2-24.png"))); // NOI18N
    rotateBtn.setToolTipText("Rotate");
    rotateBtn.setFocusable(false);
    rotateBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    rotateBtn.setMaximumSize(new java.awt.Dimension(40, 40));
    rotateBtn.setMinimumSize(new java.awt.Dimension(38, 38));
    rotateBtn.setPreferredSize(new java.awt.Dimension(38, 38));
    rotateBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    rotateBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rotateBtnActionPerformed(evt);
      }
    });
    toolBar.add(rotateBtn);

    topPanel.add(toolBar);

    add(topPanel, java.awt.BorderLayout.NORTH);

    canvasScrollPane.setDoubleBuffered(true);
    canvasScrollPane.setMinimumSize(new java.awt.Dimension(110, 110));
    canvasScrollPane.setPreferredSize(new java.awt.Dimension(1000, 700));
    canvasScrollPane.setViewportView(canvas);

    canvas.setMinimumSize(new java.awt.Dimension(100, 100));
    canvas.setPreferredSize(new java.awt.Dimension(895, 695));
    canvasScrollPane.setViewportView(canvas);

    add(canvasScrollPane, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void horizontalMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_horizontalMIActionPerformed
//      Logger.trace(this.orientation + ", " + evt.getModifiers() + ", " + evt.paramString());
//
//      if (this.mouseLocation != null && evt.getModifiers() == ActionEvent.MOUSE_EVENT_MASK) {
//          addTile(this.mouseLocation);
//          this.mouseLocation = null;
//      }
  }//GEN-LAST:event_horizontalMIActionPerformed

  private void verticalMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_verticalMIActionPerformed
//      Logger.trace(this.orientation + ", " + evt.getModifiers() + ", " + evt.paramString());
//
//      if (this.mouseLocation != null && evt.getModifiers() == ActionEvent.MOUSE_EVENT_MASK) {
//          addTile(this.mouseLocation);
//          this.mouseLocation = null;
//      }
  }//GEN-LAST:event_verticalMIActionPerformed

  private void rightMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rightMIActionPerformed
//      Logger.trace(this.orientation + ", " + evt.getModifiers() + ", " + evt.paramString());
//
//      if (this.mouseLocation != null && evt.getModifiers() == ActionEvent.MOUSE_EVENT_MASK) {
//          addTile(this.mouseLocation);
//          this.mouseLocation = null;
//      }
  }//GEN-LAST:event_rightMIActionPerformed

  private void leftMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_leftMIActionPerformed
//      Logger.trace(this.orientation + ", " + evt.getModifiers() + ", " + evt.paramString());
//
//      if (this.mouseLocation != null && evt.getModifiers() == ActionEvent.MOUSE_EVENT_MASK) {
//          addTile(this.mouseLocation);
//
//          //do someting with the rotation/direction...
//          this.mouseLocation = null;
//      }
  }//GEN-LAST:event_leftMIActionPerformed

    private void rotateMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rotateMIActionPerformed
//        rotateSelectedTile();
    }//GEN-LAST:event_rotateMIActionPerformed

    private void flipHorizontalMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_flipHorizontalMIActionPerformed
//        flipSelectedTileHorizontal();
    }//GEN-LAST:event_flipHorizontalMIActionPerformed

    private void flipVerticalMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_flipVerticalMIActionPerformed
//        flipSelectedTileVertical();
    }//GEN-LAST:event_flipVerticalMIActionPerformed

    private void moveMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_moveMIActionPerformed
//        this.mode = Mode.MOVE;
    }//GEN-LAST:event_moveMIActionPerformed

    private void deleteMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteMIActionPerformed
      this.canvas.removeTiles();
    }//GEN-LAST:event_deleteMIActionPerformed

    private void propertiesMIActionPerformed(ActionEvent evt) {//GEN-FIRST:event_propertiesMIActionPerformed
//        editSelectedTileProperties();
    }//GEN-LAST:event_propertiesMIActionPerformed

    private void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
      this.saveLayout();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void loadBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
      this.loadLayout();
    }//GEN-LAST:event_loadBtnActionPerformed

    private void selectBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
      setMode(LayoutCanvas.Mode.SELECT);
    }//GEN-LAST:event_selectBtnActionPerformed

    private void addBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
      setMode(LayoutCanvas.Mode.ADD);
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
      setMode(LayoutCanvas.Mode.DELETE);
      this.canvas.removeTiles();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void repaintBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_repaintBtnActionPerformed
      this.canvas.repaint();
    }//GEN-LAST:event_repaintBtnActionPerformed

    private void straightBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_straightBtnActionPerformed
      setTileType(TileBean.TileType.STRAIGHT);
    }//GEN-LAST:event_straightBtnActionPerformed

    private void curvedBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_curvedBtnActionPerformed
      setTileType(TileBean.TileType.CURVED);
    }//GEN-LAST:event_curvedBtnActionPerformed

    private void blockBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_blockBtnActionPerformed
      setTileType(TileBean.TileType.BLOCK);
    }//GEN-LAST:event_blockBtnActionPerformed

    private void rotateBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rotateBtnActionPerformed
      this.canvas.rotateSelectedTile();
    }//GEN-LAST:event_rotateBtnActionPerformed

    private void flipHorizontalBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_flipHorizontalBtnActionPerformed
      this.canvas.flipSelectedTileHorizontal();
    }//GEN-LAST:event_flipHorizontalBtnActionPerformed

    private void flipVerticalBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_flipVerticalBtnActionPerformed
      this.canvas.flipSelectedTileVertical();
    }//GEN-LAST:event_flipVerticalBtnActionPerformed

    private void moveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_moveBtnActionPerformed
      setMode(LayoutCanvas.Mode.MOVE);
    }//GEN-LAST:event_moveBtnActionPerformed

    private void rightSwitchBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_rightSwitchBtnActionPerformed
      this.setTileType(TileBean.TileType.SWITCH);
      this.setDirection(Direction.RIGHT);
    }//GEN-LAST:event_rightSwitchBtnActionPerformed

    private void leftSwitchBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_leftSwitchBtnActionPerformed
      this.setTileType(TileBean.TileType.SWITCH);
      this.setDirection(Direction.LEFT);
    }//GEN-LAST:event_leftSwitchBtnActionPerformed

    private void signalBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_signalBtnActionPerformed
      setTileType(TileBean.TileType.SIGNAL);
    }//GEN-LAST:event_signalBtnActionPerformed

    private void sensorBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sensorBtnActionPerformed
      setTileType(TileBean.TileType.SENSOR);
    }//GEN-LAST:event_sensorBtnActionPerformed

    private void gridBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_gridBtnActionPerformed
      this.canvas.setDrawGrid(this.gridBtn.isSelected());
      this.canvas.repaint();
    }//GEN-LAST:event_gridBtnActionPerformed

    private void formComponentResized(ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
      Logger.debug(evt.getComponent().getSize());// TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void crossLBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_crossLBtnActionPerformed
      setTileType(TileBean.TileType.CROSS);
      this.setDirection(Direction.LEFT);
    }//GEN-LAST:event_crossLBtnActionPerformed

    private void crossRBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_crossRBtnActionPerformed
      setTileType(TileBean.TileType.CROSS);
      this.setDirection(Direction.RIGHT);
    }//GEN-LAST:event_crossRBtnActionPerformed

    private void routeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_routeBtnActionPerformed
      Logger.debug("Start Routing...");
      this.canvas.showRoutesDialog();
    }//GEN-LAST:event_routeBtnActionPerformed

    private void formComponentHidden(ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
      Logger.trace("HIDDEN");
      if (JCS.getParentFrame() != null) {
        JCS.getParentFrame().hideExtraToolbar(this.toolBar);
      }
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      Logger.trace("SHOWN");
      if (JCS.getParentFrame() != null) {
        topPanel.remove(this.toolBar);
        this.remove(topPanel);
        this.doLayout();
        JCS.getParentFrame().showExtraToolbar(this.toolBar);
      }
    }//GEN-LAST:event_formComponentShown

  private void straightDirectionBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_straightDirectionBtnActionPerformed
    setTileType(TileBean.TileType.STRAIGHT_DIR);
  }//GEN-LAST:event_straightDirectionBtnActionPerformed

  private void endTrackBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_endTrackBtnActionPerformed
    setTileType(TileBean.TileType.END);
  }//GEN-LAST:event_endTrackBtnActionPerformed

  private void autoPilotBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_autoPilotBtnActionPerformed
    Logger.trace(evt.getActionCommand() + " Enable Auto mode " + this.autoPilotBtn.isSelected());

  }//GEN-LAST:event_autoPilotBtnActionPerformed

  private void startAutoPilotBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_startAutoPilotBtnActionPerformed
    Logger.trace(evt.getActionCommand() + " Start Auto mode " + this.autoPilotBtn.isSelected());

  }//GEN-LAST:event_startAutoPilotBtnActionPerformed

  private void crossingBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_crossingBtnActionPerformed
    setTileType(TileBean.TileType.CROSSING);
  }//GEN-LAST:event_crossingBtnActionPerformed

  private void setTileType(TileBean.TileType tileType) {
    this.canvas.setTileType(tileType);
  }

  private void setDirection(Direction direction) {
    this.canvas.setDirection(direction);
  }

  private void setMode(LayoutCanvas.Mode mode) {
    switch (mode) {
      case SELECT -> {
        selectBtn.setIcon(new ImageIcon(getClass().getResource("/media/cursor-24-y.png")));
        addBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24.png")));
        deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24.png")));
      }
      case ADD -> {
        addBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24-y.png")));
        selectBtn.setIcon(new ImageIcon(getClass().getResource("/media/cursor-24.png")));
        deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24.png")));
      }
      case DELETE -> {
        deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24-y.png")));
        selectBtn.setIcon(new ImageIcon(getClass().getResource("/media/cursor-24.png")));
        addBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24.png")));
      }
      default -> {
        Logger.warn("Mode setting which should not ever happen " + mode);
        selectBtn.setIcon(new ImageIcon(getClass().getResource("/media/cursor-24.png")));
        addBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24.png")));
        deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24.png")));
      }
    }

    this.canvas.setMode(mode);
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addBtn;
  private javax.swing.JToggleButton autoPilotBtn;
  private javax.swing.JToggleButton blockBtn;
  private jcs.ui.layout.LayoutCanvas canvas;
  private javax.swing.JScrollPane canvasScrollPane;
  private javax.swing.JToggleButton crossLBtn;
  private javax.swing.JToggleButton crossRBtn;
  private javax.swing.JToggleButton crossingBtn;
  private javax.swing.JToggleButton curvedBtn;
  private javax.swing.JPopupMenu curvedPopupMenu;
  private javax.swing.JButton deleteBtn;
  private javax.swing.JMenuItem deleteMI;
  private javax.swing.JToggleButton endTrackBtn;
  private javax.swing.Box.Filler filler1;
  private javax.swing.Box.Filler filler2;
  private javax.swing.Box.Filler filler3;
  private javax.swing.Box.Filler filler4;
  private javax.swing.JButton flipHorizontalBtn;
  private javax.swing.JMenuItem flipHorizontalMI;
  private javax.swing.JButton flipVerticalBtn;
  private javax.swing.JMenuItem flipVerticalMI;
  private javax.swing.JToggleButton gridBtn;
  private javax.swing.JMenuItem horizontalMI;
  private javax.swing.JMenuItem leftMI;
  private javax.swing.JToggleButton leftSwitchBtn;
  private javax.swing.JButton loadBtn;
  private javax.swing.JButton moveBtn;
  private javax.swing.JMenuItem moveMI;
  private javax.swing.JPopupMenu operationsPM;
  private javax.swing.JMenuItem propertiesMI;
  private javax.swing.JButton repaintBtn;
  private javax.swing.JMenuItem rightMI;
  private javax.swing.JToggleButton rightSwitchBtn;
  private javax.swing.JButton rotateBtn;
  private javax.swing.JMenuItem rotateMI;
  private javax.swing.JButton routeBtn;
  private javax.swing.JButton saveBtn;
  private javax.swing.JButton selectBtn;
  private javax.swing.JToggleButton sensorBtn;
  private javax.swing.JToggleButton signalBtn;
  private javax.swing.JToggleButton startAutoPilotBtn;
  private javax.swing.JToggleButton straightBtn;
  private javax.swing.JToggleButton straightDirectionBtn;
  private javax.swing.JPopupMenu straightPopupMenu;
  private javax.swing.ButtonGroup tileBtnGroup;
  private javax.swing.JToolBar toolBar;
  private javax.swing.JPanel topPanel;
  private javax.swing.JMenuItem verticalMI;
  private javax.swing.JMenuItem xyMI;
  // End of variables declaration//GEN-END:variables
}
