/*
 * Copyright 2023 frans.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.table;

import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultRowSorter;
import javax.swing.JFrame;
import javax.swing.RowSorter;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.RowSorterEvent;
import javax.swing.event.RowSorterListener;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jcs.entities.LocomotiveBean;
import jcs.persistence.PersistenceFactory;
import jcs.ui.table.model.LocomotiveBeanTableModel;
import org.tinylog.Logger;

/**
 *
 * @author frans
 */
public class LocomotiveTablePanel extends javax.swing.JPanel {

  /**
   * Creates new form LocomotiveTablePanel
   */
  public LocomotiveTablePanel() {
    locomotiveBeanTableModel = new LocomotiveBeanTableModel();

    initComponents();
    //this.jTable1.setRowSorter(new TableRowSorter<>(this.locomotiveBeanTableModel));

    this.jTable1.getRowSorter().addRowSorterListener(new RowSorterListener() {
      @Override
      public void sorterChanged(RowSorterEvent e) {
        Logger.trace(e.getType()+","+e.getSource().getSortKeys());// Sorting changed
      }
    });

    initModel();
  }

  private void initModel() {
    List<LocomotiveBean> locomotiveBeans = PersistenceFactory.getService().getLocomotives();
    Logger.trace("Found " + locomotiveBeans.size() + " Locomotives");
    locomotiveBeanTableModel.setBeans(locomotiveBeans);
  }

  private TableCellRenderer getCellRenderer() {
    TableCellRenderer renderer = (tbl, value, isSelected, hasFocus, row, column) -> {
      TableCellRenderer r = tbl.getTableHeader().getDefaultRenderer();
      Component c = r.getTableCellRendererComponent(tbl, value, isSelected, hasFocus, row, column);
      RowSorter<? extends TableModel> rs = tbl.getRowSorter();
      if (rs instanceof DefaultRowSorter) {
        int cmi = tbl.convertColumnIndexToModel(column);
        c.setForeground(((DefaultRowSorter<?, ?>) rs).isSortable(cmi) ? Color.BLACK : Color.GRAY);
      }
      return c;
    };
    return renderer;
  }

  public static void main(String args[]) {
    try {
      String plaf = System.getProperty("jcs.plaf", "com.formdev.flatlaf.FlatLightLaf");
      if (plaf != null) {
        UIManager.setLookAndFeel(plaf);
      } else {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.error(ex);
    }

    java.awt.EventQueue.invokeLater(() -> {

      LocomotiveTablePanel testPanel = new LocomotiveTablePanel();
      JFrame testFrame = new JFrame("LocomotiveTablePanel Tester");

      testFrame.add(testPanel);

      testFrame.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      testFrame.pack();
      testFrame.setLocationRelativeTo(null);

      //testPanel.loadLocomotives();
      testPanel.locomotiveBeanTableModel.refresh();
      testFrame.setVisible(true);
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    locomotiveBeanTableModel = new jcs.ui.table.model.LocomotiveBeanTableModel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();

    setLayout(new java.awt.BorderLayout());

    jScrollPane1.setViewportView(jTable1);

    jTable1.setModel(locomotiveBeanTableModel);
    jTable1.setDoubleBuffered(true);
    jTable1.setRowSorter(new TableRowSorter<>(locomotiveBeanTableModel));
    jTable1.setShowGrid(true);
    jScrollPane1.setViewportView(jTable1);

    add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

    jButton1.setText("Refresh");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);

    jButton2.setText("jButton2");
    jPanel1.add(jButton2);

    add(jPanel1, java.awt.BorderLayout.NORTH);

    jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 50, Short.MAX_VALUE)
    );

    add(jPanel2, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.locomotiveBeanTableModel.refresh();
  }//GEN-LAST:event_jButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private jcs.ui.table.model.LocomotiveBeanTableModel locomotiveBeanTableModel;
  // End of variables declaration//GEN-END:variables
}
