<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>jcs</groupId>
    <artifactId>jcs</artifactId>
    <version>0.0.4-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>JCS</name>
    <url>https://github.com/fransjacobs/model-railway</url>
    <description>Java Central Station</description>
    <inceptionYear>2018</inceptionYear>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>25</java.version>
        <packaging>jar</packaging>
        <app.main.class>jcs.JCS</app.main.class>
        <maven.compiler.release>25</maven.compiler.release>
        <app.distribution.directory>${project.build.directory}/distributions/app</app.distribution.directory>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss z</maven.build.timestamp.format>
        <!-- default for local builds -->
        <jpackage.type>APP_IMAGE</jpackage.type>
        <!--        
        [WARNING] Parameter 'linux' is unknown for plugin 'jpackage-maven-plugin:1.8.0:jpackage (default)'
        [WARNING] Parameter 'win' is unknown for plugin 'jpackage-maven-plugin:1.8.0:jpackage (default)'
        [WARNING] Parameter 'mac' is unknown for plugin 'jpackage-maven-plugin:1.8.0:jpackage (default)'
        -->
    </properties>    
    <licenses>
        <license>
            <name>Apache-2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Frans Jacobs</name>
            <email>frans.jacobs-at-gmail.com</email>
        </developer>
    </developers>
    <dependencies>
        <dependency>
            <groupId>org.tinylog</groupId>
            <artifactId>tinylog-api</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.tinylog</groupId>
            <artifactId>tinylog-impl</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>2.4.240</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.20.0</version>
        </dependency>
        <dependency>
            <groupId>org.beryx</groupId>
            <artifactId>awt-color-factory</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>2.0.18</version>
        </dependency>
        <dependency>
            <groupId>com.dieselpoint</groupId>
            <artifactId>norm</artifactId>
            <version>1.2</version>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>7.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20260522</version>
        </dependency>
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-batik</artifactId>
            <version>3.14.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang3</artifactId>
                </exclusion>
            </exclusions>     
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-transcoder</artifactId>
            <version>1.19</version>
            <exclusions>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
            </exclusions>            
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>6.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>6.1.2</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>apiguardian-api</artifactId>
                    <groupId>org.apiguardian</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>6.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.27.7</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>byte-buddy</artifactId>
                    <groupId>net.bytebuddy</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>3.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.23.0</version>
            <scope>test</scope>
        </dependency>        
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>3.7.2</version>
        </dependency>
        <dependency>
            <groupId>org.httprpc</groupId>
            <artifactId>sierra</artifactId>
            <version>4.6.6</version>
        </dependency>
        <dependency>
            <groupId>eu.hansolo</groupId>
            <artifactId>SteelSeries</artifactId>
            <version>3.9.30</version>
        </dependency>
        <dependency>
            <groupId>org.imgscalr</groupId>
            <artifactId>imgscalr-lib</artifactId>
            <version>4.2</version>
        </dependency> 
        <dependency>
            <groupId>com.fazecast</groupId>
            <artifactId>jSerialComm</artifactId>
            <version>2.11.4</version>
        </dependency>
        <dependency>
            <groupId>com.shinyhut</groupId>
            <artifactId>vernacular</artifactId>
            <version>1.14</version>
        </dependency>
        <dependency>
            <groupId>net.straylightlabs</groupId>
            <artifactId>hola</artifactId>
            <version>0.2.3</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.38</version>
        </dependency>
        <dependency>
            <groupId>com.miglayout</groupId>
            <artifactId>miglayout-core</artifactId>
            <version>11.4.3</version>
        </dependency>
        <dependency>
            <groupId>com.miglayout</groupId>
            <artifactId>miglayout-swing</artifactId>
            <version>11.4.3</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.external</groupId>
            <artifactId>AbsoluteLayout</artifactId>
            <version>RELEASE300</version>
        </dependency>
    </dependencies>
    <build>     
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.panteleyev</groupId>
                    <artifactId>jpackage-maven-plugin</artifactId>
                    <version>1.8.0</version>
                    <configuration>
                        <name>jcs</name>
                        <appVersion>1.0.0</appVersion>
                        <type>${jpackage.type}</type>    <!-- ← driven by property -->
                        <input>${project.build.directory}</input>
                        <mainJar>${project.build.finalName}.jar</mainJar>
                        <mainClass>${app.main.class}</mainClass>
                        <vendor>Frans Jacobs</vendor>
                        <copyright>Frans Jacobs</copyright>
                        <description>JCS is model railroad automation software</description>
                        <destination>${project.build.directory}/jpackage</destination>
                        <javaOptions>
                            <option>-Dfile.encoding=UTF-8</option>
                            <option>-Xms256m</option>
                            <option>-Xmx1024m</option>
                            <option>--enable-native-access=ALL-UNNAMED</option>
                        </javaOptions>

                        <macPackageIdentifier>jcs</macPackageIdentifier>
                        <winConsole>false</winConsole>
                        <winMenuGroup>JCS</winMenuGroup>
                        <winShortcut>true</winShortcut>
                        <linuxMenuGroup>Education</linuxMenuGroup>
                        <linuxShortcut>true</linuxShortcut>
                        <icon>${app.icon}</icon>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.6.2</version>
                    <configuration>
                        <transformers>
                            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                <mainClass>${app.main.class}</mainClass>
                            </transformer>
                            <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                        </transformers>
                        <filters>
                            <filter>
                                <artifact>*:*</artifact>
                                <excludes>
                                    <exclude>module-info.class</exclude>
                                    <exclude>META-INF/*.txt</exclude>
                                    <exclude>META-INF/*.SF</exclude>
                                    <exclude>META-INF/*.DSA</exclude>
                                    <exclude>META-INF/*.RSA</exclude>
                                    <exclude>META-INF/NOTICE</exclude>
                                    <exclude>META-INF/LICENSE</exclude>
                                    <exclude>META-INF/MANIFEST.MF</exclude>
                                    <!-- Fix path format for multi-release module descriptors -->
                                    <exclude>META-INF/versions/**/module-info.class</exclude>
                                    <exclude>META-INF/services/org.slf4j.spi.SLF4JServiceProvider</exclude>
                                </excludes>
                            </filter>
                        </filters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>templating-maven-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>3.6.3</version>
                    <configuration>
                        <mainClass>${app.main.class}</mainClass>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.15.0</version>
                    <configuration>
                        <!--compilerArgs>-Xlint:unchecked,-verbose</compilerArgs-->
                        <compilerArgs>-verbose</compilerArgs>
                        <release>25</release>
                        <showDeprecation>true</showDeprecation>
                    </configuration>
                </plugin>  
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>4.10.3.0</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.github.spotbugs</groupId>
                            <artifactId>spotbugs</artifactId>
                            <version>4.10.3</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.11.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.5.0</version>              
                    <configuration>
                        <encoding>UTF-8</encoding>
                        <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
                        <nonFilteredFileExtensions>
                            <nonFilteredFileExtension>db:encryptable</nonFilteredFileExtension>
                            <nonFilteredFileExtension>db</nonFilteredFileExtension>
                            <nonFilteredFileExtension>png</nonFilteredFileExtension>
                            <nonFilteredFileExtension>icns</nonFilteredFileExtension>
                        </nonFilteredFileExtensions>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.6</version>
                    <configuration>
                        <!--testFailureIgnore>false</testFailureIgnore-->
                        <argLine>-Dfile.encoding=UTF-8</argLine>
                        <parallel>false</parallel>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>3.1.4</version>
                    <configuration>
                        <packaging>jar</packaging>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>3.6.0</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.puppycrawl.tools</groupId>
                            <artifactId>checkstyle</artifactId>
                            <version>10.26.1</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>3.6.3</version>
                    <configuration>
                        <rules>
                            <requireMavenVersion>
                                <version>3.2.5</version>
                            </requireMavenVersion>
                        </rules>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <version>2.7.1</version>
                    <configuration>
                        <licensesOutputDirectory>${project.build.directory}/generated-resources/licenses</licensesOutputDirectory>
                        <useRepositoryContent>true</useRepositoryContent>
                        <cacheDir>${project.build.directory}/license-cache</cacheDir>
                        <licenseMerges>
                            <licenseMerge>GNU Lesser General Public License</licenseMerge>
                            <licenseMerge>LGPL-2.1</licenseMerge>
                        </licenseMerges>
                        <licenseMap>
                            <license>
                                <name>GNU Lesser General Public License</name>
                                <url>https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt</url>
                            </license>
                            <license>
                                <name>OpenJDK GPLv2 + Classpath Exception</name>
                                <url>https://openjdk.org/legal/gplv2+ce.html</url>
                            </license>
                        </licenseMap>
                        <licenseUrlMap>
                            <licenseUrl>
                                <match>http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html</match>
                                <replacement>https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt</replacement>
                            </licenseUrl>
                            <licenseUrl>
                                <match>http://www.gnu.org/licenses/lgpl.html</match>
                                <replacement>https://www.gnu.org/licenses/lgpl-2.1.txt</replacement>
                            </licenseUrl>
                            <licenseUrl>
                                <match>https://openjdk.java.net/legal/gplv2+ce.html</match>
                                <replacement>https://openjdk.org/legal/gplv2+ce.html</replacement>
                            </licenseUrl>
                            <licenseUrl>
                                <match>/LICENSE.txt</match>
                                <replacement>https://raw.githubusercontent.com/apache/commons-logging/master/LICENSE.txt</replacement>
                            </licenseUrl>
                        </licenseUrlMap>
                    </configuration>
                </plugin>  
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>3.2.8</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>templating-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-jcs-version</id>
                        <goals>
                            <goal>filter-sources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>  
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <executions>
                    <execution>
                        <id>checkstyle</id>
                        <phase>checkstyle</phase>
                        <goals>
                            <goal>checkstyle</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-maven</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>aggregate-download-licenses</id>
                        <phase>none</phase>
                        <goals>
                            <goal>aggregate-download-licenses</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>  
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>tinylog-dev.properties</exclude>
                    <exclude>*.db</exclude>
                    <exclude>*.db:encryptable</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/test/resources</directory>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>${project.basedir}/licenses</directory>
                <targetPath>META-INF/licenses</targetPath>
                <includes>
                    <include>**/*.txt</include>
                </includes>
            </resource>
        </resources> 
    </build>
    <profiles>
        <profile>
            <id>linux-icon</id>
            <activation>
                <os>
                    <family>unix</family>
                    <name>!mac os x</name>
                </os>
            </activation>
            <properties>
                <app.icon>${project.basedir}/config/jpackage/resources/JCS.png</app.icon>
            </properties>
        </profile>
        <profile>
            <id>win-icon</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <app.icon>${project.basedir}/config/jpackage/resources/JCS.ico</app.icon>
            </properties>
        </profile>
        <profile>
            <id>mac-icon</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <app.icon>${project.basedir}/config/jpackage/resources/JCS.icns</app.icon>
            </properties>
        </profile>
        <profile>
            <id>no-app</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>aggregate-download-licenses</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>none</phase>
                                <goals>
                                    <goal>none</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>package-app</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>verify</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>update-licenses</id>
            <build>
                <plugins>    
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>aggregate-download-licenses</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>aggregate-download-licenses</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
