/*
 * Copyright (C) 2020 fransjacobs.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package lan.wervel.jcs.ui.layout;

import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import lan.wervel.jcs.entities.LayoutTile;
import lan.wervel.jcs.entities.Sensor;
import lan.wervel.jcs.trackservice.TrackServiceFactory;
import lan.wervel.jcs.ui.layout.tiles.OccupancyDetector;
import org.pmw.tinylog.Logger;

/**
 *
 * @author fransjacobs
 */
public class OccupancySensorDialog extends javax.swing.JDialog {

    private final OccupancyDetector tile;

    public OccupancySensorDialog(java.awt.Frame parent, boolean modal, OccupancyDetector tile) {
        super(parent, modal);
        this.tile = tile;

        initComponents();
        postInit();
    }

    private void postInit() {
        LayoutTile lt = tile.getLayoutTile();
        if (lt.getSensor() != null) {
            Sensor fm = lt.getSensor();
            this.sensorCB.setSelectedItem(fm);
        }
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/media/jcs-train-64.png")));
        this.setLocation(tile.getCenter());
    }

    private ComboBoxModel<Sensor> getSensorComboBoxModel() {
        ComboBoxModel sensorCBM;
        if (TrackServiceFactory.getTrackService() != null) {
            List<Sensor> sl = new ArrayList<>();
            Sensor def = new Sensor();
            def.setName("-");
            sl.add(def);
            sl.addAll(TrackServiceFactory.getTrackService().getSensors());

            Sensor[] sens = new Sensor[sl.size()];
            sl.toArray(sens);

            sensorCBM = new DefaultComboBoxModel<>(sens);
        } else {
            sensorCBM = new DefaultComboBoxModel<>();
        }
        return sensorCBM;
    }

    private void setSensor() {
        Sensor s = (Sensor) this.sensorCB.getSelectedItem();
        Logger.trace("Selected Sensor: "+s);

        if (this.tile.getLayoutTile() != null && s != null) {
            if ("-".equals(s.getName())) {
                this.tile.getLayoutTile().setSensor(null);
                this.moduleLbl.setText("Module #: -");
            } else {
                Logger.trace("Setting Sensor " + s);
                this.tile.getLayoutTile().setSensor(s);
                this.moduleLbl.setText("Module #: " + Sensor.calculateModuleNumber(s.getContactId()) + " Port#: " + Sensor.calculatePortNumber(s.getContactId()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sensorLbl = new javax.swing.JLabel();
        sensorCB = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        moduleLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        sensorLbl.setText("Sensor:");
        sensorLbl.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel1.add(sensorLbl);

        sensorCB.setModel(getSensorComboBoxModel());
        sensorCB.setPreferredSize(new java.awt.Dimension(150, 27));
        sensorCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sensorCBActionPerformed(evt);
            }
        });
        jPanel1.add(sensorCB);

        getContentPane().add(jPanel1);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        moduleLbl.setText("Module #:");
        jPanel3.add(moduleLbl);

        getContentPane().add(jPanel3);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(closeBtn);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sensorCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sensorCBActionPerformed
        setSensor();
    }//GEN-LAST:event_sensorCBActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel moduleLbl;
    private javax.swing.JComboBox<Sensor> sensorCB;
    private javax.swing.JLabel sensorLbl;
    // End of variables declaration//GEN-END:variables
}
