/*
 * Copyright 2025 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.layout.tiles.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jcs.entities.AccessoryBean.AccessoryValue;
import jcs.entities.TileBean;
import jcs.ui.layout.tiles.CrossSwitch;
import jcs.ui.layout.tiles.Tile;
import org.tinylog.Logger;

public class CrossSwitchTileTester extends javax.swing.JFrame {

  private Tile crossSwitchEastR;
  private Tile crossSwitchSouthR;
  private Tile crossSwitchWestR;
  private Tile crossSwitchNorthR;

  private Tile crossSwitchEastL;
  private Tile crossSwitchSouthL;
  private Tile crossSwitchWestL;
  private Tile crossSwitchNorthL;

  /**
   * Creates new form TileTester
   *
   * @param title
   */
  public CrossSwitchTileTester(String title) {
    super(title);
    initComponents();

    createTiles();

    this.setVisible(true);
  }

  private void createTiles() {

    crossSwitchEastR = new CrossSwitch(TileBean.Orientation.EAST, TileBean.Direction.RIGHT, 60, 60);
    crossSwitchEastR.setId("eastR");
    crossSwitchEastR.setTrackRouteColor(Color.MAGENTA);
    crossSwitchEastR.setRouteValue(AccessoryValue.GREEN);

    crossSwitchSouthR = new CrossSwitch(TileBean.Orientation.SOUTH, TileBean.Direction.RIGHT, 180, 60);
    crossSwitchSouthR.setId("southR");
    crossSwitchSouthR.setTrackRouteColor(Color.YELLOW);
    crossSwitchSouthR.setRouteValue(AccessoryValue.RED);

    crossSwitchWestR = new CrossSwitch(TileBean.Orientation.WEST, TileBean.Direction.RIGHT, 380, 60);
    crossSwitchWestR.setId("westR");
    crossSwitchWestR.setTrackRouteColor(Color.CYAN);

    crossSwitchNorthR = new CrossSwitch(TileBean.Orientation.NORTH, TileBean.Direction.RIGHT, 180, 220);
    crossSwitchNorthR.setId("northR");
    crossSwitchNorthR.setTrackRouteColor(Color.blue);
    crossSwitchNorthR.setRouteValue(AccessoryValue.GREEN);

    crossSwitchEastL = new CrossSwitch(TileBean.Orientation.EAST, TileBean.Direction.LEFT, 60, 140);
    crossSwitchEastL.setId("eastL");
    crossSwitchEastL.setTrackRouteColor(Color.MAGENTA);
    crossSwitchEastL.setRouteValue(AccessoryValue.GREEN);

    crossSwitchSouthL = new CrossSwitch(TileBean.Orientation.SOUTH, TileBean.Direction.LEFT, 260, 60);
    crossSwitchSouthL.setId("southL");
    crossSwitchSouthL.setTrackRouteColor(Color.YELLOW);
    crossSwitchSouthL.setRouteValue(AccessoryValue.RED);

    crossSwitchWestL = new CrossSwitch(TileBean.Orientation.WEST, TileBean.Direction.LEFT, 380, 140);
    crossSwitchWestL.setId("westL");
    crossSwitchWestL.setTrackRouteColor(Color.CYAN);

    crossSwitchNorthL = new CrossSwitch(TileBean.Orientation.NORTH, TileBean.Direction.LEFT, 260, 220);
    crossSwitchNorthL.setId("northL");
    crossSwitchNorthL.setTrackRouteColor(Color.blue);
    crossSwitchNorthL.setRouteValue(AccessoryValue.GREEN);

    dotGridCanvas.add(crossSwitchEastR);
    dotGridCanvas.add(crossSwitchSouthR);
    dotGridCanvas.add(crossSwitchWestR);
    dotGridCanvas.add(crossSwitchNorthR);

    dotGridCanvas.add(crossSwitchEastL);
    dotGridCanvas.add(crossSwitchSouthL);
    dotGridCanvas.add(crossSwitchWestL);
    dotGridCanvas.add(crossSwitchNorthL);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    toolbarPanel = new javax.swing.JPanel();
    toolBar = new javax.swing.JToolBar();
    eastTileBtn = new javax.swing.JToggleButton();
    southTileBtn = new javax.swing.JToggleButton();
    westTileBtn = new javax.swing.JToggleButton();
    northTileBtn = new javax.swing.JToggleButton();
    selectSouthTileBtn = new javax.swing.JToggleButton();
    drawCenterBtn = new javax.swing.JToggleButton();
    greenRedBtn = new javax.swing.JToggleButton();
    dotGridCanvas = new jcs.ui.layout.tiles.ui.DotGridCanvas();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout1.setAlignOnBaseline(true);
    toolbarPanel.setLayout(flowLayout1);

    toolBar.setRollover(true);

    eastTileBtn.setText("East");
    eastTileBtn.setFocusable(false);
    eastTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    eastTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    eastTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        eastTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(eastTileBtn);

    southTileBtn.setText("South");
    southTileBtn.setFocusable(false);
    southTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    southTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    southTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        southTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(southTileBtn);

    westTileBtn.setText("West");
    westTileBtn.setFocusable(false);
    westTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    westTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    westTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        westTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(westTileBtn);

    northTileBtn.setText("North");
    northTileBtn.setFocusable(false);
    northTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    northTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    northTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        northTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(northTileBtn);

    selectSouthTileBtn.setText("Select Tile");
    selectSouthTileBtn.setFocusable(false);
    selectSouthTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    selectSouthTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    selectSouthTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectSouthTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(selectSouthTileBtn);

    drawCenterBtn.setText("show Center");
    drawCenterBtn.setFocusable(false);
    drawCenterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    drawCenterBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    drawCenterBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        drawCenterBtnActionPerformed(evt);
      }
    });
    toolBar.add(drawCenterBtn);

    greenRedBtn.setText("Red");
    greenRedBtn.setFocusable(false);
    greenRedBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    greenRedBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    greenRedBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        greenRedBtnActionPerformed(evt);
      }
    });
    toolBar.add(greenRedBtn);

    toolbarPanel.add(toolBar);

    getContentPane().add(toolbarPanel, java.awt.BorderLayout.NORTH);

    dotGridCanvas.setPreferredSize(new java.awt.Dimension(480, 320));
    getContentPane().add(dotGridCanvas, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void northTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northTileBtnActionPerformed
    Logger.trace(crossSwitchNorthR.getId() + "...");
    this.crossSwitchNorthR.setShowRoute(this.northTileBtn.isSelected());
    this.crossSwitchNorthL.setShowRoute(this.northTileBtn.isSelected());
  }//GEN-LAST:event_northTileBtnActionPerformed

  private void eastTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastTileBtnActionPerformed
    this.crossSwitchEastR.setShowRoute(this.eastTileBtn.isSelected());
    this.crossSwitchEastL.setShowRoute(this.eastTileBtn.isSelected());
  }//GEN-LAST:event_eastTileBtnActionPerformed

  private void westTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westTileBtnActionPerformed
    this.crossSwitchWestR.setShowRoute(this.westTileBtn.isSelected());
    this.crossSwitchWestL.setShowRoute(this.westTileBtn.isSelected());
  }//GEN-LAST:event_westTileBtnActionPerformed

  private void southTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southTileBtnActionPerformed
    this.crossSwitchSouthR.setShowRoute(this.southTileBtn.isSelected());
    this.crossSwitchSouthL.setShowRoute(this.southTileBtn.isSelected());
  }//GEN-LAST:event_southTileBtnActionPerformed

  private void selectSouthTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSouthTileBtnActionPerformed
    this.crossSwitchSouthR.setSelected(this.selectSouthTileBtn.isSelected());
    this.crossSwitchSouthL.setSelected(this.selectSouthTileBtn.isSelected());
  }//GEN-LAST:event_selectSouthTileBtnActionPerformed

  private void drawCenterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawCenterBtnActionPerformed
    this.crossSwitchEastR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSwitchEastL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSwitchSouthR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSwitchSouthL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSwitchWestR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSwitchWestL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSwitchNorthR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSwitchNorthL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
  }//GEN-LAST:event_drawCenterBtnActionPerformed

  private void greenRedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenRedBtnActionPerformed
    boolean red = this.greenRedBtn.isSelected();
    if (red) {
      this.greenRedBtn.setText("Green");
      if (this.westTileBtn.isSelected()) {
        this.crossSwitchWestR.setAccessoryValue(AccessoryValue.OFF);
        this.crossSwitchWestR.setRouteValue(AccessoryValue.GREEN);

        this.crossSwitchWestL.setAccessoryValue(AccessoryValue.OFF);
        this.crossSwitchWestL.setRouteValue(AccessoryValue.GREEN);
      } else {
        this.crossSwitchWestR.setAccessoryValue(AccessoryValue.GREEN);
        this.crossSwitchWestL.setAccessoryValue(AccessoryValue.GREEN);
      }
    } else {
      this.greenRedBtn.setText("Red");
      if (this.westTileBtn.isSelected()) {
        this.crossSwitchWestR.setAccessoryValue(AccessoryValue.OFF);
        this.crossSwitchWestR.setRouteValue(AccessoryValue.RED);

        this.crossSwitchWestL.setAccessoryValue(AccessoryValue.OFF);
        this.crossSwitchWestL.setRouteValue(AccessoryValue.RED);
      } else {
        this.crossSwitchWestR.setAccessoryValue(AccessoryValue.RED);
        this.crossSwitchWestL.setAccessoryValue(AccessoryValue.RED);
      }
    }
  }//GEN-LAST:event_greenRedBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
      CrossSwitchTileTester.setDefaultLookAndFeelDecorated(true);

    } catch (ClassNotFoundException
            | InstantiationException
            | IllegalAccessException
            | UnsupportedLookAndFeelException ex) {
      Logger.error(ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      CrossSwitchTileTester app = new CrossSwitchTileTester("Switch Tile Tester");
      app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
      app.setLocation(dim.width / 2 - app.getSize().width / 2, dim.height / 2 - app.getSize().height / 2);
      app.pack();
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private jcs.ui.layout.tiles.ui.DotGridCanvas dotGridCanvas;
  private javax.swing.JToggleButton drawCenterBtn;
  private javax.swing.JToggleButton eastTileBtn;
  private javax.swing.JToggleButton greenRedBtn;
  private javax.swing.JToggleButton northTileBtn;
  private javax.swing.JToggleButton selectSouthTileBtn;
  private javax.swing.JToggleButton southTileBtn;
  private javax.swing.JToolBar toolBar;
  private javax.swing.JPanel toolbarPanel;
  private javax.swing.JToggleButton westTileBtn;
  // End of variables declaration//GEN-END:variables
}
