/*
 * Copyright 2025 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.layout.tiles.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jcs.entities.TileBean;
import jcs.ui.layout.tiles.Sensor;
import jcs.ui.layout.tiles.Tile;
import org.tinylog.Logger;

public class SensorTileTester extends javax.swing.JFrame {

  private Tile sensorEast;
  private Tile sensorSouth;
  private Tile sensorWest;
  private Tile sensorNorth;

  /**
   * Creates new form TileTester
   *
   * @param title
   */
  public SensorTileTester(String title) {
    super(title);
    initComponents();

    createTiles();

    this.setVisible(true);
  }

  private void createTiles() {

    sensorEast = new Sensor(TileBean.Orientation.EAST, 40, 40);
    sensorEast.setId("east");
    sensorEast.setTrackRouteColor(Color.MAGENTA);

    sensorSouth = new Sensor(TileBean.Orientation.SOUTH, 120, 40);
    sensorSouth.setId("south");
    sensorSouth.setTrackRouteColor(Color.YELLOW);

    sensorWest = new Sensor(TileBean.Orientation.WEST, 200, 40);
    sensorWest.setId("west");
    sensorWest.setTrackRouteColor(Color.CYAN);

    sensorNorth = new Sensor(TileBean.Orientation.NORTH, 280, 40);
    sensorNorth.setId("north");
    sensorNorth.setTrackRouteColor(Color.blue);

    dotGridCanvas.add(sensorEast);

    dotGridCanvas.add(sensorSouth);
    dotGridCanvas.add(sensorWest);
    dotGridCanvas.add(sensorNorth);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    toolbarPanel = new javax.swing.JPanel();
    toolBar = new javax.swing.JToolBar();
    eastTileBtn = new javax.swing.JToggleButton();
    southTileBtn = new javax.swing.JToggleButton();
    westTileBtn = new javax.swing.JToggleButton();
    northTileBtn = new javax.swing.JToggleButton();
    selectSouthTileBtn = new javax.swing.JToggleButton();
    drawCenterBtn = new javax.swing.JToggleButton();
    activateEastSensorBtn = new javax.swing.JToggleButton();
    dotGridCanvas = new jcs.ui.layout.tiles.ui.DotGridCanvas();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout1.setAlignOnBaseline(true);
    toolbarPanel.setLayout(flowLayout1);

    toolBar.setRollover(true);

    eastTileBtn.setText("East");
    eastTileBtn.setFocusable(false);
    eastTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    eastTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    eastTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        eastTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(eastTileBtn);

    southTileBtn.setText("South");
    southTileBtn.setFocusable(false);
    southTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    southTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    southTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        southTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(southTileBtn);

    westTileBtn.setText("West");
    westTileBtn.setFocusable(false);
    westTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    westTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    westTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        westTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(westTileBtn);

    northTileBtn.setText("North");
    northTileBtn.setFocusable(false);
    northTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    northTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    northTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        northTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(northTileBtn);

    selectSouthTileBtn.setText("Select Tile");
    selectSouthTileBtn.setFocusable(false);
    selectSouthTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    selectSouthTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    selectSouthTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectSouthTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(selectSouthTileBtn);

    drawCenterBtn.setText("show Center");
    drawCenterBtn.setFocusable(false);
    drawCenterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    drawCenterBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    drawCenterBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        drawCenterBtnActionPerformed(evt);
      }
    });
    toolBar.add(drawCenterBtn);

    activateEastSensorBtn.setText("Active");
    activateEastSensorBtn.setFocusable(false);
    activateEastSensorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    activateEastSensorBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    activateEastSensorBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        activateEastSensorBtnActionPerformed(evt);
      }
    });
    toolBar.add(activateEastSensorBtn);

    toolbarPanel.add(toolBar);

    getContentPane().add(toolbarPanel, java.awt.BorderLayout.NORTH);

    dotGridCanvas.setPreferredSize(new java.awt.Dimension(360, 120));
    getContentPane().add(dotGridCanvas, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void northTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northTileBtnActionPerformed
    Logger.trace(sensorNorth.getId() + "...");
    sensorNorth.setShowRoute(this.northTileBtn.isSelected());
  }//GEN-LAST:event_northTileBtnActionPerformed

  private void eastTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastTileBtnActionPerformed
    sensorEast.setShowRoute(this.eastTileBtn.isSelected());
  }//GEN-LAST:event_eastTileBtnActionPerformed

  private void westTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westTileBtnActionPerformed
    sensorWest.setShowRoute(this.westTileBtn.isSelected());
  }//GEN-LAST:event_westTileBtnActionPerformed

  private void southTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southTileBtnActionPerformed
    sensorSouth.setShowRoute(this.southTileBtn.isSelected());
  }//GEN-LAST:event_southTileBtnActionPerformed

  private void selectSouthTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSouthTileBtnActionPerformed
    sensorSouth.setSelected(this.selectSouthTileBtn.isSelected());
  }//GEN-LAST:event_selectSouthTileBtnActionPerformed

  private void drawCenterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawCenterBtnActionPerformed
    sensorNorth.setDrawCenterPoint(this.drawCenterBtn.isSelected());
  }//GEN-LAST:event_drawCenterBtnActionPerformed

  private void activateEastSensorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateEastSensorBtnActionPerformed
    sensorEast.setActive(this.activateEastSensorBtn.isSelected());
  }//GEN-LAST:event_activateEastSensorBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
      SensorTileTester.setDefaultLookAndFeelDecorated(true);

    } catch (ClassNotFoundException
            | InstantiationException
            | IllegalAccessException
            | UnsupportedLookAndFeelException ex) {
      Logger.error(ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      SensorTileTester app = new SensorTileTester("Sensor Tile Tester");
      app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
      app.setLocation(dim.width / 2 - app.getSize().width / 2, dim.height / 2 - app.getSize().height / 2);
      app.pack();
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton activateEastSensorBtn;
  private jcs.ui.layout.tiles.ui.DotGridCanvas dotGridCanvas;
  private javax.swing.JToggleButton drawCenterBtn;
  private javax.swing.JToggleButton eastTileBtn;
  private javax.swing.JToggleButton northTileBtn;
  private javax.swing.JToggleButton selectSouthTileBtn;
  private javax.swing.JToggleButton southTileBtn;
  private javax.swing.JToolBar toolBar;
  private javax.swing.JPanel toolbarPanel;
  private javax.swing.JToggleButton westTileBtn;
  // End of variables declaration//GEN-END:variables
}
