/*
 * Copyright 2026 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.layout.tiles.ui;

import java.awt.Color;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jcs.entities.AccessoryBean;
import jcs.entities.TileBean;
import jcs.entities.TileBean.Orientation;
import jcs.entities.TileBean.TileType;
import jcs.ui.layout.tiles.Tile;
import jcs.ui.layout.tiles.TileCache;
import org.tinylog.Logger;

/**
 * UI for testing the Tile drawings
 *
 * @author fransjacobs
 */
public class UnscaledTileTester extends JFrame {

  private Tile tile;

  public UnscaledTileTester() {
    initComponents();

    this.orientationCB.setModel(createOrientationComboBoxModel());
    this.tileCB.setModel(createTileTypeComboBoxModel());

    tile = TileCache.createTile(TileType.CROSS_SWITCH, Orientation.EAST, TileBean.Direction.RIGHT, 220, 100);

    //canvas.setExpanded(this.scaleCB.isSelected());
    //tile.setScaleImage(this.scaleCB.isSelected());
    tile.setTrackRouteColor(Color.blue);

    canvas.add(tile);
    centerSP.getViewport().revalidate();
    pack();
    setVisible(true);
  }

  private ComboBoxModel<Orientation> createOrientationComboBoxModel() {
    DefaultComboBoxModel<Orientation> orientationModel = new DefaultComboBoxModel();
    orientationModel.addElement(Orientation.EAST);
    orientationModel.addElement(Orientation.SOUTH);
    orientationModel.addElement(Orientation.WEST);
    orientationModel.addElement(Orientation.NORTH);

    orientationModel.setSelectedItem(Orientation.EAST);

    return orientationModel;
  }

  private ComboBoxModel<TileType> createTileTypeComboBoxModel() {
    DefaultComboBoxModel<TileType> tileTypeModel = new DefaultComboBoxModel();
    tileTypeModel.addElement(TileType.STRAIGHT);
    tileTypeModel.addElement(TileType.STRAIGHT_DIR);
    tileTypeModel.addElement(TileType.SENSOR);
    tileTypeModel.addElement(TileType.SIGNAL);
    tileTypeModel.addElement(TileType.CURVED);
    tileTypeModel.addElement(TileType.SWITCH);
    tileTypeModel.addElement(TileType.THREEWAY);
    tileTypeModel.addElement(TileType.CROSS_SWITCH);
    tileTypeModel.addElement(TileType.CROSS);
    tileTypeModel.addElement(TileType.CROSSING);
    tileTypeModel.addElement(TileType.END);

    tileTypeModel.setSelectedItem(TileType.CROSS_SWITCH);
    return tileTypeModel;
  }

  private void changeOrientation() {
    Orientation orientation = (Orientation) this.orientationCB.getSelectedItem();
    tile.setIncomingSide(orientation);
    
    //tile.setOrientation(orientation);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    accessoryBG = new javax.swing.ButtonGroup();
    nPanel = new javax.swing.JPanel();
    scaleCB = new javax.swing.JCheckBox();
    tileLbl = new javax.swing.JLabel();
    tileCB = new javax.swing.JComboBox<>();
    rotateButton = new javax.swing.JButton();
    orientationLabel = new javax.swing.JLabel();
    orientationCB = new javax.swing.JComboBox<>();
    showRouteCB = new javax.swing.JCheckBox();
    showCenterCB = new javax.swing.JCheckBox();
    offButton = new javax.swing.JRadioButton();
    greenButton = new javax.swing.JRadioButton();
    redButton = new javax.swing.JRadioButton();
    centerSP = new javax.swing.JScrollPane();
    canvas = new jcs.ui.layout.tiles.ui.UnscaledCanvas();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    nPanel.setPreferredSize(new java.awt.Dimension(1250, 50));

    scaleCB.setText("Expand");
    scaleCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        scaleCBActionPerformed(evt);
      }
    });
    nPanel.add(scaleCB);

    tileLbl.setText("Tile Type");
    tileLbl.setToolTipText("");
    nPanel.add(tileLbl);

    tileCB.setPreferredSize(new java.awt.Dimension(150, 22));
    tileCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tileCBActionPerformed(evt);
      }
    });
    nPanel.add(tileCB);

    rotateButton.setText("Rotate");
    rotateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rotateButtonActionPerformed(evt);
      }
    });
    nPanel.add(rotateButton);

    orientationLabel.setText("Orientation");
    nPanel.add(orientationLabel);

    orientationCB.setPreferredSize(new java.awt.Dimension(150, 22));
    orientationCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        orientationCBActionPerformed(evt);
      }
    });
    nPanel.add(orientationCB);

    showRouteCB.setText("Show Route");
    showRouteCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        showRouteCBActionPerformed(evt);
      }
    });
    nPanel.add(showRouteCB);

    showCenterCB.setText("Show Center");
    showCenterCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        showCenterCBActionPerformed(evt);
      }
    });
    nPanel.add(showCenterCB);

    accessoryBG.add(offButton);
    offButton.setText("OFF");
    offButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        offButtonActionPerformed(evt);
      }
    });
    nPanel.add(offButton);

    accessoryBG.add(greenButton);
    greenButton.setForeground(new java.awt.Color(102, 255, 102));
    greenButton.setText("Green");
    greenButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        greenButtonActionPerformed(evt);
      }
    });
    nPanel.add(greenButton);

    accessoryBG.add(redButton);
    redButton.setForeground(new java.awt.Color(255, 51, 51));
    redButton.setText("RED");
    redButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        redButtonActionPerformed(evt);
      }
    });
    nPanel.add(redButton);

    getContentPane().add(nPanel, java.awt.BorderLayout.NORTH);

    centerSP.setAutoscrolls(true);
    centerSP.setDoubleBuffered(true);
    centerSP.setMinimumSize(new java.awt.Dimension(1250, 440));
    centerSP.setPreferredSize(new java.awt.Dimension(1250, 440));
    centerSP.setViewportView(canvas);
    centerSP.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentResized(java.awt.event.ComponentEvent evt) {
        centerSPComponentResized(evt);
      }
    });
    centerSP.setViewportView(canvas);

    getContentPane().add(centerSP, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void rotateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateButtonActionPerformed
    Orientation orientation = tile.rotate();
    this.orientationCB.setSelectedItem(orientation);
    Logger.trace("\nTile is rotated to " + orientation);
  }//GEN-LAST:event_rotateButtonActionPerformed

  private void orientationCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orientationCBActionPerformed
    changeOrientation();
  }//GEN-LAST:event_orientationCBActionPerformed

  private void tileCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tileCBActionPerformed

    Tile newTile = TileCache.createTile((TileType) tileCB.getSelectedItem(), (Orientation) orientationCB.getSelectedItem(), TileBean.Direction.RIGHT, 220, 100);

    if (tile.getTileType() != newTile.getTileType()) {
      Logger.trace("Chaneg tile to " + newTile.getTileType());
      canvas.remove(tile);
      tile = newTile;
      canvas.add(tile);
      canvas.repaint();
      centerSP.getViewport().revalidate();
    }

  }//GEN-LAST:event_tileCBActionPerformed

  private void showCenterCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCenterCBActionPerformed
    tile.setDrawCenterPoint(this.showCenterCB.isSelected());
  }//GEN-LAST:event_showCenterCBActionPerformed

  private void scaleCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleCBActionPerformed
    Logger.trace("\nBlok is expanded " + this.scaleCB.isSelected());
    tile.setScaleImage(!scaleCB.isSelected());
    canvas.setExpanded(scaleCB.isSelected());

    //Shift the tile a bit to fit on the canvas
//    if(!scaleCB.isSelected()) {
//      blockTile.setCenter(new Point(620, 180));
//    } else {
//      blockTile.setCenter(new Point(620, 140));
//    }

  }//GEN-LAST:event_scaleCBActionPerformed

  private void centerSPComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_centerSPComponentResized
    //Logger.trace(evt);
    //this.centerSP.validate();
    //wordt bij init aangeroepen
  }//GEN-LAST:event_centerSPComponentResized

  private void offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offButtonActionPerformed
    if (showRouteCB.isSelected()) {
      tile.setRouteValue(AccessoryBean.AccessoryValue.OFF);
    } else {
      tile.setAccessoryValue(AccessoryBean.AccessoryValue.OFF);
    }
  }//GEN-LAST:event_offButtonActionPerformed

  private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
    if (showRouteCB.isSelected()) {
      tile.setRouteValue(AccessoryBean.AccessoryValue.GREEN);
    } else {
      tile.setAccessoryValue(AccessoryBean.AccessoryValue.GREEN);
    }
  }//GEN-LAST:event_greenButtonActionPerformed

  private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
    if (showRouteCB.isSelected()) {
      tile.setRouteValue(AccessoryBean.AccessoryValue.RED);
    } else {
      tile.setAccessoryValue(AccessoryBean.AccessoryValue.RED);
    }
  }//GEN-LAST:event_redButtonActionPerformed

  private void showRouteCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRouteCBActionPerformed

    if (this.greenButton.isSelected()) {
      tile.setRouteValue(AccessoryBean.AccessoryValue.GREEN);
    } else if (this.redButton.isSelected()) {
      tile.setRouteValue(AccessoryBean.AccessoryValue.RED);
    } else {
      tile.setRouteValue(AccessoryBean.AccessoryValue.OFF);
    }

    tile.setShowRoute(showRouteCB.isSelected());

    //tile.repaint();
  }//GEN-LAST:event_showRouteCBActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.error(ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      UnscaledTileTester app = new UnscaledTileTester();
      app.setTitle("Unscaled Tile Tester");
      app.setLocationRelativeTo(null);

      //app.pack();
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup accessoryBG;
  private jcs.ui.layout.tiles.ui.UnscaledCanvas canvas;
  private javax.swing.JScrollPane centerSP;
  private javax.swing.JRadioButton greenButton;
  private javax.swing.JPanel nPanel;
  private javax.swing.JRadioButton offButton;
  private javax.swing.JComboBox<Orientation> orientationCB;
  private javax.swing.JLabel orientationLabel;
  private javax.swing.JRadioButton redButton;
  private javax.swing.JButton rotateButton;
  private javax.swing.JCheckBox scaleCB;
  private javax.swing.JCheckBox showCenterCB;
  private javax.swing.JCheckBox showRouteCB;
  private javax.swing.JComboBox<TileType> tileCB;
  private javax.swing.JLabel tileLbl;
  // End of variables declaration//GEN-END:variables
}
