/*
 * Copyright 2024 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui;

import javax.swing.JPanel;
import jcs.ui.util.LocomotiveSelectionChangedListener;

/**
 *
 */
public class DispatcherStatusPanel extends JPanel {

  private static final long serialVersionUID = 6158244271104499799L;

  public DispatcherStatusPanel() {
    initComponents();
    //Do not show the componenents
    tabsPane.remove(tileBeanTablePanel);
  }

  public void showDispatcherTab() {
    int tabs = tabsPane.getTabCount();
    if (tabs == 1) {
      tabsPane.addTab("Locomotives", locomotiveTablePanel);
      tabsPane.addTab("Dispatcher", dispatcherTablePanel);
      tabsPane.remove(tileBeanTablePanel);
    }

    tabsPane.setSelectedIndex(1);
    dispatcherTablePanel.refresh();
  }

  public void showLocomotiveTab() {
    int tabs = tabsPane.getTabCount();
    if (tabs == 1) {
      tabsPane.addTab("Locomotives", locomotiveTablePanel);
      tabsPane.addTab("Dispatcher", dispatcherTablePanel);
      tabsPane.remove(tileBeanTablePanel);
    }

    tabsPane.setSelectedIndex(0);
  }

  public void showComponentsTab() {
    tabsPane.remove(locomotiveTablePanel);
    tabsPane.remove(dispatcherTablePanel);

    tabsPane.addTab("Components", tileBeanTablePanel);
    tabsPane.setSelectedIndex(0);
  }

  public void refresh() {
    locomotiveTablePanel.refresh();
  }

  public void addLocomotiveSelectionChangeListener(LocomotiveSelectionChangedListener listener) {
    locomotiveTablePanel.addLocomotiveSelectionChangeListener(listener);
    dispatcherTablePanel.addLocomotiveSelectionChangeListener(listener);
  }

  public void removeLocomotiveSelectionChangeListener(LocomotiveSelectionChangedListener listener) {
    locomotiveTablePanel.removeLocomotiveSelectionChangeListener(listener);
    dispatcherTablePanel.removeLocomotiveSelectionChangeListener(listener);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tabsPane = new javax.swing.JTabbedPane();
    locomotiveTablePanel = new jcs.ui.panel.LocomotiveTablePanel();
    dispatcherTablePanel = new jcs.ui.panel.DispatcherTablePanel();
    tileBeanTablePanel = new jcs.ui.panel.TileBeanTablePanel();

    setPreferredSize(new java.awt.Dimension(300, 450));
    setLayout(new java.awt.BorderLayout());

    tabsPane.setPreferredSize(new java.awt.Dimension(300, 440));
    tabsPane.addTab("Locomotives", locomotiveTablePanel);
    tabsPane.addTab("Dispatcher", dispatcherTablePanel);
    tabsPane.addTab("Components", tileBeanTablePanel);

    add(tabsPane, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private jcs.ui.panel.DispatcherTablePanel dispatcherTablePanel;
  private jcs.ui.panel.LocomotiveTablePanel locomotiveTablePanel;
  private javax.swing.JTabbedPane tabsPane;
  private jcs.ui.panel.TileBeanTablePanel tileBeanTablePanel;
  // End of variables declaration//GEN-END:variables

}
