/*
 * Copyright 2023 frans.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.tinylog.Logger;

/**
 *
 * @author frans
 */
public class DriversCabine extends javax.swing.JFrame {

  /**
   * Creates new form DriversCabine
   */
  public DriversCabine() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    southPanel = new javax.swing.JPanel();
    speed1Button = new javax.swing.JButton();
    speed2Button = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jToggleButton1 = new javax.swing.JToggleButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    stopButton = new javax.swing.JButton();
    centerPanel = new javax.swing.JPanel();
    gaugePanel = new javax.swing.JPanel();
    gauge1 = new jcs.ui.widgets.Gauge();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
    sliderPanel = new javax.swing.JPanel();
    jSlider1 = new javax.swing.JSlider();
    functionsPanel = new jcs.ui.widgets.FunctionsPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(450, 270));
    setPreferredSize(new java.awt.Dimension(450, 330));

    southPanel.setMinimumSize(new java.awt.Dimension(138, 50));
    southPanel.setPreferredSize(new java.awt.Dimension(200, 45));
    java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 2);
    flowLayout2.setAlignOnBaseline(true);
    southPanel.setLayout(flowLayout2);

    speed1Button.setText("I");
    speed1Button.setDoubleBuffered(true);
    speed1Button.setMargin(new java.awt.Insets(2, 2, 2, 2));
    speed1Button.setPreferredSize(new java.awt.Dimension(30, 30));
    southPanel.add(speed1Button);

    speed2Button.setText("II");
    speed2Button.setMargin(new java.awt.Insets(2, 2, 2, 2));
    speed2Button.setPreferredSize(new java.awt.Dimension(30, 30));
    southPanel.add(speed2Button);

    jButton1.setText("III");
    jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
    southPanel.add(jButton1);

    jToggleButton1.setText("<");
    jToggleButton1.setPreferredSize(new java.awt.Dimension(30, 30));
    southPanel.add(jToggleButton1);

    jToggleButton2.setText(">");
    jToggleButton2.setPreferredSize(new java.awt.Dimension(30, 30));
    southPanel.add(jToggleButton2);

    stopButton.setText("Stop");
    stopButton.setPreferredSize(new java.awt.Dimension(75, 30));
    southPanel.add(stopButton);

    getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

    centerPanel.setMinimumSize(new java.awt.Dimension(440, 240));
    centerPanel.setPreferredSize(new java.awt.Dimension(440, 240));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5);
    flowLayout1.setAlignOnBaseline(true);
    centerPanel.setLayout(flowLayout1);

    gaugePanel.setMinimumSize(new java.awt.Dimension(200, 235));
    gaugePanel.setPreferredSize(new java.awt.Dimension(200, 235));
    gaugePanel.setLayout(new jcs.ui.swing.layout.VerticalFlowLayout());
    gaugePanel.add(gauge1);
    gaugePanel.add(filler1);

    centerPanel.add(gaugePanel);

    sliderPanel.setMinimumSize(new java.awt.Dimension(40, 235));
    sliderPanel.setPreferredSize(new java.awt.Dimension(40, 235));
    sliderPanel.setLayout(new javax.swing.BoxLayout(sliderPanel, javax.swing.BoxLayout.LINE_AXIS));

    jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
    jSlider1.setValue(0);
    jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jSlider1.setDoubleBuffered(true);
    jSlider1.setPreferredSize(new java.awt.Dimension(175, 25));
    sliderPanel.add(jSlider1);

    centerPanel.add(sliderPanel);
    centerPanel.add(functionsPanel);

    getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
   try {
      String plaf = System.getProperty("jcs.plaf", "com.formdev.flatlaf.FlatLightLaf");
      if (plaf != null) {
        UIManager.setLookAndFeel(plaf);
      } else {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.error(ex);
    }
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new DriversCabine().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel centerPanel;
  private javax.swing.Box.Filler filler1;
  private jcs.ui.widgets.FunctionsPanel functionsPanel;
  private jcs.ui.widgets.Gauge gauge1;
  private javax.swing.JPanel gaugePanel;
  private javax.swing.JButton jButton1;
  private javax.swing.JSlider jSlider1;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToggleButton jToggleButton2;
  private javax.swing.JPanel sliderPanel;
  private javax.swing.JPanel southPanel;
  private javax.swing.JButton speed1Button;
  private javax.swing.JButton speed2Button;
  private javax.swing.JButton stopButton;
  // End of variables declaration//GEN-END:variables
}
