/*
 * Copyright 2024 FJA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jcs.commandStation.events.LocomotiveDirectionEvent;
import jcs.commandStation.events.LocomotiveDirectionEventListener;
import jcs.entities.LocomotiveBean;
import jcs.persistence.PersistenceFactory;
import jcs.ui.util.ImageUtil;
import org.tinylog.Logger;

/**
 *
 * @author FJA
 */
public class DriverCabDialog extends javax.swing.JDialog implements LocomotiveDirectionEventListener {
  
  private static final long serialVersionUID = 4474469920406357799L;

  /**
   * Creates new form DrivedCabDialog
   *
   * @param parent
   * @param modal
   */
  public DriverCabDialog(JFrame parent, boolean modal) {
    this(parent, null, modal);
  }
  
  public DriverCabDialog(java.awt.Frame parent, LocomotiveBean locomotiveBean, boolean modal) {
    super(parent, modal);
    initComponents();
    initListener();
    
    if (locomotiveBean != null) {
      //Refresh settings
      LocomotiveBean locomotive = PersistenceFactory.getService().getLocomotive(locomotiveBean.getId());
      this.setTitle(locomotive.getName());
      this.driverCabPanel.setLocomotiveBean(locomotive);
      
      if (locomotive.getLocIcon() != null) {
        Image img = locomotive.getLocIcon().getImage();
        if (LocomotiveBean.Direction.BACKWARDS == locomotive.getDirection()) {
          img = ImageUtil.flipVertically(locomotive.getLocIcon().getImage());
          this.imageLabel.setIcon(new ImageIcon(img));
        } else {
          this.imageLabel.setIcon(new ImageIcon(img));
        }
        this.imageLabel.setText(null);
        this.locNameLabel.setText(locomotive.getName());
      } else {
        this.imageLabel.setText(locomotive.getName());
        this.locNameLabel.setText("");
      }
    }
    
  }
  
  private void initListener() {
    this.driverCabPanel.setDirectionListener(this);
  }
  
  @Override
  public void onDirectionChange(LocomotiveDirectionEvent directionEvent) {
    LocomotiveBean locomotive = this.driverCabPanel.getLocomotiveBean();
    
    ImageIcon imgIcon = locomotive.getLocIcon();
    if (imgIcon != null) {
      Image img = imgIcon.getImage();
      if (LocomotiveBean.Direction.BACKWARDS == locomotive.getDirection()) {
        img = ImageUtil.flipVertically(locomotive.getLocIcon().getImage());
        this.imageLabel.setIcon(new ImageIcon(img));
      } else {
        this.imageLabel.setIcon(new ImageIcon(img));
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    driverCabPanel = new jcs.ui.DriverCabPanel();
    northPanel = new javax.swing.JPanel();
    imageLabel = new javax.swing.JLabel();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
    locNameLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(500, 380));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
    });
    getContentPane().add(driverCabPanel, java.awt.BorderLayout.CENTER);

    northPanel.setPreferredSize(new java.awt.Dimension(300, 50));
    northPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    imageLabel.setText("image");
    imageLabel.setPreferredSize(new java.awt.Dimension(120, 40));
    northPanel.add(imageLabel);
    northPanel.add(filler1);

    locNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    locNameLabel.setText("name");
    northPanel.add(locNameLabel);

    getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    Logger.trace("Closing " + this.locNameLabel.getText());
    this.driverCabPanel.setLocomotiveBean(null);
  }//GEN-LAST:event_formWindowClosed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      String plaf = System.getProperty("jcs.plaf", "com.formdev.flatlaf.FlatLightLaf");
      if (plaf != null) {
        UIManager.setLookAndFeel(plaf);
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.error(ex);
    }
    
    LocomotiveBean loc = PersistenceFactory.getService().getLocomotive(7L);

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(() -> {
      DriverCabDialog dialog = new DriverCabDialog(new javax.swing.JFrame(), loc, true);
      dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      dialog.setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private jcs.ui.DriverCabPanel driverCabPanel;
  private javax.swing.Box.Filler filler1;
  private javax.swing.JLabel imageLabel;
  private javax.swing.JLabel locNameLabel;
  private javax.swing.JPanel northPanel;
  // End of variables declaration//GEN-END:variables
}
