/*
 * Copyright 2024 FJA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import jcs.entities.LocomotiveBean;
import jcs.persistence.PersistenceFactory;

/**
 *
 * @author FJA
 */
public class DriverCabDialog extends javax.swing.JDialog {

  /**
   * Creates new form DrivedCabDialog
   *
   * @param parent
   * @param modal
   */
  public DriverCabDialog(JFrame parent, boolean modal) {
    this(parent, null, modal);
  }

  public DriverCabDialog(java.awt.Frame parent, LocomotiveBean locomotiveBean, boolean modal) {
    super(parent, modal);
    initComponents();

    //Refresh settings
    LocomotiveBean locomotive = PersistenceFactory.getService().getLocomotive(locomotiveBean.getId());

    this.driverCabPanel.setLocomotiveBean(locomotive);
    if (locomotive != null) {

      if (locomotive.getLocIcon() != null) {
        this.imageLabel.setIcon(new ImageIcon(locomotive.getLocIcon()));
        this.imageLabel.setText(null);
        this.locNameLabel.setText(locomotive.getName());
      } else {
        this.imageLabel.setText(locomotive.getName());
        this.locNameLabel.setText("");
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    driverCabPanel = new jcs.ui.DriverCabPanel();
    northPanel = new javax.swing.JPanel();
    imageLabel = new javax.swing.JLabel();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
    locNameLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(500, 380));
    getContentPane().add(driverCabPanel, java.awt.BorderLayout.CENTER);

    northPanel.setPreferredSize(new java.awt.Dimension(300, 50));
    northPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    imageLabel.setText("image");
    imageLabel.setPreferredSize(new java.awt.Dimension(120, 40));
    northPanel.add(imageLabel);
    northPanel.add(filler1);

    locNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    locNameLabel.setText("name");
    northPanel.add(locNameLabel);

    getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DriverCabDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DriverCabDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DriverCabDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DriverCabDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        DriverCabDialog dialog = new DriverCabDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private jcs.ui.DriverCabPanel driverCabPanel;
  private javax.swing.Box.Filler filler1;
  private javax.swing.JLabel imageLabel;
  private javax.swing.JLabel locNameLabel;
  private javax.swing.JPanel northPanel;
  // End of variables declaration//GEN-END:variables
}
