/*
 * Copyright 2023 frans.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jcs.ui.widgets.KeyboardPanelWide;
import jcs.ui.widgets.MessagesPanel;
import jcs.ui.widgets.SensorPanelWide;
import org.tinylog.Logger;

/**
 *
 * @author frans
 */
public class KeyboardSensorPanel extends JPanel {

  private static final long serialVersionUID = 3984321012712562834L;

  /**
   * Creates new form FeedbackMonitorPanel
   */
  public KeyboardSensorPanel() {
    initComponents();
    //For now this feedback screen is disabled
    if ("true".equals(System.getProperty("show.sensor.panels", "false"))) {
      //widgetPanel.remove(feedbackPanel);
      //feedbackPanel.setVisible(false);
      //widgetPanel.setVisible(false);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    accessoryKeyboardPanel = new KeyboardPanelWide();
    messagesPanel = new MessagesPanel();
    sensorModulePanel = new SensorPanelWide();

    setName("Form"); // NOI18N
    setPreferredSize(new Dimension(1010, 850));
    addComponentListener(new ComponentAdapter() {
      public void componentHidden(ComponentEvent evt) {
        formComponentHidden(evt);
      }
      public void componentShown(ComponentEvent evt) {
        formComponentShown(evt);
      }
    });
    setLayout(new BorderLayout());

    accessoryKeyboardPanel.setBorder(BorderFactory.createTitledBorder("Keyboard"));
    accessoryKeyboardPanel.setName("accessoryKeyboardPanel"); // NOI18N
    add(accessoryKeyboardPanel, BorderLayout.NORTH);

    messagesPanel.setBorder(BorderFactory.createTitledBorder("Log"));
    messagesPanel.setName("messagesPanel"); // NOI18N
    add(messagesPanel, BorderLayout.CENTER);

    sensorModulePanel.setBorder(BorderFactory.createTitledBorder("Sensors"));
    sensorModulePanel.setName("sensorModulePanel"); // NOI18N
    sensorModulePanel.setPreferredSize(new Dimension(895, 150));
    add(sensorModulePanel, BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      //registerListeners();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
      //removeListeners();
    }//GEN-LAST:event_formComponentHidden

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private KeyboardPanelWide accessoryKeyboardPanel;
  private MessagesPanel messagesPanel;
  private SensorPanelWide sensorModulePanel;
  // End of variables declaration//GEN-END:variables

  //Testing
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.error("Can't set the LookAndFeel: " + ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
      KeyboardSensorPanel testPanel = new KeyboardSensorPanel();
      JFrame testFrame = new JFrame("ControllerPanel Tester");
      //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/media/jcs-train-64.png")));
      URL iconUrl = KeyboardSensorPanel.class.getResource("/media/jcs-train-2-512.png");
      if (iconUrl != null) {
        testFrame.setIconImage(new ImageIcon(iconUrl).getImage());
      }

      JFrame.setDefaultLookAndFeelDecorated(true);
      testFrame.add(testPanel);

      testFrame.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      testFrame.pack();
      testFrame.setLocationRelativeTo(null);
      testFrame.setVisible(true);
    });
  }
}
