/*
 * Copyright (C) 2019 frans.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package lan.wervel.jcs.ui.options;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import lan.wervel.jcs.entities.FeedbackModule;
import lan.wervel.jcs.trackservice.TrackServiceFactory;
import lan.wervel.jcs.ui.options.table.FeedbackModuleTableModel;
import org.pmw.tinylog.Configurator;
import org.pmw.tinylog.Logger;

/**
 *
 * @author frans
 */
@SuppressWarnings("deprecation")
public class FeedbackModulePanel extends JPanel {

  private final FeedbackModuleTableModel feedbackModulelTableModel;

  public FeedbackModulePanel() {
    feedbackModulelTableModel = new FeedbackModuleTableModel();

    initComponents();
    alignFeedbackModuleTable();

  }

  private void alignFeedbackModuleTable() {
    this.feedbackModuleTable.getColumnModel().getColumn(0).setPreferredWidth(50);
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
    this.feedbackModuleTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    this.feedbackModuleTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    directionBG = new ButtonGroup();
    feedbackModule = new FeedbackModule();
    topPanel = new JPanel();
    refreshBtn = new JButton();
    newBtn = new JButton();
    centerPanel = new JPanel();
    centerSplitPane = new JSplitPane();
    feedbackModuleTableScrollPane = new JScrollPane();
    feedbackModuleTable = new JTable();
    feedbackModuleDetailPanel = new JPanel();
    row1Panel = new JPanel();
    addressLbl = new JLabel();
    addressSpinner = new JSpinner();
    idLbl = new JLabel();
    row2Panel = new JPanel();
    portTypeLbl = new JLabel();
    portSpinner = new JSpinner();
    row3Panel = new JPanel();
    nameLbl = new JLabel();
    nameTF = new JTextField();
    row4Panel = new JPanel();
    descriptionLbl = new JLabel();
    decriptionTF = new JTextField();
    row5Panel = new JPanel();
    catalogeNrLbl = new JLabel();
    catalogNrTF = new JTextField();
    row6Panel = new JPanel();
    row7Panel = new JPanel();
    row8Panel = new JPanel();
    row9Panel = new JPanel();
    filler2 = new Box.Filler(new Dimension(0, 50), new Dimension(0, 250), new Dimension(32767, 300));
    buttonPanel = new JPanel();
    deleteBtn = new JButton();
    filler1 = new Box.Filler(new Dimension(50, 0), new Dimension(200, 0), new Dimension(150, 32767));
    saveBtn = new JButton();
    bottomPanel = new JPanel();

    setMinimumSize(new Dimension(1000, 600));
    setPreferredSize(new Dimension(1000, 600));
    setLayout(new BorderLayout());

    topPanel.setMinimumSize(new Dimension(1000, 45));
    topPanel.setPreferredSize(new Dimension(1000, 50));
    topPanel.setRequestFocusEnabled(false);
    FlowLayout flowLayout1 = new FlowLayout(FlowLayout.RIGHT);
    flowLayout1.setAlignOnBaseline(true);
    topPanel.setLayout(flowLayout1);

    refreshBtn.setIcon(new ImageIcon(getClass().getResource("/media/refresh-24.png"))); // NOI18N
    refreshBtn.setText("Refresh");
    refreshBtn.setMargin(new Insets(2, 2, 2, 2));
    refreshBtn.setMaximumSize(new Dimension(120, 36));
    refreshBtn.setMinimumSize(new Dimension(120, 36));
    refreshBtn.setPreferredSize(new Dimension(120, 36));
    refreshBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        refreshBtnActionPerformed(evt);
      }
    });
    topPanel.add(refreshBtn);

    newBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24.png"))); // NOI18N
    newBtn.setText("New");
    newBtn.setToolTipText("Create new Locomotive");
    newBtn.setMaximumSize(new Dimension(120, 36));
    newBtn.setMinimumSize(new Dimension(120, 36));
    newBtn.setPreferredSize(new Dimension(120, 36));
    newBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        newBtnActionPerformed(evt);
      }
    });
    topPanel.add(newBtn);

    add(topPanel, BorderLayout.NORTH);

    centerPanel.setMinimumSize(new Dimension(100, 500));
    centerPanel.setPreferredSize(new Dimension(1000, 500));
    centerPanel.setLayout(new BorderLayout());

    centerSplitPane.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
    centerSplitPane.setDividerLocation(500);
    centerSplitPane.setDoubleBuffered(true);
    centerSplitPane.setMinimumSize(new Dimension(420, 542));
    centerSplitPane.setPreferredSize(new Dimension(897, 542));

    feedbackModuleTableScrollPane.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
    feedbackModuleTableScrollPane.setMinimumSize(new Dimension(500, 500));
    feedbackModuleTableScrollPane.setPreferredSize(new Dimension(500, 500));

    feedbackModuleTable.setModel(feedbackModulelTableModel);
    feedbackModuleTable.setDoubleBuffered(true);
    feedbackModuleTable.setGridColor(new Color(204, 204, 204));
    feedbackModuleTable.setPreferredSize(new Dimension(480, 470));
    feedbackModuleTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    feedbackModuleTable.getTableHeader().setReorderingAllowed(false);
    feedbackModuleTable.addMouseListener(new MouseAdapter() {
      public void mouseClicked(MouseEvent evt) {
        feedbackModuleTableMouseClicked(evt);
      }
    });
    feedbackModuleTableScrollPane.setViewportView(feedbackModuleTable);

    centerSplitPane.setLeftComponent(feedbackModuleTableScrollPane);

    feedbackModuleDetailPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1), "Edit Signal"));
    feedbackModuleDetailPanel.setMinimumSize(new Dimension(500, 490));
    feedbackModuleDetailPanel.setPreferredSize(new Dimension(500, 490));
    feedbackModuleDetailPanel.setLayout(new BoxLayout(feedbackModuleDetailPanel, BoxLayout.Y_AXIS));

    row1Panel.setMinimumSize(new Dimension(380, 30));
    row1Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout6 = new FlowLayout(FlowLayout.LEFT);
    flowLayout6.setAlignOnBaseline(true);
    row1Panel.setLayout(flowLayout6);

    addressLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    addressLbl.setLabelFor(addressSpinner);
    addressLbl.setText("Address");
    addressLbl.setPreferredSize(new Dimension(120, 16));
    row1Panel.add(addressLbl);

    addressSpinner.setModel(new SpinnerNumberModel(0, 0, 32, 1));
    addressSpinner.setDoubleBuffered(true);
    addressSpinner.setEditor(new JSpinner.NumberEditor(addressSpinner, ""));
    addressSpinner.setMinimumSize(new Dimension(50, 26));
    addressSpinner.setName(""); // NOI18N
    addressSpinner.setNextFocusableComponent(nameTF);
    addressSpinner.setPreferredSize(new Dimension(60, 26));
    row1Panel.add(addressSpinner);

    idLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    idLbl.setText("ID: ");
    idLbl.setPreferredSize(new Dimension(220, 16));
    row1Panel.add(idLbl);

    feedbackModuleDetailPanel.add(row1Panel);

    row2Panel.setMinimumSize(new Dimension(380, 30));
    row2Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout7 = new FlowLayout(FlowLayout.LEFT);
    flowLayout7.setAlignOnBaseline(true);
    row2Panel.setLayout(flowLayout7);

    portTypeLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    portTypeLbl.setText("Ports");
    portTypeLbl.setMaximumSize(new Dimension(120, 16));
    portTypeLbl.setPreferredSize(new Dimension(120, 16));
    row2Panel.add(portTypeLbl);

    portSpinner.setModel(new SpinnerNumberModel(0, 0, 16, 1));
    portSpinner.setDoubleBuffered(true);
    portSpinner.setEditor(new JSpinner.NumberEditor(portSpinner, ""));
    portSpinner.setMinimumSize(new Dimension(50, 26));
    portSpinner.setName(""); // NOI18N
    portSpinner.setNextFocusableComponent(nameTF);
    portSpinner.setPreferredSize(new Dimension(60, 26));
    row2Panel.add(portSpinner);

    feedbackModuleDetailPanel.add(row2Panel);

    row3Panel.setMinimumSize(new Dimension(380, 30));
    row3Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout8 = new FlowLayout(FlowLayout.LEFT);
    flowLayout8.setAlignOnBaseline(true);
    row3Panel.setLayout(flowLayout8);

    nameLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    nameLbl.setLabelFor(nameTF);
    nameLbl.setText("Name");
    nameLbl.setPreferredSize(new Dimension(120, 16));
    row3Panel.add(nameLbl);

    nameTF.setMinimumSize(new Dimension(120, 26));
    nameTF.setPreferredSize(new Dimension(120, 26));
    row3Panel.add(nameTF);

    feedbackModuleDetailPanel.add(row3Panel);

    row4Panel.setMinimumSize(new Dimension(380, 30));
    row4Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout9 = new FlowLayout(FlowLayout.LEFT);
    flowLayout9.setAlignOnBaseline(true);
    row4Panel.setLayout(flowLayout9);

    descriptionLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    descriptionLbl.setText("Description");
    descriptionLbl.setPreferredSize(new Dimension(120, 16));
    row4Panel.add(descriptionLbl);

    decriptionTF.setPreferredSize(new Dimension(120, 26));
    decriptionTF.setSize(new Dimension(120, 26));
    row4Panel.add(decriptionTF);

    feedbackModuleDetailPanel.add(row4Panel);

    row5Panel.setMinimumSize(new Dimension(380, 30));
    row5Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout10 = new FlowLayout(FlowLayout.LEFT);
    flowLayout10.setAlignOnBaseline(true);
    row5Panel.setLayout(flowLayout10);

    catalogeNrLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    catalogeNrLbl.setLabelFor(catalogNrTF);
    catalogeNrLbl.setText("Catalog Number");
    catalogeNrLbl.setPreferredSize(new Dimension(120, 16));
    row5Panel.add(catalogeNrLbl);

    catalogNrTF.setMinimumSize(new Dimension(120, 26));
    catalogNrTF.setPreferredSize(new Dimension(120, 26));
    row5Panel.add(catalogNrTF);

    feedbackModuleDetailPanel.add(row5Panel);

    row6Panel.setMinimumSize(new Dimension(380, 30));
    row6Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout5 = new FlowLayout(FlowLayout.LEFT);
    flowLayout5.setAlignOnBaseline(true);
    row6Panel.setLayout(flowLayout5);
    feedbackModuleDetailPanel.add(row6Panel);

    row7Panel.setMinimumSize(new Dimension(380, 30));
    row7Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout4 = new FlowLayout(FlowLayout.LEFT);
    flowLayout4.setAlignOnBaseline(true);
    row7Panel.setLayout(flowLayout4);
    feedbackModuleDetailPanel.add(row7Panel);

    row8Panel.setMinimumSize(new Dimension(380, 30));
    row8Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout3 = new FlowLayout(FlowLayout.LEFT);
    flowLayout3.setAlignOnBaseline(true);
    row8Panel.setLayout(flowLayout3);
    feedbackModuleDetailPanel.add(row8Panel);

    row9Panel.setMinimumSize(new Dimension(380, 30));
    row9Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout2 = new FlowLayout(FlowLayout.LEFT);
    flowLayout2.setAlignOnBaseline(true);
    row9Panel.setLayout(flowLayout2);
    feedbackModuleDetailPanel.add(row9Panel);
    feedbackModuleDetailPanel.add(filler2);

    buttonPanel.setMinimumSize(new Dimension(380, 40));
    buttonPanel.setPreferredSize(new Dimension(380, 40));
    FlowLayout flowLayout11 = new FlowLayout();
    flowLayout11.setAlignOnBaseline(true);
    buttonPanel.setLayout(flowLayout11);

    deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24.png"))); // NOI18N
    deleteBtn.setText("Delete");
    deleteBtn.setMaximumSize(new Dimension(100, 36));
    deleteBtn.setMinimumSize(new Dimension(100, 36));
    deleteBtn.setPreferredSize(new Dimension(100, 36));
    deleteBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        deleteBtnActionPerformed(evt);
      }
    });
    buttonPanel.add(deleteBtn);
    buttonPanel.add(filler1);

    saveBtn.setIcon(new ImageIcon(getClass().getResource("/media/save-24.png"))); // NOI18N
    saveBtn.setText("Save");
    saveBtn.setMaximumSize(new Dimension(100, 36));
    saveBtn.setMinimumSize(new Dimension(100, 36));
    saveBtn.setPreferredSize(new Dimension(100, 36));
    saveBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        saveBtnActionPerformed(evt);
      }
    });
    buttonPanel.add(saveBtn);

    feedbackModuleDetailPanel.add(buttonPanel);

    centerSplitPane.setRightComponent(feedbackModuleDetailPanel);

    centerPanel.add(centerSplitPane, BorderLayout.CENTER);

    add(centerPanel, BorderLayout.CENTER);

    bottomPanel.setPreferredSize(new Dimension(1000, 50));
    bottomPanel.setRequestFocusEnabled(false);

    GroupLayout bottomPanelLayout = new GroupLayout(bottomPanel);
    bottomPanel.setLayout(bottomPanelLayout);
    bottomPanelLayout.setHorizontalGroup(bottomPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 1000, Short.MAX_VALUE)
    );
    bottomPanelLayout.setVerticalGroup(bottomPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 50, Short.MAX_VALUE)
    );

    add(bottomPanel, BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents


  private void newBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
    this.feedbackModulelTableModel.refresh();
    alignFeedbackModuleTable();
    Logger.debug("Create new FeedbackModule...");

    this.feedbackModule = new FeedbackModule(0, null, 16);
    this.feedbackModule.setResponse(new Integer[]{0, 0});

    Integer pa = TrackServiceFactory.getTrackService().getFeedbackModules().size() + 1;
    this.feedbackModule.setAddress(pa);

    this.feedbackModule.setName("S88_" + pa);

    this.setComponentValues(feedbackModule);
    Logger.debug("Create new FeedbackModule..." + this.feedbackModule);
  }//GEN-LAST:event_newBtnActionPerformed

  private void feedbackModuleTableMouseClicked(MouseEvent evt) {//GEN-FIRST:event_feedbackModuleTableMouseClicked
    JTable source = (JTable) evt.getSource();
    int row = source.rowAtPoint(evt.getPoint());

    FeedbackModule f = this.feedbackModulelTableModel.getControllableDeviceAt(row);
    if (f != null) {
      Logger.debug("Selected row: " + row + ", Module Address: " + f.getAddress());
      this.feedbackModule = TrackServiceFactory.getTrackService().getFeedbackModule(f.getAddress());
      this.setComponentValues(this.feedbackModule);
    }
  }//GEN-LAST:event_feedbackModuleTableMouseClicked

  private void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    this.feedbackModule = this.setFeedbackModuleValues();
    Logger.debug("Save the Signal: " + this.feedbackModule);

    FeedbackModule f = TrackServiceFactory.getTrackService().getFeedbackModule(feedbackModule.getAddress());
    if (f != null) {
      this.feedbackModule.setId(f.getId());
      this.feedbackModule.setResponse(f.getResponse());
      Logger.debug("Found Feedback with id " + f.getId());
    }

    this.feedbackModule = TrackServiceFactory.getTrackService().persist(this.feedbackModule);
    this.setComponentValues(feedbackModule);
    this.feedbackModulelTableModel.refresh();
    alignFeedbackModuleTable();
  }//GEN-LAST:event_saveBtnActionPerformed

  private void deleteBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
    Logger.debug("Delete Signal: " + this.feedbackModule);
    TrackServiceFactory.getTrackService().remove(feedbackModule);
    this.feedbackModulelTableModel.refresh();
    this.feedbackModule = null;
    this.setComponentValues(feedbackModule);
    alignFeedbackModuleTable();
  }//GEN-LAST:event_deleteBtnActionPerformed

  public void refresh() {
    this.feedbackModulelTableModel.refresh();
    alignFeedbackModuleTable();
  }

  private void refreshBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
    refresh();
  }//GEN-LAST:event_refreshBtnActionPerformed

  //Create Signal from fields  
  protected FeedbackModule setFeedbackModuleValues() {
    Integer address = (Integer) this.addressSpinner.getValue();
    String name = this.nameTF.getText();

    String description = this.decriptionTF.getText();

    String catalogNumber = this.catalogNrTF.getText();

    Integer ports = (Integer) this.portSpinner.getValue();

    FeedbackModule f = new FeedbackModule(address, catalogNumber, ports);
    f.setName(name);
    f.setDescription(description);

    return f;
  }

  //Set fields from feedbackModule
  protected void setComponentValues(FeedbackModule feedbackModule) {
    if (feedbackModule != null) {
      this.addressSpinner.setValue(feedbackModule.getAddress());
      this.nameTF.setText(feedbackModule.getName());

      this.catalogNrTF.setText(feedbackModule.getCatalogNumber());
      this.decriptionTF.setText(feedbackModule.getDescription());
      this.portSpinner.setValue(feedbackModule.getPorts());
      this.idLbl.setText(feedbackModule.getId() + "");
    } else {
      this.addressSpinner.setValue(0);
      this.nameTF.setText("");

      this.catalogNrTF.setText("");
      this.decriptionTF.setText("");
      this.portSpinner.setValue(16);
      this.idLbl.setText("--");

    }
  }

  public static void main(String args[]) {
    Configurator.defaultConfig().level(org.pmw.tinylog.Level.DEBUG).activate();

    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      //UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");

    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.warn("Can't set the LookAndFeel: " + ex);
    }
    java.awt.EventQueue.invokeLater(() -> {

      FeedbackModulePanel testPanel = new FeedbackModulePanel();
      JFrame testFrame = new JFrame();
      JDialog testDialog = new JDialog(testFrame, true);

      testDialog.add(testPanel);
      testDialog.setIconImage(Toolkit.getDefaultToolkit().getImage(testDialog.getClass().getResource("/media/jcs-train-64.png")));

      testDialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      testDialog.pack();
      testDialog.setLocationRelativeTo(null);

      testDialog.setVisible(true);
    });
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel addressLbl;
  private JSpinner addressSpinner;
  private JPanel bottomPanel;
  private JPanel buttonPanel;
  private JTextField catalogNrTF;
  private JLabel catalogeNrLbl;
  private JPanel centerPanel;
  private JSplitPane centerSplitPane;
  private JTextField decriptionTF;
  private JButton deleteBtn;
  private JLabel descriptionLbl;
  private ButtonGroup directionBG;
  private FeedbackModule feedbackModule;
  private JPanel feedbackModuleDetailPanel;
  private JTable feedbackModuleTable;
  private JScrollPane feedbackModuleTableScrollPane;
  private Box.Filler filler1;
  private Box.Filler filler2;
  private JLabel idLbl;
  private JLabel nameLbl;
  private JTextField nameTF;
  private JButton newBtn;
  private JSpinner portSpinner;
  private JLabel portTypeLbl;
  private JButton refreshBtn;
  private JPanel row1Panel;
  private JPanel row2Panel;
  private JPanel row3Panel;
  private JPanel row4Panel;
  private JPanel row5Panel;
  private JPanel row6Panel;
  private JPanel row7Panel;
  private JPanel row8Panel;
  private JPanel row9Panel;
  private JButton saveBtn;
  private JPanel topPanel;
  // End of variables declaration//GEN-END:variables
}
