/*
 * Copyright 2025 frans.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.settings;

/**
 *
 * @author frans
 */
public class RoutesPanel extends javax.swing.JPanel {

  /**
   * Creates new form RoutesPanel
   */
  public RoutesPanel() {
    initComponents();
    
    postInit();
  }

  
  private void postInit() {
    this.routeBeanTableModel.refresh();
  }
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    routeBeanTableModel = new jcs.ui.table.model.RouteBeanTableModel();
    mainCenterPanel = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    topPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    westPanel = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();

    setPreferredSize(new java.awt.Dimension(1000, 600));
    setLayout(new java.awt.BorderLayout());

    mainCenterPanel.setLayout(new java.awt.BorderLayout());

    jTable1.setModel(routeBeanTableModel);
    jScrollPane1.setViewportView(jTable1);

    mainCenterPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    add(mainCenterPanel, java.awt.BorderLayout.CENTER);

    topPanel.setPreferredSize(new java.awt.Dimension(1000, 50));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout1.setAlignOnBaseline(true);
    topPanel.setLayout(flowLayout1);

    jLabel1.setText("Routes");
    topPanel.add(jLabel1);

    add(topPanel, java.awt.BorderLayout.PAGE_START);

    westPanel.setPreferredSize(new java.awt.Dimension(50, 573));
    add(westPanel, java.awt.BorderLayout.WEST);
    add(jPanel1, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JPanel mainCenterPanel;
  private jcs.ui.table.model.RouteBeanTableModel routeBeanTableModel;
  private javax.swing.JPanel topPanel;
  private javax.swing.JPanel westPanel;
  // End of variables declaration//GEN-END:variables
}
