/*
 * Copyright 2023 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.settings;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.tinylog.Logger;

/**
 * Settings Dialog combines the Settings Dialogs into one Dialog, so it can be shown in MacOS via the Settings Menu.
 */
public class SettingsDialog extends javax.swing.JDialog {

  private static final long serialVersionUID = 4989500714204829315L;

  /**
   * @param parent
   * @param modal
   */
  public SettingsDialog(Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    init();
  }

  private void init() {
    //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/media/jcs-train-64.png")));
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    centerPanel = new JPanel();
    dialogTP = new JTabbedPane();
    locomotivePanel = new LocomotiveSettingsPanel();
    accessoryPreferencesPanel = new AccessorySettingsPanel();
    commandStationPanel = new CommandStationPanel();
    propertiesPanel = new PropertySettingsPanel();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Settings");
    setAlwaysOnTop(true);
    setMinimumSize(new Dimension(1024, 750));
    setName("Options"); // NOI18N

    centerPanel.setMinimumSize(new Dimension(1021, 750));
    centerPanel.setName("centerPanel"); // NOI18N
    centerPanel.setLayout(new BorderLayout());

    dialogTP.setName("dialogTP"); // NOI18N
    dialogTP.addChangeListener(new ChangeListener() {
      public void stateChanged(ChangeEvent evt) {
        dialogTPStateChanged(evt);
      }
    });

    locomotivePanel.setName("locomotivePanel"); // NOI18N
    dialogTP.addTab("Locomotives", locomotivePanel);

    accessoryPreferencesPanel.setName("accessoryPreferencesPanel"); // NOI18N
    dialogTP.addTab("Accessories", accessoryPreferencesPanel);

    commandStationPanel.setName("commandStationPanel"); // NOI18N
    dialogTP.addTab("Command Stations", commandStationPanel);

    propertiesPanel.setName("propertiesPanel"); // NOI18N
    dialogTP.addTab("Properties", propertiesPanel);

    centerPanel.add(dialogTP, BorderLayout.CENTER);
    dialogTP.getAccessibleContext().setAccessibleName("Locomotives");

    getContentPane().add(centerPanel, BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void dialogTPStateChanged(ChangeEvent evt) {//GEN-FIRST:event_dialogTPStateChanged
    Component c = this.dialogTP.getSelectedComponent();

    if (c instanceof LocomotiveSettingsPanel) {
      //this.locomotivePanel.refresh();
    } else if (c instanceof AccessorySettingsPanel) {
      //this.turnoutPanel.refresh();
    } else if (c instanceof PropertySettingsPanel) {
      //this.propertiesPanel.refresh();
    }

    Logger.debug("Refreshed " + (c != null ? c.getName() : ""));
  }//GEN-LAST:event_dialogTPStateChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the FlatLightLaf look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.warn("Can't set the LookAndFeel: " + ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(() -> {
      SettingsDialog dialog = new SettingsDialog(new javax.swing.JFrame(), true);
      dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      dialog.pack();
      dialog.setLocationRelativeTo(null);
      dialog.setVisible(true);
    });
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private AccessorySettingsPanel accessoryPreferencesPanel;
  private JPanel centerPanel;
  private CommandStationPanel commandStationPanel;
  private JTabbedPane dialogTP;
  private LocomotiveSettingsPanel locomotivePanel;
  private PropertySettingsPanel propertiesPanel;
  // End of variables declaration//GEN-END:variables
}
