/*
 * Copyright 2026 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.settings;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import jcs.entities.BlockBean;
import jcs.entities.StationBean;
import jcs.persistence.PersistenceFactory;
import jcs.ui.table.model.DrivewayCommandTableModel;
import jcs.ui.widgets.Shuttle;
import org.tinylog.Logger;

/**
 * Dialog panel viewing Driveway settings.
 *
 */
public class StationSettingsPanel extends JPanel {

  private static final long serialVersionUID = 4740648662345334085L;

  private final StationBeanListModel stationBeanListModel;

  private StationBean selectedStation;

  public StationSettingsPanel() {
    stationBeanListModel = new StationBeanListModel();

    initComponents();

    initStations();
  }

  private void initStations() {
    if (PersistenceFactory.getService() != null) {
      stationBeanListModel.clear();
      List<StationBean> stations = PersistenceFactory.getService().getStations();
      stationBeanListModel.addAll(stations);
      stationList.setModel(stationBeanListModel);

      setFieldValues();
    }
  }

  private void initShuttle() {
    List<BlockBean> nonMemberBlocks = PersistenceFactory.getService().getNonStationBlocks();
    List<BlockBean> memberBlocks;
    if (selectedStation != null) {
      memberBlocks = PersistenceFactory.getService().getStationBlocks(selectedStation);
    } else {
      memberBlocks = new ArrayList();
    }
    shuttlePanel.clearSourceListModel();
    shuttlePanel.setSourceElements(nonMemberBlocks);

    shuttlePanel.clearDestinationListModel();
    shuttlePanel.addDestinationElements(memberBlocks);
  }

  private void setFieldValues() {
    if (selectedStation != null) {
      String id = selectedStation.getId();
      idLbl.setText(id);

      String name = selectedStation.getName();
      stationNameTF.setText(name);

      Integer minLocs = selectedStation.getMinLocomotives();
      if (minLocs != null) {
        minLocsSpinner.setValue(minLocs);
      }

      boolean useFifo = selectedStation.isFifo();
      useFifoCB.setSelected(useFifo);

      initShuttle();

    } else {
      idLbl.setText(null);
      stationNameTF.setText(null);
      minLocsSpinner.setValue(0);
      useFifoCB.setSelected(false);
      List<BlockBean> nonMemberBlocks = PersistenceFactory.getService().getNonStationBlocks();
      shuttlePanel.clearSourceListModel();
      shuttlePanel.setSourceElements(nonMemberBlocks);
      shuttlePanel.clearDestinationListModel();
    }
    enableFields(selectedStation != null);
  }

  private void enableFields(boolean enable) {
    stationNameTF.setEnabled(enable);
    minLocsSpinner.setEnabled(enable);
    useFifoCB.setEnabled(enable);
    saveBtn.setEnabled(enable);
    mainTP.setEnabled(enable);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings({"unchecked", "deprecation"})
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    drivewayCommandTableModel = new DrivewayCommandTableModel();
    topPanel = new JPanel();
    leftPanel = new JPanel();
    idLbl = new JLabel();
    rightPanel = new JPanel();
    newBtn = new JButton();
    deleteBtn = new JButton();
    mainTP = new JTabbedPane();
    stationPanel = new JPanel();
    row0Panel = new JPanel();
    stationNameLbl = new JLabel();
    stationNameTF = new JTextField();
    row1Panel = new JPanel();
    minLocsLbl = new JLabel();
    minLocsSpinner = new JSpinner();
    useFifoLbl = new JLabel();
    useFifoCB = new JCheckBox();
    row2Panel = new JPanel();
    row3Panel = new JPanel();
    row4Panel = new JPanel();
    row5Panel = new JPanel();
    row6Panel = new JPanel();
    row7Panel = new JPanel();
    row9Panel = new JPanel();
    buttonPanel = new JPanel();
    memberPanel = new JPanel();
    drivewayTableSP = new JScrollPane();
    shuttlePanel = new Shuttle();
    westPanel = new JPanel();
    stationsSP = new JScrollPane();
    stationList = new JList<>();
    bottomPanel = new JPanel();
    filler1 = new Box.Filler(new Dimension(100, 0), new Dimension(200, 0), new Dimension(150, 32767));
    saveBtn = new JButton();

    setMinimumSize(new Dimension(1000, 600));
    setPreferredSize(new Dimension(1000, 600));
    setLayout(new BorderLayout());

    topPanel.setMinimumSize(new Dimension(1000, 50));
    topPanel.setPreferredSize(new Dimension(1000, 50));
    topPanel.setRequestFocusEnabled(false);
    topPanel.setLayout(new GridLayout(1, 2));

    FlowLayout flowLayout11 = new FlowLayout(FlowLayout.LEFT);
    flowLayout11.setAlignOnBaseline(true);
    leftPanel.setLayout(flowLayout11);

    idLbl.setPreferredSize(new Dimension(150, 17));
    leftPanel.add(idLbl);

    topPanel.add(leftPanel);

    FlowLayout flowLayout2 = new FlowLayout(FlowLayout.RIGHT);
    flowLayout2.setAlignOnBaseline(true);
    rightPanel.setLayout(flowLayout2);

    newBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24.png"))); // NOI18N
    newBtn.setToolTipText("Create new Accessory");
    newBtn.setMaximumSize(new Dimension(40, 40));
    newBtn.setMinimumSize(new Dimension(40, 40));
    newBtn.setPreferredSize(new Dimension(40, 40));
    newBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        newBtnActionPerformed(evt);
      }
    });
    rightPanel.add(newBtn);

    deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24.png"))); // NOI18N
    deleteBtn.setMaximumSize(new Dimension(40, 40));
    deleteBtn.setMinimumSize(new Dimension(40, 40));
    deleteBtn.setPreferredSize(new Dimension(40, 40));
    deleteBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        deleteBtnActionPerformed(evt);
      }
    });
    rightPanel.add(deleteBtn);

    topPanel.add(rightPanel);

    add(topPanel, BorderLayout.NORTH);

    stationPanel.setMinimumSize(new Dimension(390, 540));
    stationPanel.setPreferredSize(new Dimension(480, 500));
    stationPanel.setLayout(new BoxLayout(stationPanel, BoxLayout.Y_AXIS));

    row0Panel.setMinimumSize(new Dimension(380, 30));
    row0Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout8 = new FlowLayout(FlowLayout.LEFT);
    flowLayout8.setAlignOnBaseline(true);
    row0Panel.setLayout(flowLayout8);

    stationNameLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    stationNameLbl.setLabelFor(stationNameTF);
    stationNameLbl.setText("Name:");
    stationNameLbl.setToolTipText("");
    stationNameLbl.setPreferredSize(new Dimension(120, 17));
    row0Panel.add(stationNameLbl);

    stationNameTF.setMinimumSize(new Dimension(200, 23));
    stationNameTF.setPreferredSize(new Dimension(200, 23));
    row0Panel.add(stationNameTF);

    stationPanel.add(row0Panel);

    row1Panel.setMinimumSize(new Dimension(380, 30));
    row1Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout1 = new FlowLayout(FlowLayout.LEFT);
    flowLayout1.setAlignOnBaseline(true);
    row1Panel.setLayout(flowLayout1);

    minLocsLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    minLocsLbl.setLabelFor(minLocsSpinner);
    minLocsLbl.setText("Min. Nr. of Loc's:");
    minLocsLbl.setToolTipText("");
    minLocsLbl.setPreferredSize(new Dimension(120, 17));
    row1Panel.add(minLocsLbl);

    minLocsSpinner.setModel(new SpinnerNumberModel(0, 0, null, 1));
    row1Panel.add(minLocsSpinner);

    useFifoLbl.setHorizontalAlignment(SwingConstants.TRAILING);
    useFifoLbl.setLabelFor(useFifoCB);
    useFifoLbl.setText("Use FIFO:");
    useFifoLbl.setToolTipText("");
    useFifoLbl.setPreferredSize(new Dimension(120, 17));
    row1Panel.add(useFifoLbl);

    useFifoCB.setSelected(true);
    row1Panel.add(useFifoCB);

    stationPanel.add(row1Panel);

    row2Panel.setMinimumSize(new Dimension(380, 30));
    row2Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout3 = new FlowLayout(FlowLayout.LEFT);
    flowLayout3.setAlignOnBaseline(true);
    row2Panel.setLayout(flowLayout3);
    stationPanel.add(row2Panel);

    row3Panel.setMinimumSize(new Dimension(380, 30));
    row3Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout4 = new FlowLayout(FlowLayout.LEFT);
    flowLayout4.setAlignOnBaseline(true);
    row3Panel.setLayout(flowLayout4);
    stationPanel.add(row3Panel);

    row4Panel.setMinimumSize(new Dimension(380, 30));
    row4Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout5 = new FlowLayout(FlowLayout.LEFT);
    flowLayout5.setAlignOnBaseline(true);
    row4Panel.setLayout(flowLayout5);
    stationPanel.add(row4Panel);

    row5Panel.setMinimumSize(new Dimension(380, 30));
    row5Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout6 = new FlowLayout(FlowLayout.LEFT);
    flowLayout6.setAlignOnBaseline(true);
    row5Panel.setLayout(flowLayout6);
    stationPanel.add(row5Panel);

    row6Panel.setMinimumSize(new Dimension(380, 30));
    row6Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout7 = new FlowLayout(FlowLayout.LEFT);
    flowLayout7.setAlignOnBaseline(true);
    row6Panel.setLayout(flowLayout7);
    stationPanel.add(row6Panel);

    row7Panel.setMinimumSize(new Dimension(380, 30));
    row7Panel.setPreferredSize(new Dimension(380, 30));
    FlowLayout flowLayout9 = new FlowLayout(FlowLayout.LEFT);
    flowLayout9.setAlignOnBaseline(true);
    row7Panel.setLayout(flowLayout9);
    stationPanel.add(row7Panel);

    row9Panel.setMinimumSize(new Dimension(380, 30));
    row9Panel.setPreferredSize(new Dimension(380, 30));
    row9Panel.setLayout(new FlowLayout(FlowLayout.LEFT));
    stationPanel.add(row9Panel);

    buttonPanel.setPreferredSize(new Dimension(380, 40));
    FlowLayout flowLayout10 = new FlowLayout();
    flowLayout10.setAlignOnBaseline(true);
    buttonPanel.setLayout(flowLayout10);
    stationPanel.add(buttonPanel);

    mainTP.addTab("Station", stationPanel);

    memberPanel.setLayout(new BorderLayout());

    drivewayTableSP.setViewportView(shuttlePanel);

    memberPanel.add(drivewayTableSP, BorderLayout.CENTER);

    mainTP.addTab("Members", memberPanel);

    add(mainTP, BorderLayout.CENTER);

    westPanel.setMinimumSize(new Dimension(175, 500));
    westPanel.setPreferredSize(new Dimension(175, 500));
    westPanel.setLayout(new BorderLayout());

    stationsSP.setPreferredSize(new Dimension(175, 130));

    stationList.addListSelectionListener(new ListSelectionListener() {
      public void valueChanged(ListSelectionEvent evt) {
        stationListValueChanged(evt);
      }
    });
    stationsSP.setViewportView(stationList);

    westPanel.add(stationsSP, BorderLayout.CENTER);

    add(westPanel, BorderLayout.WEST);

    bottomPanel.setPreferredSize(new Dimension(1000, 50));
    bottomPanel.setRequestFocusEnabled(false);
    FlowLayout flowLayout12 = new FlowLayout(FlowLayout.RIGHT);
    flowLayout12.setAlignOnBaseline(true);
    bottomPanel.setLayout(flowLayout12);
    bottomPanel.add(filler1);

    saveBtn.setIcon(new ImageIcon(getClass().getResource("/media/save-24.png"))); // NOI18N
    saveBtn.setMaximumSize(new Dimension(40, 40));
    saveBtn.setMinimumSize(new Dimension(40, 40));
    saveBtn.setPreferredSize(new Dimension(40, 40));
    saveBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        saveBtnActionPerformed(evt);
      }
    });
    bottomPanel.add(saveBtn);

    add(bottomPanel, BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

  private void newBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
    Logger.trace("Create new Station...");
    selectedStation = new StationBean();

    List<StationBean> stations = PersistenceFactory.getService().getStations();
    String newId = "station-" + (stations.size() + 1);

    selectedStation.setId(newId);
    selectedStation.setLocomotiveCount(0);
    selectedStation.setMinLocomotives(1);
    selectedStation.setFifo(true);

    setFieldValues();
  }//GEN-LAST:event_newBtnActionPerformed

  private void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    if (selectedStation != null) {
      selectedStation.setName(stationNameTF.getText());
      selectedStation.setFifo(useFifoCB.isSelected());
      selectedStation.setMinLocomotives((Integer) minLocsSpinner.getValue());

      List<BlockBean> blocks = shuttlePanel.getSelectedItems();
      List<BlockBean> currentBlocks = selectedStation.getBlockBeans();

      for (BlockBean bb : currentBlocks) {
        if (!blocks.contains(bb)) {
          selectedStation.removeBlock(bb);
        }
      }

      //Create station BlockBeans
      for (BlockBean block : blocks) {
        if (!currentBlocks.contains(block)) {
          selectedStation.addBlock(block);
        }
      }

      Logger.trace("Saving: " + selectedStation.toString());

      selectedStation = PersistenceFactory.getService().persist(selectedStation);

      int selectedIndex = stationList.getSelectedIndex();
      initStations();
      stationList.setSelectedIndex(selectedIndex);
    }
  }//GEN-LAST:event_saveBtnActionPerformed

  private void deleteBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
    Logger.trace("Delete: " + selectedStation.toString());
    PersistenceFactory.getService().remove(selectedStation);
    selectedStation = null;
    initStations();
  }//GEN-LAST:event_deleteBtnActionPerformed

  private void stationListValueChanged(ListSelectionEvent evt) {//GEN-FIRST:event_stationListValueChanged
    if (!evt.getValueIsAdjusting()) {
      selectedStation = stationList.getSelectedValue();
      Logger.trace(selectedStation);
      setFieldValues();

    }
  }//GEN-LAST:event_stationListValueChanged

  class StationBeanByNameSorter implements Comparator<StationBean> {

    @Override
    public int compare(StationBean a, StationBean b) {
      //Avoid null pointers
      String aa = a.getName();
      if (aa == null) {
        aa = "aaa";
      }
      String bb = b.getName();
      if (bb == null) {
        bb = "aaa";
      }

      return aa.compareTo(bb);
    }
  }

  class StationBeanListModel extends AbstractListModel<StationBean> {

    private static final long serialVersionUID = 5484763343433191947L;

    private final List<StationBean> all;

    public StationBeanListModel() {
      all = new ArrayList<>();
    }

    @Override
    public int getSize() {
      return all.size();
    }

    @Override
    public StationBean getElementAt(int index) {
      return (StationBean) all.toArray()[index];
    }

    public void add(StationBean element) {
      if (all.add(element)) {
        Collections.sort(all, new StationBeanByNameSorter());
        fireContentsChanged(this, 0, getSize());
      }
    }

    public void addAll(StationBean elements[]) {
      Collection<StationBean> c = Arrays.asList(elements);
      all.addAll(c);
      Collections.sort(all, new StationBeanByNameSorter());
      fireContentsChanged(this, 0, getSize());
    }

    public void addAll(Collection<StationBean> elements) {
      all.addAll(elements);
      Collections.sort(all, new StationBeanByNameSorter());
      fireContentsChanged(this, 0, getSize());
    }

    public void clear() {
      all.clear();
      fireContentsChanged(this, 0, getSize());
    }

    public boolean contains(StationBean element) {
      return all.contains(element);
    }

    public StationBean firstElement() {
      if (!all.isEmpty()) {
        return all.get(0);
      } else {
        return null;
      }
    }

    public Iterator<StationBean> iterator() {
      return all.iterator();
    }

    public StationBean lastElement() {
      if (!all.isEmpty()) {
        return all.get(all.size() - 1);
      } else {
        return null;
      }
    }

    public boolean removeElement(StationBean element) {
      boolean removed = all.remove(element);
      if (removed) {
        Collections.sort(all, new StationBeanByNameSorter());
        fireContentsChanged(this, 0, getSize());
      }
      return removed;
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  JPanel bottomPanel;
  JPanel buttonPanel;
  JButton deleteBtn;
  DrivewayCommandTableModel drivewayCommandTableModel;
  JScrollPane drivewayTableSP;
  Box.Filler filler1;
  JLabel idLbl;
  JPanel leftPanel;
  JTabbedPane mainTP;
  JPanel memberPanel;
  JLabel minLocsLbl;
  JSpinner minLocsSpinner;
  JButton newBtn;
  JPanel rightPanel;
  JPanel row0Panel;
  JPanel row1Panel;
  JPanel row2Panel;
  JPanel row3Panel;
  JPanel row4Panel;
  JPanel row5Panel;
  JPanel row6Panel;
  JPanel row7Panel;
  JPanel row9Panel;
  JButton saveBtn;
  Shuttle shuttlePanel;
  JList<StationBean> stationList;
  JLabel stationNameLbl;
  JTextField stationNameTF;
  JPanel stationPanel;
  JScrollPane stationsSP;
  JPanel topPanel;
  JCheckBox useFifoCB;
  JLabel useFifoLbl;
  JPanel westPanel;
  // End of variables declaration//GEN-END:variables
}
