/*
 * Copyright 2023 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.layout.dialogs;

import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import jcs.entities.SensorBean;
import jcs.persistence.PersistenceFactory;
import jcs.ui.layout.tiles.Block;
import jcs.ui.layout.tiles.Tile;

/**
 *
 * @author fransjacobs
 */
public class BlockDialog extends javax.swing.JDialog {

  private final Block block;

  private ComboBoxModel<SensorBean> plusSensorComboBoxModel;
  private ComboBoxModel<SensorBean> minSensorComboBoxModel;

  /**
   * Creates new form SensorDialog
   *
   * @param parent
   * @param tile
   */
  public BlockDialog(java.awt.Frame parent, Tile tile) {
    super(parent, true);
    this.block = (Block) tile;
    initComponents();

    postInit();
  }

  private void postInit() {
    setLocationRelativeTo(null);
    String text = this.headingLbl.getText(); // + " " + this.turnout.getId();
    this.headingLbl.setText(text);

    if (this.block != null) {
      //Get a list of all available Sensors
      List<SensorBean> sensors = PersistenceFactory.getService().getSensors();
      //Expand with an empty one for display
      SensorBean emptyBean = new SensorBean();
      sensors.add(emptyBean);

      plusSensorComboBoxModel = new DefaultComboBoxModel(sensors.toArray());
      minSensorComboBoxModel = new DefaultComboBoxModel(sensors.toArray());
      this.plusSensorCB.setModel(plusSensorComboBoxModel);
      this.minSensorCB.setModel(minSensorComboBoxModel);

      if (this.block.getBlockBean() != null && this.block.getBlockBean().getPlusSensorBean() != null) {
        this.plusSensorComboBoxModel.setSelectedItem(block.getBlockBean().getPlusSensorBean());
      }

    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    headingPanel = new javax.swing.JPanel();
    headingLbl = new javax.swing.JLabel();
    deviceIdPanel = new javax.swing.JPanel();
    blockIdLbl = new javax.swing.JLabel();
    blockIdTF = new javax.swing.JTextField();
    namePanel = new javax.swing.JPanel();
    blockDescLbl = new javax.swing.JLabel();
    blockTF1 = new javax.swing.JTextField();
    plusSensorPanel = new javax.swing.JPanel();
    plusSensorLbl = new javax.swing.JLabel();
    plusSensorCB = new javax.swing.JComboBox<>();
    minSensorPanel = new javax.swing.JPanel();
    minSensorLbl = new javax.swing.JLabel();
    minSensorCB = new javax.swing.JComboBox<>();
    saveExitPanel = new javax.swing.JPanel();
    saveExitBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Block Properties");
    setMinimumSize(new java.awt.Dimension(290, 200));
    getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

    headingPanel.setMinimumSize(new java.awt.Dimension(290, 40));
    headingPanel.setPreferredSize(new java.awt.Dimension(290, 40));
    headingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    headingLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/new-block.png"))); // NOI18N
    headingLbl.setText("Block");
    headingPanel.add(headingLbl);

    getContentPane().add(headingPanel);

    deviceIdPanel.setPreferredSize(new java.awt.Dimension(290, 40));
    java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout2.setAlignOnBaseline(true);
    deviceIdPanel.setLayout(flowLayout2);

    blockIdLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    blockIdLbl.setText("Id:");
    blockIdLbl.setPreferredSize(new java.awt.Dimension(100, 16));
    deviceIdPanel.add(blockIdLbl);

    blockIdTF.setPreferredSize(new java.awt.Dimension(150, 23));
    deviceIdPanel.add(blockIdTF);

    getContentPane().add(deviceIdPanel);

    namePanel.setMinimumSize(new java.awt.Dimension(290, 40));
    namePanel.setPreferredSize(new java.awt.Dimension(290, 40));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout1.setAlignOnBaseline(true);
    namePanel.setLayout(flowLayout1);

    blockDescLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    blockDescLbl.setText("Name:");
    blockDescLbl.setToolTipText("");
    blockDescLbl.setPreferredSize(new java.awt.Dimension(100, 16));
    namePanel.add(blockDescLbl);

    blockTF1.setPreferredSize(new java.awt.Dimension(150, 23));
    namePanel.add(blockTF1);

    getContentPane().add(namePanel);

    plusSensorPanel.setPreferredSize(new java.awt.Dimension(290, 40));
    java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout7.setAlignOnBaseline(true);
    plusSensorPanel.setLayout(flowLayout7);

    plusSensorLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    plusSensorLbl.setText("Plus Sensor:");
    plusSensorLbl.setDoubleBuffered(true);
    plusSensorLbl.setPreferredSize(new java.awt.Dimension(100, 17));
    plusSensorPanel.add(plusSensorLbl);

    plusSensorCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusSensorCBActionPerformed(evt);
      }
    });
    plusSensorPanel.add(plusSensorCB);

    getContentPane().add(plusSensorPanel);

    minSensorPanel.setPreferredSize(new java.awt.Dimension(290, 40));
    java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout3.setAlignOnBaseline(true);
    minSensorPanel.setLayout(flowLayout3);

    minSensorLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    minSensorLbl.setText("Min. Sensor:");
    minSensorLbl.setPreferredSize(new java.awt.Dimension(100, 17));
    minSensorPanel.add(minSensorLbl);

    minSensorCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        minSensorCBActionPerformed(evt);
      }
    });
    minSensorPanel.add(minSensorCB);

    getContentPane().add(minSensorPanel);

    saveExitPanel.setPreferredSize(new java.awt.Dimension(290, 50));
    java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT);
    flowLayout4.setAlignOnBaseline(true);
    saveExitPanel.setLayout(flowLayout4);

    saveExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/save-24.png"))); // NOI18N
    saveExitBtn.setToolTipText("Save and Exit");
    saveExitBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveExitBtnActionPerformed(evt);
      }
    });
    saveExitPanel.add(saveExitBtn);

    getContentPane().add(saveExitPanel);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void saveExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveExitBtnActionPerformed
//      if (this.turnout != null && this.turnout.getAccessoryBean() != null) {
//        if (this.turnout.getAccessoryBean().getName() != null) {
//          PersistenceFactory.getService().persist((turnout));
//
//          TrackControllerFactory.getTrackController().addAccessoryListener(turnout);
//        } else {
//          this.turnout.setAccessoryBean(null);
//          PersistenceFactory.getService().persist((turnout));
//        }
//      }
//      this.setVisible(false);
//      this.dispose();
//      Logger.trace(evt.getActionCommand() + "Switch " + turnout.getId() + " linked to accessoryId: " + turnout.getAccessoryId());
    }//GEN-LAST:event_saveExitBtnActionPerformed

  private void plusSensorCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusSensorCBActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_plusSensorCBActionPerformed

  private void minSensorCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minSensorCBActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_minSensorCBActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel blockDescLbl;
  private javax.swing.JLabel blockIdLbl;
  private javax.swing.JTextField blockIdTF;
  private javax.swing.JTextField blockTF1;
  private javax.swing.JPanel deviceIdPanel;
  private javax.swing.JLabel headingLbl;
  private javax.swing.JPanel headingPanel;
  private javax.swing.JComboBox<SensorBean> minSensorCB;
  private javax.swing.JLabel minSensorLbl;
  private javax.swing.JPanel minSensorPanel;
  private javax.swing.JPanel namePanel;
  private javax.swing.JComboBox<SensorBean> plusSensorCB;
  private javax.swing.JLabel plusSensorLbl;
  private javax.swing.JPanel plusSensorPanel;
  private javax.swing.JButton saveExitBtn;
  private javax.swing.JPanel saveExitPanel;
  // End of variables declaration//GEN-END:variables
}
