-- H2 2.4.240; 
;              
CREATE USER IF NOT EXISTS "JCS" SALT 'fc40fdb9b1ff5d96' HASH '7442d719ccf651d1601a11f83df8e7b49fa1f589a7a3a9d04d69998e22249fcd' ADMIN;         
CREATE USER IF NOT EXISTS "SA" SALT 'eb1afca2ae28ad08' HASH 'f2c8c398ba306b98b4cb3ecfe0865559d3a221c6c0bc6aaeaef142c3f78b5915' ADMIN;          
CREATE SCHEMA IF NOT EXISTS "jcs" AUTHORIZATION "JCS";         
DROP TABLE IF EXISTS "jcs"."tiles" CASCADE;    
DROP TABLE IF EXISTS "jcs"."stations" CASCADE; 
DROP TABLE IF EXISTS "jcs"."station_blocks" CASCADE;           
DROP TABLE IF EXISTS "jcs"."accessories" CASCADE;              
DROP TABLE IF EXISTS "jcs"."blocks" CASCADE;   
DROP TABLE IF EXISTS "jcs"."sensors" CASCADE;  
DROP TABLE IF EXISTS "jcs"."locomotive_functions" CASCADE;     
DROP TABLE IF EXISTS "jcs"."locomotives" CASCADE;              
DROP TABLE IF EXISTS "jcs"."command_stations" CASCADE;         
DROP TABLE IF EXISTS "jcs"."routes" CASCADE;   
DROP TABLE IF EXISTS "jcs"."route_elements" CASCADE;           
DROP TABLE IF EXISTS "jcs"."jcs_properties" CASCADE;           
DROP TABLE IF EXISTS "jcs"."jcs_version" CASCADE;              
CREATE CACHED TABLE "jcs"."tiles"(
    "id" CHARACTER VARYING(255) NOT NULL,
    "tile_type" CHARACTER VARYING(255) NOT NULL,
    "orientation" CHARACTER VARYING(255) NOT NULL,
    "direction" CHARACTER VARYING(255) NOT NULL,
    "x" INTEGER NOT NULL,
    "y" INTEGER NOT NULL,
    "signal_type" CHARACTER VARYING(255),
    "accessory_id" CHARACTER VARYING(255),
    "sensor_id" INTEGER
);          
ALTER TABLE "jcs"."tiles" ADD CONSTRAINT "jcs"."tile_pk" PRIMARY KEY("id");    
-- 492 +/- SELECT COUNT(*) FROM jcs.tiles;     
INSERT INTO "jcs"."tiles" VALUES
('bk-1', 'Block', 'South', 'Center', 900, 500, NULL, NULL, NULL),
('bk-2', 'Block', 'South', 'Center', 940, 500, NULL, NULL, NULL),
('bk-3', 'Block', 'North', 'Center', 1020, 500, NULL, NULL, NULL),
('bk-4', 'Block', 'North', 'Center', 1060, 500, NULL, NULL, NULL),
('bk-5', 'Block', 'North', 'Center', 1100, 540, NULL, NULL, NULL),
('se-1', 'Sensor', 'North', 'Center', 900, 420, NULL, NULL, NULL),
('se-2', 'Sensor', 'North', 'Center', 940, 420, NULL, NULL, NULL),
('se-3', 'Sensor', 'North', 'Center', 1020, 420, NULL, NULL, NULL),
('se-4', 'Sensor', 'North', 'Center', 1060, 420, NULL, NULL, NULL),
('se-5', 'Sensor', 'North', 'Center', 1100, 460, NULL, NULL, NULL),
('si-3', 'Signal', 'North', 'Center', 460, 340, 'NONE', NULL, NULL),
('si-4', 'Signal', 'North', 'Center', 580, 380, 'NONE', NULL, NULL),
('sw-1', 'Switch', 'South', 'Right', 900, 300, 'NONE', NULL, NULL),
('sw-2', 'Switch', 'West', 'Right', 820, 180, 'NONE', NULL, NULL),
('sw-3', 'Switch', 'South', 'Left', 900, 180, 'NONE', NULL, NULL),
('ct-1', 'Curved', 'South', 'Center', 900, 260, NULL, NULL, NULL),
('ct-2', 'Curved', 'North', 'Center', 860, 260, NULL, NULL, NULL),
('ct-3', 'Curved', 'South', 'Center', 1100, 340, NULL, NULL, NULL),
('ct-4', 'Curved', 'West', 'Center', 1140, 140, NULL, NULL, NULL),
('ct-5', 'Curved', 'South', 'Center', 860, 220, NULL, NULL, NULL),
('ct-6', 'Curved', 'North', 'Center', 820, 220, NULL, NULL, NULL),
('st-2', 'Straight', 'East', 'Center', 820, 60, NULL, NULL, NULL),
('st-3', 'Straight', 'North', 'Center', 420, 420, NULL, NULL, NULL),
('st-4', 'Straight', 'East', 'Center', 860, 20, NULL, NULL, NULL),
('sw-6', 'Switch', 'West', 'Right', 940, 220, 'NONE', NULL, NULL),
('ct-7', 'Curved', 'North', 'Center', 900, 220, NULL, NULL, NULL),
('st-7', 'Straight', 'North', 'Center', 940, 380, NULL, NULL, NULL),
('st-8', 'Straight', 'North', 'Center', 1020, 380, NULL, NULL, NULL),
('ct-8', 'Curved', 'South', 'Center', 900, 140, NULL, NULL, NULL),
('st-9', 'Straight', 'West', 'Center', 1500, 780, NULL, NULL, NULL),
('st-10', 'Straight', 'West', 'Center', 1100, 820, NULL, NULL, NULL),
('st-11', 'Straight', 'West', 'Center', 500, 580, NULL, NULL, NULL),
('st-12', 'Straight', 'West', 'Center', 540, 620, NULL, NULL, NULL),
('se-6', 'Sensor', 'West', 'Center', 740, 140, NULL, NULL, NULL),
('se-7', 'Sensor', 'West', 'Center', 740, 180, NULL, NULL, NULL),
('bk-6', 'Block', 'East', 'Center', 660, 180, NULL, NULL, NULL),
('bk-7', 'Block', 'West', 'Center', 660, 140, NULL, NULL, NULL),
('bk-8', 'Block', 'South', 'Center', 1140, 540, NULL, NULL, NULL),
('bk-9', 'Block', 'South', 'Center', 1180, 580, NULL, NULL, NULL),
('sw-8', 'Switch', 'East', 'Left', 1060, 180, 'NONE', NULL, NULL),
('st-13', 'Straight', 'East', 'Center', 860, 140, NULL, NULL, NULL),
('ct-9', 'Curved', 'East', 'Center', 1020, 140, NULL, NULL, NULL),
('st-14', 'Straight', 'South', 'Center', 900, 740, NULL, NULL, NULL),
('st-15', 'Straight', 'South', 'Center', 1180, 140, NULL, NULL, NULL),
('st-16', 'Straight', 'South', 'Center', 1060, 220, NULL, NULL, NULL),
('st-17', 'Straight', 'West', 'Center', 1060, 140, NULL, NULL, NULL),
('sw-10', 'Switch', 'North', 'Left', 1180, 420, 'NONE', NULL, NULL),
('sw-11', 'Switch', 'West', 'Right', 1140, 380, 'NONE', NULL, NULL),
('ct-10', 'Curved', 'South', 'Center', 1180, 380, NULL, NULL, NULL),
('st-22', 'Straight', 'West', 'Center', 860, 180, NULL, NULL, NULL),
('ct-11', 'Curved', 'North', 'Center', 1140, 740, NULL, NULL, NULL),
('st-24', 'Straight', 'South', 'Center', 1060, 740, NULL, NULL, NULL),
('ct-12', 'Curved', 'South', 'Center', 1140, 60, NULL, NULL, NULL),
('st-25', 'Straight', 'West', 'Center', 1100, 60, NULL, NULL, NULL),
('se-8', 'Sensor', 'South', 'Center', 1140, 460, NULL, NULL, NULL),
('se-9', 'Sensor', 'South', 'Center', 1140, 620, NULL, NULL, NULL),
('se-10', 'Sensor', 'West', 'Center', 580, 140, NULL, NULL, NULL),
('se-11', 'Sensor', 'West', 'Center', 580, 180, NULL, NULL, NULL),
('se-12', 'Sensor', 'West', 'Center', 1140, 20, NULL, NULL, NULL),
('se-13', 'Sensor', 'West', 'Center', 980, 20, NULL, NULL, NULL);        
INSERT INTO "jcs"."tiles" VALUES
('st-26', 'Straight', 'North', 'Center', 1500, 940, NULL, NULL, NULL),
('st-27', 'Straight', 'North', 'Center', 260, 180, NULL, NULL, NULL),
('st-28', 'Straight', 'North', 'Center', 1180, 60, NULL, NULL, NULL),
('st-29', 'Straight', 'East', 'Center', 500, 620, NULL, NULL, NULL),
('st-32', 'Straight', 'North', 'Center', 420, 500, NULL, NULL, NULL),
('st-33', 'Straight', 'North', 'Center', 420, 460, NULL, NULL, NULL),
('st-34', 'Straight', 'North', 'Center', 100, 300, NULL, NULL, NULL),
('tw-1', 'ThreeWay', 'South', 'Center', 1060, 780, 'NONE', NULL, NULL),
('cs-2', 'CrossSwitch', 'South', 'Left', 1020, 260, 'NONE', NULL, NULL),
('cx-10', 'Cross', 'South', 'Center', 980, 220, NULL, NULL, NULL),
('cs-1', 'CrossSwitch', 'South', 'Right', 940, 260, 'NONE', NULL, NULL),
('ct-13', 'Curved', 'West', 'Center', 1180, 180, NULL, NULL, NULL),
('ct-15', 'Curved', 'South', 'Center', 1180, 20, NULL, NULL, NULL),
('cs-5', 'CrossSwitch', 'South', 'Right', 1020, 180, 'NONE', NULL, NULL),
('si-8', 'Signal', 'North', 'Center', 940, 340, 'NONE', NULL, NULL),
('si-9', 'Signal', 'North', 'Center', 1020, 340, 'NONE', NULL, NULL),
('si-10', 'Signal', 'North', 'Center', 1060, 380, 'NONE', NULL, NULL),
('si-11', 'Signal', 'North', 'Center', 900, 380, 'NONE', NULL, NULL),
('si-12', 'Signal', 'North', 'Center', 1100, 420, 'NONE', NULL, NULL),
('si-13', 'Signal', 'North', 'Center', 1140, 420, 'NONE', NULL, NULL),
('si-14', 'Signal', 'North', 'Center', 1180, 460, 'NONE', NULL, NULL),
('sw-13', 'Switch', 'South', 'Left', 1220, 420, 'NONE', NULL, NULL),
('si-15', 'Signal', 'North', 'Center', 1220, 460, 'NONE', NULL, NULL),
('bk-10', 'Block', 'East', 'Center', 1060, 20, NULL, NULL, NULL),
('bk-11', 'Block', 'West', 'Center', 980, 60, NULL, NULL, NULL),
('se-14', 'Sensor', 'West', 'Center', 1060, 60, NULL, NULL, NULL),
('se-15', 'Sensor', 'West', 'Center', 900, 60, NULL, NULL, NULL),
('sd-1', 'StraightDirection', 'West', 'Center', 820, 20, NULL, NULL, NULL),
('sd-2', 'StraightDirection', 'East', 'Center', 860, 60, NULL, NULL, NULL),
('se-16', 'Sensor', 'East', 'Center', 780, 20, NULL, NULL, NULL),
('se-17', 'Sensor', 'East', 'Center', 780, 60, NULL, NULL, NULL),
('bk-12', 'Block', 'East', 'Center', 700, 60, NULL, NULL, NULL),
('bk-13', 'Block', 'West', 'Center', 700, 20, NULL, NULL, NULL),
('se-18', 'Sensor', 'West', 'Center', 620, 20, NULL, NULL, NULL),
('se-19', 'Sensor', 'West', 'Center', 620, 60, NULL, NULL, NULL),
('sd-3', 'StraightDirection', 'West', 'Center', 580, 20, NULL, NULL, NULL),
('sd-4', 'StraightDirection', 'East', 'Center', 580, 60, NULL, NULL, NULL),
('sd-5', 'StraightDirection', 'South', 'Center', 1020, 860, NULL, NULL, NULL),
('sd-6', 'StraightDirection', 'West', 'Center', 1100, 860, NULL, NULL, NULL),
('ct-16', 'Curved', 'East', 'Center', 540, 180, NULL, NULL, NULL),
('sw-14', 'Switch', 'North', 'Left', 540, 260, 'NONE', NULL, NULL),
('ct-17', 'Curved', 'South', 'Center', 580, 260, NULL, NULL, NULL),
('sd-7', 'StraightDirection', 'South', 'Center', 540, 300, NULL, NULL, NULL),
('sd-8', 'StraightDirection', 'North', 'Center', 580, 300, NULL, NULL, NULL),
('se-20', 'Sensor', 'North', 'Center', 460, 540, NULL, NULL, NULL),
('se-21', 'Sensor', 'North', 'Center', 580, 420, NULL, NULL, NULL),
('bk-14', 'Block', 'North', 'Center', 580, 500, NULL, NULL, NULL),
('bk-15', 'Block', 'North', 'Center', 460, 460, NULL, NULL, NULL),
('se-22', 'Sensor', 'South', 'Center', 460, 380, NULL, NULL, NULL),
('ct-18', 'Curved', 'North', 'Center', 460, 580, NULL, NULL, NULL),
('ct-19', 'Curved', 'West', 'Center', 540, 580, NULL, NULL, NULL),
('se-23', 'Sensor', 'North', 'Center', 580, 580, NULL, NULL, NULL),
('ct-20', 'Curved', 'West', 'Center', 580, 620, NULL, NULL, NULL),
('ct-21', 'Curved', 'North', 'Center', 420, 620, NULL, NULL, NULL),
('ct-22', 'Curved', 'South', 'Center', 460, 260, NULL, NULL, NULL),
('st-35', 'Straight', 'South', 'Center', 420, 180, NULL, NULL, NULL),
('st-36', 'Straight', 'North', 'Center', 420, 340, NULL, NULL, NULL),
('st-37', 'Straight', 'North', 'Center', 420, 540, NULL, NULL, NULL),
('st-38', 'Straight', 'North', 'Center', 420, 580, NULL, NULL, NULL);       
INSERT INTO "jcs"."tiles" VALUES
('sw-15', 'Switch', 'North', 'Left', 420, 260, 'NONE', NULL, NULL),
('sw-16', 'Switch', 'South', 'Right', 420, 220, 'NONE', NULL, NULL),
('ct-23', 'Curved', 'West', 'Center', 460, 220, NULL, NULL, NULL),
('ct-24', 'Curved', 'East', 'Center', 460, 180, NULL, NULL, NULL),
('st-40', 'Straight', 'East', 'Center', 460, 60, NULL, NULL, NULL),
('st-41', 'Straight', 'South', 'Center', 540, 340, NULL, NULL, NULL),
('st-42', 'Straight', 'South', 'Center', 540, 380, NULL, NULL, NULL),
('st-43', 'Straight', 'South', 'Center', 540, 500, NULL, NULL, NULL),
('st-44', 'Straight', 'South', 'Center', 540, 420, NULL, NULL, NULL),
('st-45', 'Straight', 'South', 'Center', 540, 460, NULL, NULL, NULL),
('sw-17', 'Switch', 'South', 'Right', 420, 140, 'NONE', NULL, NULL),
('cs-8', 'CrossSwitch', 'West', 'Left', 540, 60, 'NONE', NULL, NULL),
('ct-25', 'Curved', 'West', 'Center', 460, 140, NULL, NULL, NULL),
('sw-18', 'Switch', 'East', 'Left', 540, 20, 'NONE', NULL, NULL),
('ct-26', 'Curved', 'West', 'Center', 500, 100, NULL, NULL, NULL),
('ct-37', 'Curved', 'East', 'Center', 460, 100, NULL, NULL, NULL),
('ct-39', 'Curved', 'East', 'Center', 500, 140, NULL, NULL, NULL),
('st-46', 'Straight', 'South', 'Center', 540, 220, NULL, NULL, NULL),
('st-47', 'Straight', 'South', 'Center', 420, 380, NULL, NULL, NULL),
('st-48', 'Straight', 'South', 'Center', 100, 220, NULL, NULL, NULL),
('st-50', 'Straight', 'South', 'Center', 60, 380, NULL, NULL, NULL),
('st-51', 'Straight', 'South', 'Center', 540, 540, NULL, NULL, NULL),
('sw-19', 'Switch', 'West', 'Right', 420, 60, 'NONE', NULL, NULL),
('ct-40', 'Curved', 'North', 'Center', 1060, 860, NULL, NULL, NULL),
('ct-41', 'Curved', 'West', 'Center', 500, 180, NULL, NULL, NULL),
('st-53', 'Straight', 'East', 'Center', 500, 20, NULL, NULL, NULL),
('st-54', 'Straight', 'East', 'Center', 460, 20, NULL, NULL, NULL),
('st-55', 'Straight', 'East', 'Center', 420, 20, NULL, NULL, NULL),
('st-56', 'Straight', 'East', 'Center', 380, 20, NULL, NULL, NULL),
('st-57', 'Straight', 'East', 'Center', 300, 20, NULL, NULL, NULL),
('st-58', 'Straight', 'East', 'Center', 220, 300, NULL, NULL, NULL),
('cs-9', 'CrossSwitch', 'South', 'Left', 1060, 300, 'NONE', NULL, NULL),
('se-24', 'Sensor', 'South', 'Center', 900, 580, NULL, NULL, NULL),
('se-25', 'Sensor', 'South', 'Center', 940, 580, NULL, NULL, NULL),
('se-26', 'Sensor', 'South', 'Center', 860, 500, NULL, NULL, NULL),
('se-27', 'Sensor', 'South', 'Center', 1020, 580, NULL, NULL, NULL),
('se-28', 'Sensor', 'South', 'Center', 1060, 580, NULL, NULL, NULL),
('se-29', 'Sensor', 'South', 'Center', 1100, 620, NULL, NULL, NULL),
('se-30', 'Sensor', 'South', 'Center', 1180, 500, NULL, NULL, NULL),
('se-31', 'Sensor', 'South', 'Center', 1180, 660, NULL, NULL, NULL),
('se-32', 'Sensor', 'West', 'Center', 860, 100, NULL, NULL, NULL),
('sw-20', 'Switch', 'West', 'Right', 1460, 100, 'NONE', NULL, NULL),
('sw-21', 'Switch', 'West', 'Right', 1420, 100, 'NONE', NULL, NULL),
('sw-22', 'Switch', 'West', 'Right', 1380, 100, 'NONE', NULL, NULL),
('sw-23', 'Switch', 'West', 'Right', 1340, 100, 'NONE', NULL, NULL),
('sw-25', 'Switch', 'West', 'Right', 1500, 100, 'NONE', NULL, NULL),
('st-59', 'Straight', 'East', 'Center', 1140, 180, NULL, NULL, NULL),
('st-60', 'Straight', 'North', 'Center', 1540, 180, NULL, NULL, NULL),
('st-61', 'Straight', 'North', 'Center', 1500, 460, NULL, NULL, NULL),
('st-62', 'Straight', 'North', 'Center', 1340, 180, NULL, NULL, NULL),
('st-63', 'Straight', 'North', 'Center', 1380, 180, NULL, NULL, NULL),
('st-64', 'Straight', 'North', 'Center', 1420, 180, NULL, NULL, NULL),
('ct-42', 'Curved', 'South', 'Center', 1540, 100, NULL, NULL, NULL),
('st-65', 'Straight', 'South', 'Center', 1500, 180, NULL, NULL, NULL),
('se-33', 'Sensor', 'West', 'Center', 1020, 100, NULL, NULL, NULL),
('se-34', 'Sensor', 'South', 'Center', 1420, 220, NULL, NULL, NULL),
('se-35', 'Sensor', 'South', 'Center', 1340, 220, NULL, NULL, NULL),
('se-36', 'Sensor', 'South', 'Center', 1380, 220, NULL, NULL, NULL),
('se-37', 'Sensor', 'South', 'Center', 1420, 380, NULL, NULL, NULL);             
INSERT INTO "jcs"."tiles" VALUES
('se-38', 'Sensor', 'South', 'Center', 1460, 220, NULL, NULL, NULL),
('se-39', 'Sensor', 'South', 'Center', 1500, 220, NULL, NULL, NULL),
('bk-16', 'Block', 'North', 'Center', 1540, 300, NULL, NULL, NULL),
('bk-17', 'Block', 'North', 'Center', 1500, 300, NULL, NULL, NULL),
('bk-18', 'Block', 'North', 'Center', 1460, 300, NULL, NULL, NULL),
('bk-19', 'Block', 'North', 'Center', 1420, 300, NULL, NULL, NULL),
('bk-20', 'Block', 'North', 'Center', 1380, 300, NULL, NULL, NULL),
('bk-21', 'Block', 'North', 'Center', 1340, 300, NULL, NULL, NULL),
('bk-22', 'Block', 'West', 'Center', 940, 100, NULL, NULL, NULL),
('se-41', 'Sensor', 'North', 'Center', 1340, 380, NULL, NULL, NULL),
('se-42', 'Sensor', 'North', 'Center', 1380, 380, NULL, NULL, NULL),
('se-43', 'Sensor', 'North', 'Center', 1460, 380, NULL, NULL, NULL),
('se-44', 'Sensor', 'North', 'Center', 1500, 380, NULL, NULL, NULL),
('se-45', 'Sensor', 'North', 'Center', 1540, 380, NULL, NULL, NULL),
('se-46', 'Sensor', 'North', 'Center', 1540, 220, NULL, NULL, NULL),
('sw-26', 'Switch', 'East', 'Right', 1460, 500, 'NONE', NULL, NULL),
('sw-27', 'Switch', 'East', 'Right', 1500, 500, 'NONE', NULL, NULL),
('sw-28', 'Switch', 'South', 'Left', 1540, 500, 'NONE', NULL, NULL),
('sw-29', 'Switch', 'East', 'Right', 1420, 500, 'NONE', NULL, NULL),
('sw-30', 'Switch', 'East', 'Right', 1380, 500, 'NONE', NULL, NULL),
('ct-43', 'Curved', 'North', 'Center', 1340, 500, NULL, NULL, NULL),
('ct-44', 'Curved', 'North', 'Center', 140, 300, NULL, NULL, NULL),
('ct-45', 'Curved', 'West', 'Center', 940, 820, NULL, NULL, NULL),
('ct-46', 'Curved', 'East', 'Center', 820, 780, NULL, NULL, NULL),
('st-66', 'Straight', 'South', 'Center', 260, 100, NULL, NULL, NULL),
('st-67', 'Straight', 'South', 'Center', 100, 180, NULL, NULL, NULL),
('se-47', 'Sensor', 'South', 'Center', 860, 340, NULL, NULL, NULL),
('bk-23', 'Block', 'South', 'Center', 860, 420, NULL, NULL, NULL),
('st-68', 'Straight', 'South', 'Center', 1220, 180, NULL, NULL, NULL),
('se-49', 'Sensor', 'South', 'Center', 1220, 380, NULL, NULL, NULL),
('bk-24', 'Block', 'South', 'Center', 1220, 300, NULL, NULL, NULL),
('se-50', 'Sensor', 'South', 'Center', 1220, 220, NULL, NULL, NULL),
('et-1', 'End', 'North', 'Center', 1220, 140, NULL, NULL, NULL),
('se-51', 'Sensor', 'North', 'Center', 1220, 500, NULL, NULL, NULL),
('bk-25', 'Block', 'North', 'Center', 1220, 580, NULL, NULL, NULL),
('se-52', 'Sensor', 'North', 'Center', 1220, 660, NULL, NULL, NULL),
('et-2', 'End', 'South', 'Center', 1220, 700, NULL, NULL, NULL),
('st-69', 'Straight', 'South', 'Center', 1540, 940, NULL, NULL, NULL),
('et-3', 'End', 'South', 'Center', 1180, 700, NULL, NULL, NULL),
('si-16', 'Signal', 'South', 'Center', 1140, 660, 'NONE', NULL, NULL),
('sw-32', 'Switch', 'South', 'Left', 1140, 700, 'NONE', NULL, NULL),
('si-17', 'Signal', 'West', 'Center', 1220, 740, 'NONE', NULL, NULL),
('se-53', 'Sensor', 'East', 'Center', 1260, 740, NULL, NULL, NULL),
('bk-26', 'Block', 'East', 'Center', 1340, 740, NULL, NULL, NULL),
('se-54', 'Sensor', 'East', 'Center', 1420, 740, NULL, NULL, NULL),
('et-4', 'End', 'East', 'Center', 1460, 740, NULL, NULL, NULL),
('sw-33', 'Switch', 'North', 'Left', 1100, 700, 'NONE', NULL, NULL),
('sd-9', 'StraightDirection', 'North', 'Center', 1100, 740, NULL, NULL, NULL),
('ct-47', 'Curved', 'West', 'Center', 1100, 780, NULL, NULL, NULL),
('st-71', 'Straight', 'North', 'Center', 1100, 660, NULL, NULL, NULL),
('cs-10', 'CrossSwitch', 'North', 'Left', 1020, 780, 'NONE', NULL, NULL),
('cx-11', 'Cross', 'South', 'Center', 980, 700, NULL, NULL, NULL),
('cs-11', 'CrossSwitch', 'South', 'Right', 1020, 660, 'NONE', NULL, NULL),
('sw-34', 'Switch', 'North', 'Right', 1060, 660, 'NONE', NULL, NULL),
('si-18', 'Signal', 'South', 'Center', 1060, 620, 'NONE', NULL, NULL),
('si-19', 'Signal', 'South', 'Center', 1020, 620, 'NONE', NULL, NULL),
('st-72', 'Straight', 'South', 'Center', 1060, 260, NULL, NULL, NULL),
('st-74', 'Straight', 'South', 'Center', 1540, 980, NULL, NULL, NULL),
('st-75', 'Straight', 'South', 'Center', 1060, 700, NULL, NULL, NULL);        
INSERT INTO "jcs"."tiles" VALUES
('si-20', 'Signal', 'South', 'Center', 940, 620, 'NONE', NULL, NULL),
('si-21', 'Signal', 'South', 'Center', 900, 620, 'NONE', NULL, NULL),
('cs-12', 'CrossSwitch', 'South', 'Left', 940, 660, 'NONE', NULL, NULL),
('cs-14', 'CrossSwitch', 'South', 'Right', 940, 740, 'NONE', NULL, NULL),
('sw-35', 'Switch', 'North', 'Left', 900, 660, 'NONE', NULL, NULL),
('sw-36', 'Switch', 'West', 'Left', 900, 780, 'NONE', NULL, NULL),
('st-76', 'Straight', 'South', 'Center', 900, 700, NULL, NULL, NULL),
('st-77', 'Straight', 'West', 'Center', 1460, 860, NULL, NULL, NULL),
('st-80', 'Straight', 'North', 'Center', 900, 340, NULL, NULL, NULL),
('st-82', 'Straight', 'East', 'Center', 860, 860, NULL, NULL, NULL),
('ct-48', 'Curved', 'East', 'Center', 780, 100, NULL, NULL, NULL),
('st-84', 'Straight', 'East', 'Center', 460, 620, NULL, NULL, NULL),
('st-85', 'Straight', 'South', 'Center', 420, 100, NULL, NULL, NULL),
('cs-15', 'CrossSwitch', 'East', 'Right', 340, 60, 'NONE', NULL, NULL),
('sw-37', 'Switch', 'West', 'Right', 340, 20, 'NONE', NULL, NULL),
('st-87', 'Straight', 'North', 'Center', 380, 100, NULL, NULL, NULL),
('st-88', 'Straight', 'North', 'Center', 380, 140, NULL, NULL, NULL),
('sw-38', 'Switch', 'West', 'Right', 300, 60, 'NONE', NULL, NULL),
('sw-39', 'Switch', 'East', 'Left', 260, 60, 'NONE', NULL, NULL),
('st-90', 'Straight', 'South', 'Center', 20, 700, NULL, NULL, NULL),
('se-55', 'Sensor', 'South', 'Center', 300, 100, NULL, NULL, NULL),
('bk-27', 'Block', 'South', 'Center', 300, 180, NULL, NULL, NULL),
('se-56', 'Sensor', 'South', 'Center', 300, 260, NULL, NULL, NULL),
('se-57', 'Sensor', 'South', 'Center', 140, 100, NULL, NULL, NULL),
('bk-28', 'Block', 'South', 'Center', 140, 180, NULL, NULL, NULL),
('st-91', 'Straight', 'South', 'Center', 20, 980, NULL, NULL, NULL),
('se-58', 'Sensor', 'South', 'Center', 140, 260, NULL, NULL, NULL),
('ct-49', 'Curved', 'North', 'Center', 300, 300, NULL, NULL, NULL),
('ct-50', 'Curved', 'West', 'Center', 380, 300, NULL, NULL, NULL),
('st-92', 'Straight', 'West', 'Center', 340, 300, NULL, NULL, NULL),
('st-93', 'Straight', 'North', 'Center', 380, 260, NULL, NULL, NULL),
('st-94', 'Straight', 'North', 'Center', 380, 220, NULL, NULL, NULL),
('st-95', 'Straight', 'North', 'Center', 20, 660, NULL, NULL, NULL),
('st-96', 'Straight', 'North', 'Center', 380, 180, NULL, NULL, NULL),
('sw-40', 'Switch', 'East', 'Left', 220, 20, 'NONE', NULL, NULL),
('sw-42', 'Switch', 'West', 'Left', 220, 60, 'NONE', NULL, NULL),
('sw-44', 'Switch', 'East', 'Left', 140, 60, 'NONE', NULL, NULL),
('st-97', 'Straight', 'East', 'Center', 940, 860, NULL, NULL, NULL),
('st-98', 'Straight', 'East', 'Center', 140, 20, NULL, NULL, NULL),
('sw-46', 'Switch', 'North', 'Left', 1100, 380, NULL, NULL, NULL),
('st-99', 'Straight', 'East', 'Center', 1100, 980, NULL, NULL, NULL),
('st-100', 'Straight', 'East', 'Center', 1460, 980, NULL, NULL, NULL),
('cr-1', 'Crossing', 'South', 'Center', 1180, 100, NULL, NULL, NULL),
('cr-2', 'Crossing', 'South', 'Center', 1140, 100, NULL, NULL, NULL),
('cr-3', 'Crossing', 'South', 'Center', 1060, 820, NULL, NULL, NULL),
('cr-4', 'Crossing', 'South', 'Center', 1020, 820, NULL, NULL, NULL),
('se-59', 'Sensor', 'North', 'Center', 860, 740, NULL, NULL, NULL),
('bk-29', 'Block', 'South', 'Center', 860, 660, NULL, NULL, NULL),
('se-60', 'Sensor', 'North', 'Center', 860, 580, NULL, NULL, NULL),
('ct-52', 'Curved', 'West', 'Center', 1540, 780, NULL, NULL, NULL),
('st-103', 'Straight', 'East', 'Center', 1180, 780, NULL, NULL, NULL),
('st-104', 'Straight', 'West', 'Center', 1460, 780, NULL, NULL, NULL),
('bk-30', 'Block', 'North', 'Center', 1540, 660, NULL, NULL, NULL),
('se-61', 'Sensor', 'North', 'Center', 1540, 580, NULL, NULL, NULL),
('se-62', 'Sensor', 'North', 'Center', 1540, 740, NULL, NULL, NULL),
('st-126', 'Straight', 'South', 'Center', 1540, 900, NULL, NULL, NULL),
('st-127', 'Straight', 'West', 'Center', 1060, 980, NULL, NULL, NULL),
('st-128', 'Straight', 'West', 'Center', 1020, 980, NULL, NULL, NULL),
('st-129', 'Straight', 'West', 'Center', 1380, 860, NULL, NULL, NULL);      
INSERT INTO "jcs"."tiles" VALUES
('st-130', 'Straight', 'West', 'Center', 1420, 860, NULL, NULL, NULL),
('st-131', 'Straight', 'West', 'Center', 1500, 860, NULL, NULL, NULL),
('st-132', 'Straight', 'West', 'Center', 1420, 780, NULL, NULL, NULL),
('bk-31', 'Block', 'East', 'Center', 1300, 780, NULL, NULL, NULL),
('se-63', 'Sensor', 'West', 'Center', 1380, 780, NULL, NULL, NULL),
('se-64', 'Sensor', 'West', 'Center', 1220, 780, NULL, NULL, NULL),
('st-134', 'Straight', 'South', 'Center', 820, 820, NULL, NULL, NULL),
('st-135', 'Straight', 'South', 'Center', 260, 220, NULL, NULL, NULL),
('st-136', 'Straight', 'South', 'Center', 260, 260, NULL, NULL, NULL),
('ct-54', 'Curved', 'North', 'Center', 820, 860, NULL, NULL, NULL),
('ct-55', 'Curved', 'West', 'Center', 260, 300, NULL, NULL, NULL),
('st-137', 'Straight', 'East', 'Center', 1300, 100, NULL, NULL, NULL),
('st-138', 'Straight', 'East', 'Center', 100, 20, NULL, NULL, NULL),
('st-139', 'Straight', 'East', 'Center', 820, 140, NULL, NULL, NULL),
('st-140', 'Straight', 'South', 'Center', 260, 140, NULL, NULL, NULL),
('st-142', 'Straight', 'East', 'Center', 1260, 1020, NULL, NULL, NULL),
('st-144', 'Straight', 'East', 'Center', 820, 100, NULL, NULL, NULL),
('st-146', 'Straight', 'South', 'Center', 580, 340, NULL, NULL, NULL),
('ct-56', 'Curved', 'North', 'Center', 860, 820, NULL, NULL, NULL),
('cr-8', 'Crossing', 'East', 'Center', 780, 180, NULL, NULL, NULL),
('cr-9', 'Crossing', 'East', 'Center', 780, 140, NULL, NULL, NULL),
('cr-10', 'Crossing', 'East', 'Center', 860, 780, NULL, NULL, NULL),
('st-148', 'Straight', 'East', 'Center', 60, 20, NULL, NULL, NULL),
('st-150', 'Straight', 'East', 'Center', 1220, 100, NULL, NULL, NULL),
('st-151', 'Straight', 'East', 'Center', 180, 300, NULL, NULL, NULL),
('st-152', 'Straight', 'East', 'Center', 1060, 100, NULL, NULL, NULL),
('st-155', 'Straight', 'North', 'Center', 860, 540, NULL, NULL, NULL),
('ct-57', 'Curved', 'North', 'Center', 780, 260, NULL, NULL, NULL),
('ct-58', 'Curved', 'South', 'Center', 820, 260, NULL, NULL, NULL),
('sd-14', 'StraightDirection', 'North', 'Center', 1540, 540, NULL, NULL, NULL),
('sd-22', 'StraightDirection', 'East', 'Center', 900, 860, NULL, NULL, NULL),
('sd-24', 'StraightDirection', 'South', 'Center', 780, 220, NULL, NULL, NULL),
('sd-25', 'StraightDirection', 'East', 'Center', 900, 820, NULL, NULL, NULL),
('sd-26', 'StraightDirection', 'West', 'Center', 180, 20, NULL, NULL, NULL),
('st-156', 'Straight', 'South', 'Center', 1340, 420, NULL, NULL, NULL),
('st-157', 'Straight', 'South', 'Center', 1380, 420, NULL, NULL, NULL),
('st-158', 'Straight', 'South', 'Center', 1460, 420, NULL, NULL, NULL),
('st-159', 'Straight', 'South', 'Center', 1420, 420, NULL, NULL, NULL),
('st-160', 'Straight', 'South', 'Center', 1500, 420, NULL, NULL, NULL),
('st-161', 'Straight', 'South', 'Center', 1540, 420, NULL, NULL, NULL),
('sd-27', 'StraightDirection', 'West', 'Center', 540, 140, NULL, NULL, NULL),
('sd-28', 'StraightDirection', 'North', 'Center', 460, 300, NULL, NULL, NULL),
('sd-29', 'StraightDirection', 'South', 'Center', 420, 300, NULL, NULL, NULL),
('sd-31', 'StraightDirection', 'East', 'Center', 1100, 180, NULL, NULL, NULL),
('si-22', 'Signal', 'West', 'Center', 1140, 860, 'HP01', NULL, NULL),
('se-65', 'Sensor', 'West', 'Center', 1180, 860, NULL, NULL, NULL),
('bk-32', 'Block', 'West', 'Center', 1260, 860, NULL, NULL, NULL),
('se-66', 'Sensor', 'West', 'Center', 1340, 860, NULL, NULL, NULL),
('ct-59', 'Curved', 'North', 'Center', 1020, 900, NULL, NULL, NULL),
('ct-60', 'Curved', 'South', 'Center', 1540, 860, NULL, NULL, NULL),
('ct-61', 'Curved', 'North', 'Center', 380, 1060, NULL, NULL, NULL),
('se-67', 'Sensor', 'East', 'Center', 1060, 900, NULL, NULL, NULL),
('bk-33', 'Block', 'East', 'Center', 1140, 900, NULL, NULL, NULL),
('se-68', 'Sensor', 'East', 'Center', 1220, 900, NULL, NULL, NULL),
('si-23', 'Signal', 'East', 'Center', 1260, 900, 'HP01', NULL, NULL),
('ct-62', 'Curved', 'South', 'Center', 1500, 900, NULL, NULL, NULL),
('ct-63', 'Curved', 'West', 'Center', 1500, 980, NULL, NULL, NULL),
('ct-64', 'Curved', 'West', 'Center', 1540, 1020, NULL, NULL, NULL);           
INSERT INTO "jcs"."tiles" VALUES
('bk-34', 'Block', 'East', 'Center', 1380, 900, NULL, NULL, NULL),
('se-69', 'Sensor', 'West', 'Center', 1460, 900, NULL, NULL, NULL),
('se-70', 'Sensor', 'West', 'Center', 1300, 900, NULL, NULL, NULL),
('se-71', 'Sensor', 'West', 'Center', 1340, 980, NULL, NULL, NULL),
('bk-35', 'Block', 'West', 'Center', 1260, 980, NULL, NULL, NULL),
('se-72', 'Sensor', 'West', 'Center', 1180, 980, NULL, NULL, NULL),
('si-24', 'Signal', 'West', 'Center', 1140, 980, 'HP01', NULL, NULL),
('se-73', 'Sensor', 'West', 'Center', 980, 980, NULL, NULL, NULL),
('bk-36', 'Block', 'West', 'Center', 900, 980, NULL, NULL, NULL),
('se-74', 'Sensor', 'West', 'Center', 820, 980, NULL, NULL, NULL),
('sd-32', 'StraightDirection', 'West', 'Center', 780, 980, NULL, NULL, NULL),
('sd-33', 'StraightDirection', 'North', 'Center', 60, 140, NULL, NULL, NULL),
('sd-34', 'StraightDirection', 'East', 'Center', 780, 1020, NULL, NULL, NULL),
('sd-35', 'StraightDirection', 'West', 'Center', 1260, 100, NULL, NULL, NULL),
('si-25', 'Signal', 'East', 'Center', 1500, 1020, 'HP01', NULL, NULL),
('se-75', 'Sensor', 'East', 'Center', 1460, 1020, NULL, NULL, NULL),
('bk-37', 'Block', 'East', 'Center', 1380, 1020, NULL, NULL, NULL),
('se-76', 'Sensor', 'East', 'Center', 1300, 1020, NULL, NULL, NULL),
('se-77', 'Sensor', 'East', 'Center', 1220, 1020, NULL, NULL, NULL),
('bk-38', 'Block', 'East', 'Center', 1140, 1020, NULL, NULL, NULL),
('se-78', 'Sensor', 'East', 'Center', 1060, 1020, NULL, NULL, NULL),
('se-79', 'Sensor', 'East', 'Center', 980, 1020, NULL, NULL, NULL),
('bk-39', 'Block', 'East', 'Center', 900, 1020, NULL, NULL, NULL),
('st-162', 'Straight', 'East', 'Center', 1020, 1020, NULL, NULL, NULL),
('se-80', 'Sensor', 'East', 'Center', 820, 1020, NULL, NULL, NULL),
('sw-47', 'Switch', 'East', 'Left', 740, 980, NULL, NULL, NULL),
('cs-16', 'CrossSwitch', 'East', 'Left', 700, 1020, NULL, NULL, NULL),
('ct-65', 'Curved', 'West', 'Center', 700, 1060, NULL, NULL, NULL),
('si-26', 'Signal', 'East', 'Center', 660, 1020, 'HP01', NULL, NULL),
('si-27', 'Signal', 'East', 'Center', 660, 1060, 'HP01', NULL, NULL),
('st-163', 'Straight', 'East', 'Center', 700, 980, NULL, NULL, NULL),
('st-164', 'Straight', 'East', 'Center', 660, 980, NULL, NULL, NULL),
('se-81', 'Sensor', 'East', 'Center', 620, 980, NULL, NULL, NULL),
('se-82', 'Sensor', 'East', 'Center', 620, 1020, NULL, NULL, NULL),
('se-83', 'Sensor', 'East', 'Center', 620, 1060, NULL, NULL, NULL),
('bk-40', 'Block', 'West', 'Center', 540, 980, NULL, NULL, NULL),
('bk-41', 'Block', 'East', 'Center', 540, 1020, NULL, NULL, NULL),
('bk-42', 'Block', 'East', 'Center', 540, 1060, NULL, NULL, NULL),
('se-84', 'Sensor', 'East', 'Center', 460, 980, NULL, NULL, NULL),
('se-85', 'Sensor', 'East', 'Center', 460, 1020, NULL, NULL, NULL),
('se-86', 'Sensor', 'East', 'Center', 460, 1060, NULL, NULL, NULL),
('si-28', 'Signal', 'West', 'Center', 420, 980, 'HP01', NULL, NULL),
('si-29', 'Signal', 'West', 'Center', 420, 1020, 'HP01', NULL, NULL),
('si-30', 'Signal', 'West', 'Center', 420, 1060, 'HP01', NULL, NULL),
('cs-17', 'CrossSwitch', 'West', 'Right', 380, 1020, NULL, NULL, NULL),
('sw-48', 'Switch', 'West', 'Right', 340, 980, NULL, NULL, NULL),
('st-165', 'Straight', 'West', 'Center', 380, 980, NULL, NULL, NULL),
('sd-36', 'StraightDirection', 'West', 'Center', 300, 980, NULL, NULL, NULL),
('sd-37', 'StraightDirection', 'East', 'Center', 300, 1020, NULL, NULL, NULL),
('se-87', 'Sensor', 'East', 'Center', 260, 980, NULL, NULL, NULL),
('bk-43', 'Block', 'West', 'Center', 180, 980, NULL, NULL, NULL),
('bk-44', 'Block', 'East', 'Center', 180, 1020, NULL, NULL, NULL),
('se-88', 'Sensor', 'West', 'Center', 260, 1020, NULL, NULL, NULL),
('se-90', 'Sensor', 'West', 'Center', 100, 980, NULL, NULL, NULL),
('se-91', 'Sensor', 'West', 'Center', 100, 1020, NULL, NULL, NULL),
('ct-66', 'Curved', 'East', 'Center', 20, 20, NULL, NULL, NULL),
('ct-67', 'Curved', 'North', 'Center', 20, 1020, NULL, NULL, NULL),
('st-166', 'Straight', 'East', 'Center', 1380, 980, NULL, NULL, NULL),
('st-167', 'Straight', 'East', 'Center', 1420, 980, NULL, NULL, NULL);     
INSERT INTO "jcs"."tiles" VALUES
('st-168', 'Straight', 'North', 'Center', 1540, 140, NULL, NULL, NULL),
('st-169', 'Straight', 'North', 'Center', 1500, 140, NULL, NULL, NULL),
('st-170', 'Straight', 'North', 'Center', 1460, 140, NULL, NULL, NULL),
('st-171', 'Straight', 'North', 'Center', 1420, 140, NULL, NULL, NULL),
('st-172', 'Straight', 'North', 'Center', 1380, 140, NULL, NULL, NULL),
('st-173', 'Straight', 'North', 'Center', 1340, 140, NULL, NULL, NULL),
('st-174', 'Straight', 'North', 'Center', 1540, 460, NULL, NULL, NULL),
('st-175', 'Straight', 'North', 'Center', 1340, 460, NULL, NULL, NULL),
('st-176', 'Straight', 'North', 'Center', 1380, 460, NULL, NULL, NULL),
('st-177', 'Straight', 'North', 'Center', 1420, 460, NULL, NULL, NULL),
('st-178', 'Straight', 'North', 'Center', 1460, 460, NULL, NULL, NULL),
('st-179', 'Straight', 'North', 'Center', 1460, 180, NULL, NULL, NULL),
('st-180', 'Straight', 'North', 'Center', 20, 740, NULL, NULL, NULL),
('ct-68', 'Curved', 'East', 'Center', 980, 820, NULL, NULL, NULL),
('ct-69', 'Curved', 'West', 'Center', 980, 860, NULL, NULL, NULL),
('ct-70', 'Curved', 'East', 'Center', 60, 60, NULL, NULL, NULL),
('sw-49', 'Switch', 'South', 'Left', 100, 860, 'NONE', NULL, NULL),
('et-5', 'End', 'East', 'Center', 380, 340, NULL, NULL, NULL),
('et-6', 'End', 'East', 'Center', 380, 380, NULL, NULL, NULL),
('se-92', 'Sensor', 'East', 'Center', 340, 340, NULL, NULL, NULL),
('se-93', 'Sensor', 'East', 'Center', 340, 380, NULL, NULL, NULL),
('bk-45', 'Block', 'East', 'Center', 260, 340, NULL, NULL, NULL),
('bk-46', 'Block', 'East', 'Center', 260, 380, NULL, NULL, NULL),
('se-94', 'Sensor', 'East', 'Center', 180, 340, NULL, NULL, NULL),
('se-95', 'Sensor', 'East', 'Center', 180, 380, NULL, NULL, NULL),
('si-31', 'Signal', 'West', 'Center', 140, 340, 'NONE', NULL, NULL),
('si-32', 'Signal', 'West', 'Center', 140, 380, 'NONE', NULL, NULL),
('sw-50', 'Switch', 'North', 'Left', 100, 340, 'NONE', NULL, NULL),
('ct-71', 'Curved', 'North', 'Center', 100, 380, NULL, NULL, NULL),
('sw-51', 'Switch', 'North', 'Left', 60, 100, 'NONE', NULL, NULL),
('ct-72', 'Curved', 'South', 'Center', 100, 100, NULL, NULL, NULL),
('ct-73', 'Curved', 'North', 'Center', 60, 980, NULL, NULL, NULL),
('st-181', 'Straight', 'East', 'Center', 180, 60, NULL, NULL, NULL),
('st-182', 'Straight', 'East', 'Center', 100, 60, NULL, NULL, NULL),
('st-183', 'Straight', 'South', 'Center', 20, 60, NULL, NULL, NULL),
('st-184', 'Straight', 'South', 'Center', 100, 260, NULL, NULL, NULL),
('st-185', 'Straight', 'South', 'Center', 100, 140, NULL, NULL, NULL),
('st-187', 'Straight', 'South', 'Center', 20, 300, NULL, NULL, NULL),
('se-96', 'Sensor', 'South', 'Center', 20, 100, NULL, NULL, NULL),
('bk-47', 'Block', 'South', 'Center', 20, 180, NULL, NULL, NULL),
('se-97', 'Sensor', 'South', 'Center', 20, 260, NULL, NULL, NULL),
('se-98', 'Sensor', 'North', 'Center', 60, 180, NULL, NULL, NULL),
('bk-48', 'Block', 'North', 'Center', 60, 260, NULL, NULL, NULL),
('se-99', 'Sensor', 'North', 'Center', 60, 340, NULL, NULL, NULL),
('se-100', 'Sensor', 'North', 'Center', 20, 340, NULL, NULL, NULL),
('bk-49', 'Block', 'North', 'Center', 60, 500, NULL, NULL, NULL),
('se-101', 'Sensor', 'North', 'Center', 60, 420, NULL, NULL, NULL),
('se-102', 'Sensor', 'North', 'Center', 60, 580, NULL, NULL, NULL),
('se-103', 'Sensor', 'North', 'Center', 100, 660, NULL, NULL, NULL),
('st-188', 'Straight', 'North', 'Center', 60, 620, NULL, NULL, NULL),
('bk-50', 'Block', 'North', 'Center', 100, 740, NULL, NULL, NULL),
('bk-51', 'Block', 'South', 'Center', 20, 860, NULL, NULL, NULL),
('ct-74', 'Curved', 'East', 'Center', 60, 900, NULL, NULL, NULL),
('se-104', 'Sensor', 'South', 'Center', 100, 820, NULL, NULL, NULL),
('ct-75', 'Curved', 'North', 'Center', 60, 860, NULL, NULL, NULL),
('ct-76', 'Curved', 'West', 'Center', 100, 900, NULL, NULL, NULL),
('se-105', 'Sensor', 'North', 'Center', 60, 820, NULL, NULL, NULL),
('bk-52', 'Block', 'North', 'Center', 60, 740, NULL, NULL, NULL),
('se-106', 'Sensor', 'North', 'Center', 60, 660, NULL, NULL, NULL),
('et-7', 'End', 'North', 'Center', 100, 620, NULL, NULL, NULL);            
INSERT INTO "jcs"."tiles" VALUES
('sd-38', 'StraightDirection', 'North', 'Center', 60, 940, NULL, NULL, NULL),
('sd-39', 'StraightDirection', 'East', 'Center', 60, 1020, NULL, NULL, NULL),
('se-107', 'Sensor', 'South', 'Center', 20, 940, NULL, NULL, NULL),
('se-108', 'Sensor', 'South', 'Center', 20, 780, NULL, NULL, NULL),
('se-109', 'Sensor', 'South', 'Center', 20, 620, NULL, NULL, NULL),
('bk-53', 'Block', 'South', 'Center', 20, 540, NULL, NULL, NULL),
('se-110', 'Sensor', 'South', 'Center', 20, 460, NULL, NULL, NULL),
('st-189', 'Straight', 'South', 'Center', 20, 380, NULL, NULL, NULL),
('st-190', 'Straight', 'South', 'Center', 20, 420, NULL, NULL, NULL),
('st-192', 'Straight', 'East', 'Center', 260, 20, NULL, NULL, NULL),
('st-193', 'Straight', 'East', 'Center', 1180, 740, NULL, NULL, NULL),
('st-194', 'Straight', 'East', 'Center', 900, 20, NULL, NULL, NULL),
('st-195', 'Straight', 'East', 'Center', 940, 20, NULL, NULL, NULL),
('st-196', 'Straight', 'East', 'Center', 1100, 100, NULL, NULL, NULL),
('sd-40', 'StraightDirection', 'West', 'Center', 1100, 140, NULL, NULL, NULL),
('ct-77', 'Curved', 'North', 'Center', 820, 300, NULL, NULL, NULL),
('ct-78', 'Curved', 'South', 'Center', 860, 300, NULL, NULL, NULL),
('ct-79', 'Curved', 'East', 'Center', 1140, 780, NULL, NULL, NULL),
('ct-80', 'Curved', 'West', 'Center', 1140, 820, NULL, NULL, NULL);         
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."tile_pk_idx" ON "jcs"."tiles"("id" NULLS FIRST);     
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."tile_x_y_un_idx" ON "jcs"."tiles"("x" NULLS FIRST, "y" NULLS FIRST); 
CREATE CACHED TABLE "jcs"."stations"(
    "id" CHARACTER VARYING(255) NOT NULL,
    "name" CHARACTER VARYING(255) NOT NULL,
    "min_locs" INTEGER DEFAULT 0 NOT NULL,
    "loc_count" INTEGER DEFAULT 0 NOT NULL,
    "use_fifo" BOOLEAN DEFAULT FALSE NOT NULL
);            
ALTER TABLE "jcs"."stations" ADD CONSTRAINT "jcs"."stat_pk" PRIMARY KEY("id"); 
-- 0 +/- SELECT COUNT(*) FROM jcs.stations;    
CREATE CACHED TABLE "jcs"."station_blocks"(
    "id" CHARACTER VARYING(255) NOT NULL,
    "station_id" CHARACTER VARYING(255) NOT NULL,
    "block_id" CHARACTER VARYING(255) NOT NULL,
    "last_updated" TIMESTAMP
);        
ALTER TABLE "jcs"."station_blocks" ADD CONSTRAINT "jcs"."stbl_pk" PRIMARY KEY("id");           
-- 0 +/- SELECT COUNT(*) FROM jcs.station_blocks;              
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."stbl_stat_blck_un_idx" ON "jcs"."station_blocks"("station_id" NULLS FIRST, "block_id" NULLS FIRST);  
CREATE CACHED TABLE "jcs"."accessories"(
    "id" CHARACTER VARYING(255) NOT NULL,
    "address" INTEGER NOT NULL,
    "name" CHARACTER VARYING(255) NOT NULL,
    "type" CHARACTER VARYING(255) NOT NULL,
    "state" INTEGER,
    "states" INTEGER,
    "switch_time" INTEGER,
    "protocol" CHARACTER VARYING(255),
    "decoder" CHARACTER VARYING(255),
    "accessory_group" CHARACTER VARYING(255),
    "icon" CHARACTER VARYING(255),
    "icon_file" CHARACTER VARYING(255),
    "imported" CHARACTER VARYING(255),
    "command_station_id" CHARACTER VARYING(255) NOT NULL,
    "synchronize" BOOLEAN DEFAULT FALSE NOT NULL,
    "address2" INTEGER
);            
ALTER TABLE "jcs"."accessories" ADD CONSTRAINT "jcs"."acce_pk" PRIMARY KEY("id");              
-- 0 +/- SELECT COUNT(*) FROM jcs.accessories; 
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."acce_address_un_idx" ON "jcs"."accessories"("address" NULLS FIRST, "protocol" NULLS FIRST, "command_station_id" NULLS FIRST);        
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."acce_pk_idx" ON "jcs"."accessories"("id" NULLS FIRST);               
CREATE CACHED TABLE "jcs"."blocks"(
    "id" CHARACTER VARYING(255) NOT NULL,
    "tile_id" CHARACTER VARYING(255) NOT NULL,
    "description" CHARACTER VARYING(255),
    "plus_sensor_id" INTEGER,
    "min_sensor_id" INTEGER,
    "plus_signal_id" CHARACTER VARYING(255),
    "min_signal_id" CHARACTER VARYING(255),
    "locomotive_id" BIGINT,
    "allow_non_commuter_only" BOOLEAN DEFAULT FALSE NOT NULL,
    "status" CHARACTER VARYING(255),
    "incoming_suffix" CHARACTER VARYING(255),
    "min_wait_time" INTEGER DEFAULT 10 NOT NULL,
    "max_wait_time" INTEGER,
    "random_wait" BOOLEAN DEFAULT FALSE NOT NULL,
    "always_stop" BOOLEAN DEFAULT FALSE NOT NULL,
    "allow_commuter_only" BOOLEAN DEFAULT FALSE NOT NULL,
    "logical_direction" CHARACTER VARYING(255),
    "allow_direction_change" BOOLEAN DEFAULT TRUE NOT NULL
);              
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."bloc_pk" PRIMARY KEY("id");   
-- 53 +/- SELECT COUNT(*) FROM jcs.blocks;     
INSERT INTO "jcs"."blocks" VALUES
('bk-1', 'bk-1', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-2', 'bk-2', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-3', 'bk-3', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-4', 'bk-4', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-5', 'bk-5', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-6', 'bk-6', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-7', 'bk-7', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-8', 'bk-8', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-9', 'bk-9', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-10', 'bk-10', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-11', 'bk-11', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-12', 'bk-12', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-13', 'bk-13', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-14', 'bk-14', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-15', 'bk-15', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-16', 'bk-16', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-17', 'bk-17', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-18', 'bk-18', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-19', 'bk-19', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-20', 'bk-20', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-21', 'bk-21', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-22', 'bk-22', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-23', 'bk-23', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-24', 'bk-24', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-25', 'bk-25', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-26', 'bk-26', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-27', 'bk-27', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-28', 'bk-28', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-29', 'bk-29', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-30', 'bk-30', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-31', 'bk-31', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-32', 'bk-32', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-33', 'bk-33', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-34', 'bk-34', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-35', 'bk-35', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE);        
INSERT INTO "jcs"."blocks" VALUES
('bk-36', 'bk-36', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-37', 'bk-37', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-38', 'bk-38', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-39', 'bk-39', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-40', 'bk-40', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-41', 'bk-41', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-42', 'bk-42', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-43', 'bk-43', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-44', 'bk-44', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-45', 'bk-45', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-46', 'bk-46', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-47', 'bk-47', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-48', 'bk-48', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-49', 'bk-49', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-50', 'bk-50', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-51', 'bk-51', '', NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-52', 'bk-52', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE),
('bk-53', 'bk-53', NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 'Free', NULL, 10, NULL, FALSE, TRUE, FALSE, NULL, FALSE);
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."bloc_pk_idx" ON "jcs"."blocks"("id" NULLS FIRST);    
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."bloc_tile_idx" ON "jcs"."blocks"("tile_id" NULLS FIRST);             
CREATE CACHED TABLE "jcs"."sensors"(
    "id" INTEGER NOT NULL,
    "name" CHARACTER VARYING(255) NOT NULL,
    "device_id" INTEGER,
    "contact_id" INTEGER,
    "status" INTEGER,
    "previous_status" INTEGER,
    "millis" INTEGER,
    "last_updated" DATE,
    "node_id" INTEGER,
    "bus_nr" INTEGER DEFAULT 0 NOT NULL,
    "command_station_id" CHARACTER VARYING(255) NOT NULL
); 
ALTER TABLE "jcs"."sensors" ADD CONSTRAINT "jcs"."sens_pk" PRIMARY KEY("id");  
-- 0 +/- SELECT COUNT(*) FROM jcs.sensors;     
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."sens_pk_idx" ON "jcs"."sensors"("id" NULLS FIRST);   
CREATE CACHED TABLE "jcs"."locomotive_functions"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "locomotive_id" BIGINT NOT NULL,
    "f_number" INTEGER NOT NULL,
    "f_type" INTEGER NOT NULL,
    "f_value" INTEGER,
    "f_icon" CHARACTER VARYING(255),
    "momentary" BOOLEAN DEFAULT FALSE NOT NULL
);  
ALTER TABLE "jcs"."locomotive_functions" ADD CONSTRAINT "jcs"."lofu_pk" PRIMARY KEY("id");     
-- 0 +/- SELECT COUNT(*) FROM jcs.locomotive_functions;        
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."lofu_pk_idx" ON "jcs"."locomotive_functions"("id" NULLS FIRST);      
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."lofu_loid_fnum_un_idx" ON "jcs"."locomotive_functions"("locomotive_id" NULLS FIRST, "f_number" NULLS FIRST);         
CREATE CACHED TABLE "jcs"."locomotives"(
    "id" BIGINT NOT NULL,
    "name" CHARACTER VARYING(255) NOT NULL,
    "uid" BIGINT,
    "address" INTEGER NOT NULL,
    "icon" CHARACTER VARYING(255),
    "decoder_type" CHARACTER VARYING(255) NOT NULL,
    "tacho_max" INTEGER,
    "v_min" INTEGER,
    "velocity" INTEGER,
    "synchronize" BOOLEAN DEFAULT FALSE NOT NULL,
    "imported" CHARACTER VARYING(255),
    "commuter" BOOLEAN DEFAULT FALSE NOT NULL,
    "show" BOOLEAN DEFAULT TRUE NOT NULL,
    "command_station_id" CHARACTER VARYING(255) NOT NULL,
    "dispatcher_direction" CHARACTER VARYING(255),
    "locomotive_direction" CHARACTER VARYING(255),
    "speed_1" INTEGER,
    "speed_2" INTEGER,
    "speed_3" INTEGER,
    "speed_4" INTEGER
);  
ALTER TABLE "jcs"."locomotives" ADD CONSTRAINT "jcs"."loco_pk" PRIMARY KEY("id");              
-- 0 +/- SELECT COUNT(*) FROM jcs.locomotives; 
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."loco_pk_idx" ON "jcs"."locomotives"("id" NULLS FIRST);               
CREATE CACHED TABLE "jcs"."command_stations"(
    "id" CHARACTER VARYING(255) NOT NULL,
    "description" CHARACTER VARYING(255) NOT NULL,
    "short_name" CHARACTER VARYING(255) NOT NULL,
    "class_name" CHARACTER VARYING(255) NOT NULL,
    "connect_via" CHARACTER VARYING(255) NOT NULL,
    "serial_port" CHARACTER VARYING(255),
    "ip_address" CHARACTER VARYING(255),
    "network_port" INTEGER,
    "ip_auto_conf" BOOLEAN DEFAULT FALSE NOT NULL,
    "supports_decoder_control" BOOLEAN DEFAULT TRUE NOT NULL,
    "supports_accessory_control" BOOLEAN DEFAULT TRUE NOT NULL,
    "supports_feedback" BOOLEAN DEFAULT TRUE NOT NULL,
    "supports_loco_synch" BOOLEAN DEFAULT FALSE NOT NULL,
    "supports_accessory_synch" BOOLEAN DEFAULT FALSE NOT NULL,
    "supports_loco_image_synch" BOOLEAN DEFAULT FALSE NOT NULL,
    "supports_loco_function_synch" BOOLEAN DEFAULT FALSE NOT NULL,
    "protocols" CHARACTER VARYING(255) DEFAULT 'DCC' NOT NULL,
    "default_cs" BOOLEAN DEFAULT FALSE NOT NULL,
    "enabled" BOOLEAN DEFAULT FALSE NOT NULL,
    "last_used_serial" CHARACTER VARYING(255),
    "sup_conn_types" CHARACTER VARYING(255) NOT NULL,
    "feedback_module_id" CHARACTER VARYING(255),
    "feedback_bus_count" INTEGER,
    "feedback_bus_0_module_count" INTEGER,
    "feedback_bus_1_module_count" INTEGER,
    "feedback_bus_2_module_count" INTEGER,
    "feedback_bus_3_module_count" INTEGER,
    "virtual" BOOLEAN DEFAULT FALSE NOT NULL
);         
ALTER TABLE "jcs"."command_stations" ADD CONSTRAINT "jcs"."command_station_pk" PRIMARY KEY("id");              
-- 5 +/- SELECT COUNT(*) FROM jcs.command_stations;            
INSERT INTO "jcs"."command_stations" VALUES
('marklin.cs', 'Marklin Central Station 2/3', 'CS', 'jcs.commandStation.marklin.cs.MarklinCentralStationImpl', 'NETWORK', NULL, NULL, 15731, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'DCC,MFX,MM', FALSE, TRUE, NULL, 'NETWORK', NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
('dcc-ex', 'DCC-EX', 'dcc-ex', 'jcs.commandStation.dccex.DccExCommandStationImpl', 'NETWORK', NULL, NULL, 2560, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'DCC', FALSE, FALSE, NULL, 'NETWORK,SERIAL', NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
('hsi-s88', 'HSI S88', 'HSI', 'jcs.commandStation.hsis88.HSIImpl', 'SERIAL', NULL, NULL, 0, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, '', FALSE, TRUE, NULL, 'SERIAL', '0', 1, 6, 0, 0, 0, FALSE),
('virtual', 'Virtual CS', 'VIR', 'jcs.commandStation.virtual.VirtualCommandStationImpl', 'NETWORK', NULL, '127.0.0.1', 0, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 'dcc', TRUE, TRUE, '1', 'NETWORK', '0', 1, 1, 0, 0, 0, TRUE),
('esu-ecos', 'ESU ECoS', 'ECoS', 'jcs.commandStation.esu.ecos.EsuEcosCommandStationImpl', 'NETWORK', NULL, NULL, 15471, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'DCC,MFX,MM', TRUE, TRUE, '1', 'NETWORK', '0', 0, 0, 0, 0, 0, FALSE);     
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."command_station_pk_idx" ON "jcs"."command_stations"("id" NULLS FIRST);               
CREATE CACHED TABLE "jcs"."routes"(
    "id" CHARACTER VARYING(255) NOT NULL,
    "from_tile_id" CHARACTER VARYING(255) NOT NULL,
    "from_suffix" CHARACTER VARYING(255) NOT NULL,
    "to_tile_id" CHARACTER VARYING(255) NOT NULL,
    "to_suffix" CHARACTER VARYING(255) NOT NULL,
    "route_color" CHARACTER VARYING(255),
    "locked" BOOLEAN DEFAULT FALSE NOT NULL,
    "status" CHARACTER VARYING(255),
    "departure_signal_value" CHARACTER VARYING(255)
);     
ALTER TABLE "jcs"."routes" ADD CONSTRAINT "jcs"."rout_pk" PRIMARY KEY("id");   
-- 0 +/- SELECT COUNT(*) FROM jcs.routes;      
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."rout_pk_idx" ON "jcs"."routes"("id" NULLS FIRST);    
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."rout_from_to_un_idx" ON "jcs"."routes"("from_tile_id" NULLS FIRST, "from_suffix" NULLS FIRST, "to_tile_id" NULLS FIRST, "to_suffix" NULLS FIRST);    
CREATE CACHED TABLE "jcs"."route_elements"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "route_id" CHARACTER VARYING(255) NOT NULL,
    "node_id" CHARACTER VARYING(255) NOT NULL,
    "tile_id" CHARACTER VARYING(255) NOT NULL,
    "accessory_value" CHARACTER VARYING(255),
    "order_seq" INTEGER DEFAULT 0 NOT NULL,
    "incoming_side" CHARACTER VARYING(255)
);     
ALTER TABLE "jcs"."route_elements" ADD CONSTRAINT "jcs"."roel_pk" PRIMARY KEY("id");           
-- 0 +/- SELECT COUNT(*) FROM jcs.route_elements;              
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."roel_pk_idx" ON "jcs"."route_elements"("id" NULLS FIRST);            
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."roel_rout_node_tile_un_idx" ON "jcs"."route_elements"("route_id" NULLS FIRST, "node_id" NULLS FIRST, "tile_id" NULLS FIRST);         
CREATE CACHED TABLE "jcs"."jcs_properties"(
    "p_key" CHARACTER VARYING(255) NOT NULL,
    "p_value" CHARACTER VARYING(255) NOT NULL
);      
ALTER TABLE "jcs"."jcs_properties" ADD CONSTRAINT "jcs"."prop_pk" PRIMARY KEY("p_key");        
-- 3 +/- SELECT COUNT(*) FROM jcs.jcs_properties;              
INSERT INTO "jcs"."jcs_properties" VALUES
('jcs.version', '1.0.0'),
('jcs.db.version', '1.0.0'),
('default.switchtime', '500');
CREATE UNIQUE NULLS DISTINCT INDEX "jcs"."prop_pk_idx" ON "jcs"."jcs_properties"("p_key" NULLS FIRST);         
CREATE CACHED TABLE "jcs"."jcs_version"(
    "db_version" CHARACTER VARYING(255) NOT NULL,
    "app_version" CHARACTER VARYING(255) NOT NULL
);
-- 1 +/- SELECT COUNT(*) FROM jcs.jcs_version; 
INSERT INTO "jcs"."jcs_version" VALUES
('0.0.4', '0.0.4');     
ALTER TABLE "jcs"."tiles" ADD CONSTRAINT "jcs"."tile_acce_sens_arc_ck" CHECK((("accessory_id" IS NOT NULL)
    AND ("sensor_id" IS NULL))
    OR (("accessory_id" IS NULL)
    AND (("sensor_id" IS NOT NULL)
    OR ("sensor_id" IS NULL)))) NOCHECK;         
ALTER TABLE "jcs"."sensors" ADD CONSTRAINT "jcs"."sens_deid_coid_un" UNIQUE NULLS DISTINCT ("device_id", "contact_id", "bus_nr", "command_station_id");        
ALTER TABLE "jcs"."route_elements" ADD CONSTRAINT "jcs"."roel_rout_node_tile_un" UNIQUE NULLS DISTINCT ("route_id", "node_id", "tile_id");     
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."bloc_tile_un" UNIQUE NULLS DISTINCT ("tile_id");              
ALTER TABLE "jcs"."accessories" ADD CONSTRAINT "jcs"."acce_address_un" UNIQUE NULLS DISTINCT ("protocol", "address", "command_station_id");    
ALTER TABLE "jcs"."tiles" ADD CONSTRAINT "jcs"."tile_x_y_un" UNIQUE NULLS DISTINCT ("x", "y"); 
ALTER TABLE "jcs"."locomotive_functions" ADD CONSTRAINT "jcs"."lofu_loid_fnum_un" UNIQUE NULLS DISTINCT ("locomotive_id", "f_number");         
ALTER TABLE "jcs"."routes" ADD CONSTRAINT "jcs"."rout_from_to_un" UNIQUE NULLS DISTINCT ("from_tile_id", "from_suffix", "to_tile_id", "to_suffix");            
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."blck_sens_plus_fk" FOREIGN KEY("plus_sensor_id") REFERENCES "jcs"."sensors"("id") NOCHECK;    
ALTER TABLE "jcs"."routes" ADD CONSTRAINT "jcs"."rout_tile_to_fk" FOREIGN KEY("to_tile_id") REFERENCES "jcs"."tiles"("id") NOCHECK;            
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."blck_tile_fk" FOREIGN KEY("tile_id") REFERENCES "jcs"."tiles"("id") NOCHECK;  
ALTER TABLE "jcs"."accessories" ADD CONSTRAINT "jcs"."acce_cost_fk" FOREIGN KEY("command_station_id") REFERENCES "jcs"."command_stations"("id") NOCHECK;       
ALTER TABLE "jcs"."locomotive_functions" ADD CONSTRAINT "jcs"."lofu_loco_fk" FOREIGN KEY("locomotive_id") REFERENCES "jcs"."locomotives"("id") NOCHECK;        
ALTER TABLE "jcs"."station_blocks" ADD CONSTRAINT "jcs"."blck_stbl_fk" FOREIGN KEY("block_id") REFERENCES "jcs"."blocks"("id") NOCHECK;        
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."blck_acce_sig_plus_fk" FOREIGN KEY("plus_signal_id") REFERENCES "jcs"."accessories"("id") NOCHECK;            
ALTER TABLE "jcs"."route_elements" ADD CONSTRAINT "jcs"."roel_tile_fk" FOREIGN KEY("tile_id") REFERENCES "jcs"."tiles"("id") NOCHECK;          
ALTER TABLE "jcs"."routes" ADD CONSTRAINT "jcs"."rout_tile_from_fk" FOREIGN KEY("from_tile_id") REFERENCES "jcs"."tiles"("id") NOCHECK;        
ALTER TABLE "jcs"."locomotives" ADD CONSTRAINT "jcs"."loco_cost_fk" FOREIGN KEY("command_station_id") REFERENCES "jcs"."command_stations"("id") NOCHECK;       
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."blck_sens_min_fk" FOREIGN KEY("min_sensor_id") REFERENCES "jcs"."sensors"("id") NOCHECK;      
ALTER TABLE "jcs"."station_blocks" ADD CONSTRAINT "jcs"."stat_stbl_fk" FOREIGN KEY("station_id") REFERENCES "jcs"."stations"("id") NOCHECK;    
ALTER TABLE "jcs"."route_elements" ADD CONSTRAINT "jcs"."roel_rout_fk" FOREIGN KEY("route_id") REFERENCES "jcs"."routes"("id") NOCHECK;        
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."blck_acce_sig_min_fk" FOREIGN KEY("min_signal_id") REFERENCES "jcs"."accessories"("id") NOCHECK;              
ALTER TABLE "jcs"."blocks" ADD CONSTRAINT "jcs"."blck_loco_fk" FOREIGN KEY("locomotive_id") REFERENCES "jcs"."locomotives"("id") NOCHECK;      
ALTER TABLE "jcs"."tiles" ADD CONSTRAINT "jcs"."tile_acc_fk" FOREIGN KEY("accessory_id") REFERENCES "jcs"."accessories"("id") NOCHECK;         
ALTER TABLE "jcs"."tiles" ADD CONSTRAINT "jcs"."tile_sens_fk" FOREIGN KEY("sensor_id") REFERENCES "jcs"."sensors"("id") NOCHECK;               
