/*
 * Copyright 2025 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.layout.tiles;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jcs.entities.AccessoryBean.AccessoryValue;
import jcs.entities.TileBean;
import org.tinylog.Logger;

public class CrossTileTester extends javax.swing.JFrame {

  private Tile crossEastR;
  private Tile crossSouthR;
  private Tile crossWestR;
  private Tile crossNorthR;

  private Tile crossEastL;
  private Tile crossSouthL;
  private Tile crossWestL;
  private Tile crossNorthL;

  /**
   * Creates new form TileTester
   *
   * @param title
   */
  public CrossTileTester(String title) {
    super(title);
    initComponents();

    createTiles();

    this.setVisible(true);
  }

  private void createTiles() {

    crossEastR = new Cross(TileBean.Orientation.EAST, TileBean.Direction.RIGHT, 60, 60);
    crossEastR.setId("eastR");
    crossEastR.setTrackRouteColor(Color.MAGENTA);
    crossEastR.setRouteValue(AccessoryValue.GREEN);

    crossSouthR = new Cross(TileBean.Orientation.SOUTH, TileBean.Direction.RIGHT, 180, 60);
    crossSouthR.setId("southR");
    crossSouthR.setTrackRouteColor(Color.YELLOW);
    crossSouthR.setRouteValue(AccessoryValue.RED);

    crossWestR = new Cross(TileBean.Orientation.WEST, TileBean.Direction.RIGHT, 380, 60);
    crossWestR.setId("westR");
    crossWestR.setTrackRouteColor(Color.CYAN);

    crossNorthR = new Cross(TileBean.Orientation.NORTH, TileBean.Direction.RIGHT, 180, 220);
    crossNorthR.setId("northR");
    crossNorthR.setTrackRouteColor(Color.blue);
    crossNorthR.setRouteValue(AccessoryValue.GREEN);

    //
    crossEastL = new Cross(TileBean.Orientation.EAST, TileBean.Direction.LEFT, 60, 140);
    crossEastL.setId("eastR");
    crossEastL.setTrackRouteColor(Color.MAGENTA);
    crossEastL.setRouteValue(AccessoryValue.GREEN);

    crossSouthL = new Cross(TileBean.Orientation.SOUTH, TileBean.Direction.LEFT, 260, 60);
    crossSouthL.setId("southR");
    crossSouthL.setTrackRouteColor(Color.YELLOW);
    crossSouthL.setRouteValue(AccessoryValue.RED);

    crossWestL = new Cross(TileBean.Orientation.WEST, TileBean.Direction.LEFT, 380, 140);
    crossWestL.setId("westR");
    crossWestL.setTrackRouteColor(Color.CYAN);

    crossNorthL = new Cross(TileBean.Orientation.NORTH, TileBean.Direction.LEFT, 260, 220);
    crossNorthL.setId("northR");
    crossNorthL.setTrackRouteColor(Color.blue);
    crossNorthL.setRouteValue(AccessoryValue.GREEN);

    dotGridCanvas.add(crossEastR);
    dotGridCanvas.add(crossSouthR);
    dotGridCanvas.add(crossWestR);
    dotGridCanvas.add(crossNorthR);

    dotGridCanvas.add(crossEastL);
    dotGridCanvas.add(crossSouthL);
    dotGridCanvas.add(crossWestL);
    dotGridCanvas.add(crossNorthL);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    toolbarPanel = new javax.swing.JPanel();
    toolBar = new javax.swing.JToolBar();
    eastTileBtn = new javax.swing.JToggleButton();
    southTileBtn = new javax.swing.JToggleButton();
    westTileBtn = new javax.swing.JToggleButton();
    northTileBtn = new javax.swing.JToggleButton();
    selectSouthTileBtn = new javax.swing.JToggleButton();
    drawCenterBtn = new javax.swing.JToggleButton();
    greenRedBtn = new javax.swing.JToggleButton();
    dotGridCanvas = new jcs.ui.layout.tiles.DotGridCanvas();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
    flowLayout1.setAlignOnBaseline(true);
    toolbarPanel.setLayout(flowLayout1);

    toolBar.setRollover(true);

    eastTileBtn.setText("East");
    eastTileBtn.setFocusable(false);
    eastTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    eastTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    eastTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        eastTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(eastTileBtn);

    southTileBtn.setText("South");
    southTileBtn.setFocusable(false);
    southTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    southTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    southTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        southTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(southTileBtn);

    westTileBtn.setText("West");
    westTileBtn.setFocusable(false);
    westTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    westTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    westTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        westTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(westTileBtn);

    northTileBtn.setText("North");
    northTileBtn.setFocusable(false);
    northTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    northTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    northTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        northTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(northTileBtn);

    selectSouthTileBtn.setText("Select Tile");
    selectSouthTileBtn.setFocusable(false);
    selectSouthTileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    selectSouthTileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    selectSouthTileBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectSouthTileBtnActionPerformed(evt);
      }
    });
    toolBar.add(selectSouthTileBtn);

    drawCenterBtn.setText("show Center");
    drawCenterBtn.setFocusable(false);
    drawCenterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    drawCenterBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    drawCenterBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        drawCenterBtnActionPerformed(evt);
      }
    });
    toolBar.add(drawCenterBtn);

    greenRedBtn.setText("Red");
    greenRedBtn.setFocusable(false);
    greenRedBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    greenRedBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    greenRedBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        greenRedBtnActionPerformed(evt);
      }
    });
    toolBar.add(greenRedBtn);

    toolbarPanel.add(toolBar);

    getContentPane().add(toolbarPanel, java.awt.BorderLayout.NORTH);

    dotGridCanvas.setPreferredSize(new java.awt.Dimension(480, 320));
    getContentPane().add(dotGridCanvas, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void northTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northTileBtnActionPerformed
    Logger.trace(crossNorthR.id + "...");
    this.crossNorthR.setShowRoute(this.northTileBtn.isSelected());
    this.crossNorthL.setShowRoute(this.northTileBtn.isSelected());
  }//GEN-LAST:event_northTileBtnActionPerformed

  private void eastTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eastTileBtnActionPerformed
    this.crossEastR.setShowRoute(this.eastTileBtn.isSelected());
    this.crossEastL.setShowRoute(this.eastTileBtn.isSelected());
  }//GEN-LAST:event_eastTileBtnActionPerformed

  private void westTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westTileBtnActionPerformed
    this.crossWestR.setShowRoute(this.westTileBtn.isSelected());
    this.crossWestL.setShowRoute(this.westTileBtn.isSelected());
  }//GEN-LAST:event_westTileBtnActionPerformed

  private void southTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_southTileBtnActionPerformed
    this.crossSouthR.setShowRoute(this.southTileBtn.isSelected());
    this.crossSouthL.setShowRoute(this.southTileBtn.isSelected());
  }//GEN-LAST:event_southTileBtnActionPerformed

  private void selectSouthTileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSouthTileBtnActionPerformed
    this.crossSouthR.setSelected(this.selectSouthTileBtn.isSelected());
    this.crossSouthL.setSelected(this.selectSouthTileBtn.isSelected());
  }//GEN-LAST:event_selectSouthTileBtnActionPerformed

  private void drawCenterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawCenterBtnActionPerformed
    this.crossEastR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossEastL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSouthR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossSouthL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossWestR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossWestL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossNorthR.setDrawCenterPoint(this.drawCenterBtn.isSelected());
    this.crossNorthL.setDrawCenterPoint(this.drawCenterBtn.isSelected());
  }//GEN-LAST:event_drawCenterBtnActionPerformed

  private void greenRedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenRedBtnActionPerformed
    boolean red = this.greenRedBtn.isSelected();
    if (red) {
      this.greenRedBtn.setText("Green");
      if (this.westTileBtn.isSelected()) {
        this.crossWestR.setAccessoryValue(AccessoryValue.OFF);
        this.crossWestR.setRouteValue(AccessoryValue.GREEN);

        this.crossWestL.setAccessoryValue(AccessoryValue.OFF);
        this.crossWestL.setRouteValue(AccessoryValue.GREEN);
      } else {
        this.crossWestR.setAccessoryValue(AccessoryValue.GREEN);
        this.crossWestL.setAccessoryValue(AccessoryValue.GREEN);
      }
    } else {
      this.greenRedBtn.setText("Red");
      if (this.westTileBtn.isSelected()) {
        this.crossWestR.setAccessoryValue(AccessoryValue.OFF);
        this.crossWestR.setRouteValue(AccessoryValue.RED);

        this.crossWestL.setAccessoryValue(AccessoryValue.OFF);
        this.crossWestL.setRouteValue(AccessoryValue.RED);
      } else {
        this.crossWestR.setAccessoryValue(AccessoryValue.RED);
        this.crossWestL.setAccessoryValue(AccessoryValue.RED);
      }
    }
  }//GEN-LAST:event_greenRedBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
      CrossTileTester.setDefaultLookAndFeelDecorated(true);

    } catch (ClassNotFoundException
            | InstantiationException
            | IllegalAccessException
            | UnsupportedLookAndFeelException ex) {
      Logger.error(ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      CrossTileTester app = new CrossTileTester("Switch Tile Tester");
      app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
      app.setLocation(dim.width / 2 - app.getSize().width / 2, dim.height / 2 - app.getSize().height / 2);
      app.pack();
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private jcs.ui.layout.tiles.DotGridCanvas dotGridCanvas;
  private javax.swing.JToggleButton drawCenterBtn;
  private javax.swing.JToggleButton eastTileBtn;
  private javax.swing.JToggleButton greenRedBtn;
  private javax.swing.JToggleButton northTileBtn;
  private javax.swing.JToggleButton selectSouthTileBtn;
  private javax.swing.JToggleButton southTileBtn;
  private javax.swing.JToolBar toolBar;
  private javax.swing.JPanel toolbarPanel;
  private javax.swing.JToggleButton westTileBtn;
  // End of variables declaration//GEN-END:variables
}
