/*
 * Copyright (C) 2019 Frans Jacobs <frans.jacobs@gmail.com>.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package lan.wervel.jcs.ui;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import lan.wervel.jcs.ui.widgets.LocoPanel;
import org.tinylog.Logger;

/**
 *
 * @author Frans Jacobs <frans.jacobs@gmail.com>
 */
public class DisplayLayoutPanel extends JPanel {

    /**
     * Creates new form SignalTurnoutSwitchPanel
     */
    public DisplayLayoutPanel() {
        initComponents();
    }

    public void loadLayout() {
        displayCanvas.loadLayout();
    }

    public void refreshPanel() {
        this.locoPanel1.refreshPanel();
        this.locoPanel2.refreshPanel();
        this.locoPanel3.refreshPanel();
        this.locoPanel4.refreshPanel();
        this.locoPanel5.refreshPanel();
        this.locoPanel6.refreshPanel();
        this.locoPanel7.refreshPanel();
        this.locoPanel8.refreshPanel();
        this.locoPanel8.refreshPanel();
        this.locoPanel10.refreshPanel();
        this.locoPanel11.refreshPanel();
        this.locoPanel12.refreshPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    layoutSP = new javax.swing.JScrollPane();
    layoutPanel = new javax.swing.JPanel();
    displayCanvas = new lan.wervel.jcs.ui.layout.DisplayCanvas();
    locosTP = new javax.swing.JTabbedPane();
    locosPanel1 = new javax.swing.JPanel();
    locoPanel1 = new LocoPanel(1);
    locoPanel2 = new LocoPanel(2);
    locoPanel3 = new LocoPanel(3);
    locoPanel4 = new LocoPanel(4);
    locosPanel2 = new javax.swing.JPanel();
    locoPanel5 = new LocoPanel(5);
    locoPanel6 = new LocoPanel(6);
    locoPanel7 = new LocoPanel(7);
    locoPanel8 = new LocoPanel(8);
    locosPanel3 = new javax.swing.JPanel();
    locoPanel9 = new LocoPanel(9);
    locoPanel10 = new LocoPanel(10);
    locoPanel11 = new LocoPanel(11);
    locoPanel12 = new LocoPanel(12);

    setMinimumSize(new java.awt.Dimension(1220, 840));
    setPreferredSize(new java.awt.Dimension(1220, 840));
    setLayout(new java.awt.BorderLayout());

    layoutSP.setMinimumSize(new java.awt.Dimension(1220, 560));
    layoutSP.setPreferredSize(new java.awt.Dimension(1220, 560));
    layoutSP.setViewportView(displayCanvas);

    layoutPanel.setLayout(new java.awt.GridBagLayout());

    displayCanvas.setPreferredSize(new java.awt.Dimension(1080, 520));

    javax.swing.GroupLayout displayCanvasLayout = new javax.swing.GroupLayout(displayCanvas);
    displayCanvas.setLayout(displayCanvasLayout);
    displayCanvasLayout.setHorizontalGroup(
      displayCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1216, Short.MAX_VALUE)
    );
    displayCanvasLayout.setVerticalGroup(
      displayCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 536, Short.MAX_VALUE)
    );

    layoutPanel.add(displayCanvas, new java.awt.GridBagConstraints());
    displayCanvas.getAccessibleContext().setAccessibleName("");

    layoutSP.setViewportView(layoutPanel);

    add(layoutSP, java.awt.BorderLayout.CENTER);

    locosTP.setPreferredSize(new java.awt.Dimension(1241, 300));

    locosPanel1.setMinimumSize(new java.awt.Dimension(1220, 230));
    locosPanel1.setPreferredSize(new java.awt.Dimension(1220, 260));
    locosPanel1.setLayout(new javax.swing.BoxLayout(locosPanel1, javax.swing.BoxLayout.X_AXIS));
    locosPanel1.add(locoPanel1);
    locosPanel1.add(locoPanel2);
    locosPanel1.add(locoPanel3);
    locosPanel1.add(locoPanel4);

    locosTP.addTab("1 - 4", locosPanel1);

    locosPanel2.setMinimumSize(new java.awt.Dimension(1220, 230));
    locosPanel2.setPreferredSize(new java.awt.Dimension(1220, 260));
    locosPanel2.setLayout(new javax.swing.BoxLayout(locosPanel2, javax.swing.BoxLayout.X_AXIS));
    locosPanel2.add(locoPanel5);
    locosPanel2.add(locoPanel6);
    locosPanel2.add(locoPanel7);
    locosPanel2.add(locoPanel8);

    locosTP.addTab("5 - 8", locosPanel2);

    locosPanel3.setMinimumSize(new java.awt.Dimension(1220, 230));
    locosPanel3.setPreferredSize(new java.awt.Dimension(1220, 260));
    locosPanel3.setLayout(new javax.swing.BoxLayout(locosPanel3, javax.swing.BoxLayout.X_AXIS));
    locosPanel3.add(locoPanel9);
    locosPanel3.add(locoPanel10);
    locosPanel3.add(locoPanel11);
    locosPanel3.add(locoPanel12);

    locosTP.addTab("9 - 12", locosPanel3);

    add(locosTP, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.error(ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            JFrame f = new JFrame("displayLayoutPanel Tester");
            DisplayLayoutPanel displayLayoutPanel = new DisplayLayoutPanel();
            f.add(displayLayoutPanel);

            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            f.pack();
            f.setVisible(true);
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private lan.wervel.jcs.ui.layout.DisplayCanvas displayCanvas;
  private javax.swing.JPanel layoutPanel;
  private javax.swing.JScrollPane layoutSP;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel1;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel10;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel11;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel12;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel2;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel3;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel4;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel5;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel6;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel7;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel8;
  private lan.wervel.jcs.ui.widgets.LocoPanel locoPanel9;
  private javax.swing.JPanel locosPanel1;
  private javax.swing.JPanel locosPanel2;
  private javax.swing.JPanel locosPanel3;
  private javax.swing.JTabbedPane locosTP;
  // End of variables declaration//GEN-END:variables

}
