/*
 * Copyright 2026 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.widgets;

import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import jcs.ui.util.JcsLogDocumentWriter;

/**
 *
 */
public class MessagesPanel extends javax.swing.JPanel {

  private JcsLogDocumentWriter logDocumentWriter;

  /**
   * Creates new form MessagesPanel
   */
  public MessagesPanel() {
    initComponents();
    postInitComponents();
  }

  private void postInitComponents() {
    logDocumentWriter = JcsLogDocumentWriter.getInstance();

    if (logDocumentWriter != null) {

      railControlTA.setDocument(logDocumentWriter);

      railControlTA.getDocument().addDocumentListener(new DocumentListener() {

        @Override
        public void insertUpdate(DocumentEvent e) {
          SwingUtilities.invokeLater(()
                  -> railControlTA.setCaretPosition(0)
          );
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
        }

      });
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    railControllerLbl = new javax.swing.JLabel();
    systemLbl = new javax.swing.JLabel();
    railControlSP = new javax.swing.JScrollPane();
    railControlTA = new javax.swing.JTextArea();

    railControllerLbl.setText("Rail Controller Messages");

    systemLbl.setText("Command Station Messages");

    setLayout(new java.awt.BorderLayout());

    railControlSP.setColumnHeaderView(railControllerLbl);

    railControlTA.setColumns(20);
    railControlTA.setRows(5);
    railControlSP.setViewportView(railControlTA);

    add(railControlSP, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane railControlSP;
  private javax.swing.JTextArea railControlTA;
  private javax.swing.JLabel railControllerLbl;
  private javax.swing.JLabel systemLbl;
  // End of variables declaration//GEN-END:variables
}
