/*
 * Copyright 2026 frans.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.widgets;

/**
 *
 * @author frans
 */
public class MessagesPanel extends javax.swing.JPanel {

  /**
   * Creates new form MessagesPanel
   */
  public MessagesPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    railControllerLbl = new javax.swing.JLabel();
    systemLbl = new javax.swing.JLabel();
    logSP = new javax.swing.JSplitPane();
    commandStationLogSP = new javax.swing.JScrollPane();
    commandStationLogTA = new javax.swing.JTextArea();
    railControlSP = new javax.swing.JScrollPane();
    raiControlTA = new javax.swing.JTextArea();

    railControllerLbl.setText("Rail Controller Messages");

    systemLbl.setText("Command Station Messages");

    setLayout(new java.awt.BorderLayout());

    logSP.setDividerLocation(420);
    logSP.setDividerSize(10);

    commandStationLogSP.setColumnHeaderView(systemLbl);
    commandStationLogSP.setRowHeaderView(null);

    commandStationLogTA.setColumns(20);
    commandStationLogTA.setRows(5);
    commandStationLogSP.setViewportView(commandStationLogTA);

    logSP.setLeftComponent(commandStationLogSP);

    railControlSP.setColumnHeaderView(railControllerLbl);

    raiControlTA.setColumns(20);
    raiControlTA.setRows(5);
    railControlSP.setViewportView(raiControlTA);

    logSP.setRightComponent(railControlSP);

    add(logSP, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane commandStationLogSP;
  private javax.swing.JTextArea commandStationLogTA;
  private javax.swing.JSplitPane logSP;
  private javax.swing.JTextArea raiControlTA;
  private javax.swing.JScrollPane railControlSP;
  private javax.swing.JLabel railControllerLbl;
  private javax.swing.JLabel systemLbl;
  // End of variables declaration//GEN-END:variables
}
