/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lan.wervel.jcs.ui.nb;

import java.awt.event.ActionEvent;
import java.lang.reflect.Field;
import javax.swing.JToggleButton;
import javax.swing.Timer;
import lan.wervel.jcs.common.TrackRepository;
import lan.wervel.jcs.ui.Refreshable;
import org.pmw.tinylog.Logger;

/**
 *
 * @author frans
 */
public class DriveWayPanel extends javax.swing.JPanel implements Refreshable {

  private static final long serialVersionUID = -5138450311858564280L;

  private int number;
  private TrackRepository repository;

  private JToggleButtonDriveWayBinder binder1;
  private JToggleButtonDriveWayBinder binder2;
  private JToggleButtonDriveWayBinder binder3;
  private JToggleButtonDriveWayBinder binder4;
  private JToggleButtonDriveWayBinder binder5;
  private JToggleButtonDriveWayBinder binder6;
  private JToggleButtonDriveWayBinder binder7;
  private JToggleButtonDriveWayBinder binder8;
  private JToggleButtonDriveWayBinder binder9;
  private JToggleButtonDriveWayBinder binder10;
  private JToggleButtonDriveWayBinder binder11;
  private JToggleButtonDriveWayBinder binder12;
  private JToggleButtonDriveWayBinder binder13;
  private JToggleButtonDriveWayBinder binder14;
  private JToggleButtonDriveWayBinder binder15;
  private JToggleButtonDriveWayBinder binder16;

  private Timer timer;

  public DriveWayPanel() {
    this(0, null);
  }

  /**
   * Creates new form SwitchBoardPanel
   *
   * @param number
   * @param repository
   */
  public DriveWayPanel(int number, TrackRepository repository) {
    this.number = number;
    this.repository = repository;
    if (this.repository != null) {
      initTrackComponents();
    }

    initComponents();

    if (this.repository != null) {
      linkBindersToButtons();
      startRefreshCycle();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btn1 = new javax.swing.JToggleButton();
    btn2 = new javax.swing.JToggleButton();
    btn3 = new javax.swing.JToggleButton();
    btn4 = new javax.swing.JToggleButton();
    btn5 = new javax.swing.JToggleButton();
    btn6 = new javax.swing.JToggleButton();
    btn7 = new javax.swing.JToggleButton();
    btn8 = new javax.swing.JToggleButton();
    btn9 = new javax.swing.JToggleButton();
    btn10 = new javax.swing.JToggleButton();
    btn11 = new javax.swing.JToggleButton();
    btn12 = new javax.swing.JToggleButton();
    btn13 = new javax.swing.JToggleButton();
    btn14 = new javax.swing.JToggleButton();
    btn15 = new javax.swing.JToggleButton();
    btn16 = new javax.swing.JToggleButton();

    setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DriveWays - 1"));
    setMinimumSize(new java.awt.Dimension(600, 175));
    setPreferredSize(new java.awt.Dimension(600, 175));
    setLayout(new java.awt.GridLayout(2, 8));

    btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn1.setText("01");
    btn1.setMaximumSize(new java.awt.Dimension(65, 65));
    btn1.setMinimumSize(new java.awt.Dimension(65, 65));
    btn1.setPreferredSize(new java.awt.Dimension(65, 65));
    btn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn1);

    btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn2.setText("02");
    btn2.setMaximumSize(new java.awt.Dimension(65, 65));
    btn2.setMinimumSize(new java.awt.Dimension(65, 65));
    btn2.setPreferredSize(new java.awt.Dimension(65, 65));
    btn2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn2);

    btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn3.setText("03");
    btn3.setMaximumSize(new java.awt.Dimension(65, 65));
    btn3.setMinimumSize(new java.awt.Dimension(65, 65));
    btn3.setPreferredSize(new java.awt.Dimension(65, 65));
    btn3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn3);

    btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn4.setText("04");
    btn4.setMaximumSize(new java.awt.Dimension(65, 65));
    btn4.setMinimumSize(new java.awt.Dimension(65, 65));
    btn4.setPreferredSize(new java.awt.Dimension(65, 65));
    btn4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn4);

    btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn5.setText("05");
    btn5.setMaximumSize(new java.awt.Dimension(65, 65));
    btn5.setMinimumSize(new java.awt.Dimension(65, 65));
    btn5.setPreferredSize(new java.awt.Dimension(65, 65));
    btn5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn5);

    btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn6.setText("06");
    btn6.setMaximumSize(new java.awt.Dimension(65, 65));
    btn6.setMinimumSize(new java.awt.Dimension(65, 65));
    btn6.setPreferredSize(new java.awt.Dimension(65, 65));
    btn6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn6);

    btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn7.setText("07");
    btn7.setMaximumSize(new java.awt.Dimension(65, 65));
    btn7.setMinimumSize(new java.awt.Dimension(65, 65));
    btn7.setPreferredSize(new java.awt.Dimension(65, 65));
    btn7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn7);

    btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn8.setText("08");
    btn8.setMaximumSize(new java.awt.Dimension(65, 65));
    btn8.setMinimumSize(new java.awt.Dimension(65, 65));
    btn8.setPreferredSize(new java.awt.Dimension(65, 65));
    btn8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn8);

    btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn9.setText("09");
    btn9.setToolTipText("");
    btn9.setMaximumSize(new java.awt.Dimension(65, 65));
    btn9.setMinimumSize(new java.awt.Dimension(65, 65));
    btn9.setPreferredSize(new java.awt.Dimension(65, 65));
    btn9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn9);

    btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn10.setText("10");
    btn10.setToolTipText("");
    btn10.setMaximumSize(new java.awt.Dimension(65, 65));
    btn10.setMinimumSize(new java.awt.Dimension(65, 65));
    btn10.setPreferredSize(new java.awt.Dimension(65, 65));
    btn10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn10);

    btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn11.setText("11");
    btn11.setToolTipText("");
    btn11.setMaximumSize(new java.awt.Dimension(65, 65));
    btn11.setMinimumSize(new java.awt.Dimension(65, 65));
    btn11.setPreferredSize(new java.awt.Dimension(65, 65));
    btn11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn11);

    btn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn12.setText("12");
    btn12.setToolTipText("");
    btn12.setMaximumSize(new java.awt.Dimension(65, 65));
    btn12.setMinimumSize(new java.awt.Dimension(65, 65));
    btn12.setPreferredSize(new java.awt.Dimension(65, 65));
    btn12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn12);

    btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn13.setText("13");
    btn13.setToolTipText("");
    btn13.setMaximumSize(new java.awt.Dimension(65, 65));
    btn13.setMinimumSize(new java.awt.Dimension(65, 65));
    btn13.setPreferredSize(new java.awt.Dimension(65, 65));
    btn13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn13);

    btn14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn14.setText("14");
    btn14.setToolTipText("");
    btn14.setMaximumSize(new java.awt.Dimension(65, 65));
    btn14.setMinimumSize(new java.awt.Dimension(65, 65));
    btn14.setPreferredSize(new java.awt.Dimension(65, 65));
    btn14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn14);

    btn15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn15.setText("15");
    btn15.setToolTipText("");
    btn15.setMaximumSize(new java.awt.Dimension(65, 65));
    btn15.setMinimumSize(new java.awt.Dimension(65, 65));
    btn15.setPreferredSize(new java.awt.Dimension(65, 65));
    btn15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn15);

    btn16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Grey-20px.png"))); // NOI18N
    btn16.setText("16");
    btn16.setToolTipText("");
    btn16.setMaximumSize(new java.awt.Dimension(65, 65));
    btn16.setMinimumSize(new java.awt.Dimension(65, 65));
    btn16.setPreferredSize(new java.awt.Dimension(65, 65));
    btn16.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Button-Purple-20px.png"))); // NOI18N
    add(btn16);
  }// </editor-fold>//GEN-END:initComponents

  private void initTrackComponents() {
    for (int i = 1; i <= 16; i++) {
      Logger.trace("Init binder " + i + "...");
      JToggleButtonDriveWayBinder binder = new JToggleButtonDriveWayBinder(repository, number, i);
      setJToggleButtonDriveWayBinder(i, binder);
    }
  }

  private void setJToggleButtonDriveWayBinder(int number, JToggleButtonDriveWayBinder binder) {
    try {
      Field binderField = this.getClass().getDeclaredField("binder" + number);
      binderField.setAccessible(true);
      binderField.set(this, binder);
    } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
      Logger.error(ex);
    }
  }

  private void linkBindersToButtons() {
    this.binder1.setBtn(btn1);
    this.binder2.setBtn(btn2);
    this.binder3.setBtn(btn3);
    this.binder4.setBtn(btn4);
    this.binder5.setBtn(btn5);
    this.binder6.setBtn(btn6);
    this.binder7.setBtn(btn7);
    this.binder8.setBtn(btn8);
    this.binder9.setBtn(btn9);
    this.binder10.setBtn(btn10);
    this.binder11.setBtn(btn11);
    this.binder12.setBtn(btn12);
    this.binder13.setBtn(btn13);
    this.binder14.setBtn(btn14);
    this.binder15.setBtn(btn15);
    this.binder16.setBtn(btn16);
  }

  private JToggleButton getJToggleButton(int number) {
    JToggleButton btn = null;
    try {
      Field btnField = this.getClass().getDeclaredField("btn" + number);

      btnField.setAccessible(true);

      btn = (JToggleButton) btnField.get(this);
    } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
      Logger.error(ex);
    }
    return btn;
  }

  private JToggleButtonDriveWayBinder getJToggleButtonDriveWayBinder(int number) {
    JToggleButtonDriveWayBinder binder = null;
    try {
      Field binderField = this.getClass().getDeclaredField("binder" + number);
      binderField.setAccessible(true);

      binder = (JToggleButtonDriveWayBinder) binderField.get(this);
    } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
      Logger.error(ex);
    }
    return binder;
  }

  @Override
  public void refresh() {
    try {
      for (int i = 1; i <= 16; i++) {
        JToggleButtonDriveWayBinder binder = getJToggleButtonDriveWayBinder(i);
        binder.refresh();
      }
    } catch (Exception e) {
      Logger.trace(e);
    }
  }

  public final void startRefreshCycle() {
    Logger.debug("Starting refresh cycle...");
    timer = new Timer(500, (ActionEvent e) -> {
      refresh();
    });

    timer.setRepeats(true);
    timer.start();
  }

  public final void stopRefreshCycle() {
    this.timer.stop();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton btn1;
  private javax.swing.JToggleButton btn10;
  private javax.swing.JToggleButton btn11;
  private javax.swing.JToggleButton btn12;
  private javax.swing.JToggleButton btn13;
  private javax.swing.JToggleButton btn14;
  private javax.swing.JToggleButton btn15;
  private javax.swing.JToggleButton btn16;
  private javax.swing.JToggleButton btn2;
  private javax.swing.JToggleButton btn3;
  private javax.swing.JToggleButton btn4;
  private javax.swing.JToggleButton btn5;
  private javax.swing.JToggleButton btn6;
  private javax.swing.JToggleButton btn7;
  private javax.swing.JToggleButton btn8;
  private javax.swing.JToggleButton btn9;
  // End of variables declaration//GEN-END:variables
}
