/*
 * Copyright 2023 frans.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.options;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.tinylog.Logger;

/**
 *
 * @author frans
 */
public class CommandStationDialog extends javax.swing.JDialog {

  /**
   * Creates new form CommandStationDialog
   */
  public CommandStationDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    commandStationPanel1 = new jcs.ui.options.CommandStationPanel();
    southPanel = new javax.swing.JPanel();
    exitBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(1080, 750));
    getContentPane().add(commandStationPanel1, java.awt.BorderLayout.CENTER);

    southPanel.setPreferredSize(new java.awt.Dimension(1024, 50));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT);
    flowLayout1.setAlignOnBaseline(true);
    southPanel.setLayout(flowLayout1);

    exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/exit-24.png"))); // NOI18N
    exitBtn.setText("Close");
    exitBtn.setPreferredSize(new java.awt.Dimension(100, 36));
    exitBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitBtnActionPerformed(evt);
      }
    });
    southPanel.add(exitBtn);

    getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    this.setVisible(false);
    this.dispose();
  }//GEN-LAST:event_exitBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.warn("Can't set the LookAndFeel: " + ex);
    }

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(() -> {
      CommandStationDialog dialog = new CommandStationDialog(new javax.swing.JFrame(), true);
      dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      dialog.setLocationRelativeTo(null);
      dialog.pack();
      dialog.setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private jcs.ui.options.CommandStationPanel commandStationPanel1;
  private javax.swing.JButton exitBtn;
  private javax.swing.JPanel southPanel;
  // End of variables declaration//GEN-END:variables
}
