/*
 * Copyright 2023 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.options;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import jcs.entities.LocomotiveBean;
import jcs.persistence.PersistenceFactory;
import jcs.trackservice.TrackControllerFactory;
import jcs.ui.options.table.LocomotiveTableModel;
import org.tinylog.Logger;

/**
 *
 * @author frans
 */
public class LocomotivePreferencesPanel extends JPanel {

    private final LocomotiveTableModel locoTableModel;

    /**
     * Creates new form LocomotivePanel
     */
    public LocomotivePreferencesPanel() {
        locoTableModel = new LocomotiveTableModel();

        initComponents();

        alignLocoTable();

        //Select the firts row
        if (locoTableModel.getRowCount() > 0) {
            this.selectLoco(0);
            this.locoTable.setRowSelectionInterval(0, 0);
        }

    }

    private void alignLocoTable() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        this.locoTable.getColumnModel().getColumn(0).setPreferredWidth(90);
        this.locoTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        this.locoTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        this.locoTable.getColumnModel().getColumn(2).setPreferredWidth(80);
        this.locoTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        this.locoTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        this.locoTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        this.locoTable.getColumnModel().getColumn(5).setPreferredWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "deprecation"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectedLocomotive = new LocomotiveBean();
        topPanel = new JPanel();
        synchronizeBtn = new JButton();
        refreshBtn = new JButton();
        newBtn = new JButton();
        centerPanel = new JPanel();
        centerSplitPane = new JSplitPane();
        locoTableScrollPane = new JScrollPane();
        locoTable = new JTable();
        locoDetailPanel = new JPanel();
        row1Panel = new JPanel();
        filler3 = new Box.Filler(new Dimension(100, 0), new Dimension(55, 0), new Dimension(100, 32767));
        showCB = new JCheckBox();
        commuterCB = new JCheckBox();
        imageLbl = new JLabel();
        row2Panel = new JPanel();
        nameLbl = new JLabel();
        nameTF = new JTextField();
        row3Panel = new JPanel();
        addressLbl = new JLabel();
        addressSpinner = new JSpinner();
        decoderLabel = new JLabel();
        decoderCB = new JComboBox<>();
        row4Panel = new JPanel();
        lengthLbl = new JLabel();
        lengthSpinner = new JSpinner();
        row5Panel = new JPanel();
        row6Panel = new JPanel();
        row7Panel = new JPanel();
        row8Panel = new JPanel();
        row9Panel = new JPanel();
        filler2 = new Box.Filler(new Dimension(0, 50), new Dimension(0, 50), new Dimension(32767, 300));
        buttonPanel = new JPanel();
        bottomPanel = new JPanel();
        deleteBtn = new JButton();
        filler1 = new Box.Filler(new Dimension(100, 0), new Dimension(200, 0), new Dimension(150, 32767));
        saveBtn = new JButton();

        setMinimumSize(new Dimension(1000, 600));
        setPreferredSize(new Dimension(1000, 600));
        setLayout(new BorderLayout());

        topPanel.setMinimumSize(new Dimension(1000, 50));
        topPanel.setPreferredSize(new Dimension(1000, 50));
        topPanel.setRequestFocusEnabled(false);
        FlowLayout flowLayout2 = new FlowLayout(FlowLayout.RIGHT);
        flowLayout2.setAlignOnBaseline(true);
        topPanel.setLayout(flowLayout2);

        synchronizeBtn.setIcon(new ImageIcon(getClass().getResource("/media/CS2-3-Sync.png"))); // NOI18N
        synchronizeBtn.setToolTipText("Synchronize Locomotives met CS 2/3");
        synchronizeBtn.setMaximumSize(new Dimension(40, 40));
        synchronizeBtn.setMinimumSize(new Dimension(40, 40));
        synchronizeBtn.setPreferredSize(new Dimension(40, 40));
        synchronizeBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                synchronizeBtnActionPerformed(evt);
            }
        });
        topPanel.add(synchronizeBtn);

        refreshBtn.setIcon(new ImageIcon(getClass().getResource("/media/refresh-24.png"))); // NOI18N
        refreshBtn.setToolTipText("Refresh Locomotives");
        refreshBtn.setMaximumSize(new Dimension(40, 40));
        refreshBtn.setMinimumSize(new Dimension(40, 40));
        refreshBtn.setPreferredSize(new Dimension(40, 40));
        refreshBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        topPanel.add(refreshBtn);

        newBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24.png"))); // NOI18N
        newBtn.setToolTipText("Create new Locomotive");
        newBtn.setMaximumSize(new Dimension(40, 40));
        newBtn.setMinimumSize(new Dimension(40, 40));
        newBtn.setPreferredSize(new Dimension(40, 40));
        newBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        topPanel.add(newBtn);

        add(topPanel, BorderLayout.NORTH);

        centerPanel.setMinimumSize(new Dimension(1000, 500));
        centerPanel.setPreferredSize(new Dimension(1000, 500));
        centerPanel.setLayout(new BorderLayout());

        centerSplitPane.setBorder(null);
        centerSplitPane.setDividerLocation(500);
        centerSplitPane.setDoubleBuffered(true);
        centerSplitPane.setPreferredSize(new Dimension(1000, 540));

        locoTableScrollPane.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        locoTableScrollPane.setMinimumSize(new Dimension(500, 440));
        locoTableScrollPane.setPreferredSize(new Dimension(500, 400));
        locoTableScrollPane.setRequestFocusEnabled(false);
        locoTableScrollPane.setViewportView(locoTable);

        locoTable.setModel(locoTableModel);
        locoTable.setDoubleBuffered(true);
        locoTable.setGridColor(new Color(204, 204, 204));
        locoTable.setPreferredSize(new Dimension(480, 600));
        locoTable.setRequestFocusEnabled(false);
        locoTable.setRowHeight(20);
        locoTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        locoTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        locoTable.setShowGrid(true);
        locoTable.getTableHeader().setReorderingAllowed(false);
        locoTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                locoTableMouseClicked(evt);
            }
        });
        locoTableScrollPane.setViewportView(locoTable);

        centerSplitPane.setLeftComponent(locoTableScrollPane);

        locoDetailPanel.setMinimumSize(new Dimension(390, 540));
        locoDetailPanel.setPreferredSize(new Dimension(480, 500));
        locoDetailPanel.setLayout(new BoxLayout(locoDetailPanel, BoxLayout.Y_AXIS));

        row1Panel.setMinimumSize(new Dimension(380, 30));
        row1Panel.setPreferredSize(new Dimension(380, 50));
        FlowLayout flowLayout1 = new FlowLayout(FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        row1Panel.setLayout(flowLayout1);
        row1Panel.add(filler3);

        showCB.setText("Show");
        showCB.setToolTipText("Show the Locomotive");
        showCB.setDoubleBuffered(true);
        showCB.setHorizontalTextPosition(SwingConstants.LEADING);
        row1Panel.add(showCB);

        commuterCB.setText("Commuter");
        commuterCB.setToolTipText("A commuter Train");
        commuterCB.setDoubleBuffered(true);
        commuterCB.setHorizontalTextPosition(SwingConstants.LEADING);
        row1Panel.add(commuterCB);

        imageLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        imageLbl.setPreferredSize(new Dimension(128, 48));
        row1Panel.add(imageLbl);

        locoDetailPanel.add(row1Panel);

        row2Panel.setMinimumSize(new Dimension(380, 30));
        row2Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout3 = new FlowLayout(FlowLayout.LEFT);
        flowLayout3.setAlignOnBaseline(true);
        row2Panel.setLayout(flowLayout3);

        nameLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        nameLbl.setLabelFor(nameTF);
        nameLbl.setText("Name");
        nameLbl.setPreferredSize(new Dimension(100, 16));
        row2Panel.add(nameLbl);

        nameTF.setEditable(false);
        nameTF.setMinimumSize(new Dimension(175, 26));
        nameTF.setPreferredSize(new Dimension(225, 26));
        row2Panel.add(nameTF);

        locoDetailPanel.add(row2Panel);

        row3Panel.setMinimumSize(new Dimension(380, 30));
        row3Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout4 = new FlowLayout(FlowLayout.LEFT);
        flowLayout4.setAlignOnBaseline(true);
        row3Panel.setLayout(flowLayout4);

        addressLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        addressLbl.setLabelFor(addressSpinner);
        addressLbl.setText("Address");
        addressLbl.setPreferredSize(new Dimension(100, 16));
        row3Panel.add(addressLbl);

        addressSpinner.setModel(new SpinnerNumberModel(0, 0, null, 1));
        addressSpinner.setDoubleBuffered(true);
        addressSpinner.setEditor(new JSpinner.NumberEditor(addressSpinner, ""));
        addressSpinner.setEnabled(false);
        addressSpinner.setMinimumSize(new Dimension(50, 26));
        addressSpinner.setName(""); // NOI18N
        addressSpinner.setNextFocusableComponent(nameTF);
        addressSpinner.setPreferredSize(new Dimension(70, 26));
        row3Panel.add(addressSpinner);

        decoderLabel.setHorizontalAlignment(SwingConstants.TRAILING);
        decoderLabel.setText("Decoder");
        decoderLabel.setPreferredSize(new Dimension(70, 16));
        row3Panel.add(decoderLabel);

        decoderCB.setModel(new DefaultComboBoxModel<>(new String[] { "mm_prg", "mfx", "dcc", "sx1" }));
        decoderCB.setEnabled(false);
        row3Panel.add(decoderCB);

        locoDetailPanel.add(row3Panel);

        row4Panel.setMinimumSize(new Dimension(380, 30));
        row4Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout5 = new FlowLayout(FlowLayout.LEFT);
        flowLayout5.setAlignOnBaseline(true);
        row4Panel.setLayout(flowLayout5);

        lengthLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        lengthLbl.setText("Length");
        lengthLbl.setPreferredSize(new Dimension(100, 16));
        row4Panel.add(lengthLbl);

        lengthSpinner.setModel(new SpinnerNumberModel());
        lengthSpinner.setDoubleBuffered(true);
        lengthSpinner.setPreferredSize(new Dimension(70, 26));
        row4Panel.add(lengthSpinner);

        locoDetailPanel.add(row4Panel);

        row5Panel.setMinimumSize(new Dimension(380, 30));
        row5Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout6 = new FlowLayout(FlowLayout.LEFT);
        flowLayout6.setAlignOnBaseline(true);
        row5Panel.setLayout(flowLayout6);
        locoDetailPanel.add(row5Panel);

        row6Panel.setMinimumSize(new Dimension(380, 30));
        row6Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout7 = new FlowLayout(FlowLayout.LEFT);
        flowLayout7.setAlignOnBaseline(true);
        row6Panel.setLayout(flowLayout7);
        locoDetailPanel.add(row6Panel);

        row7Panel.setMinimumSize(new Dimension(380, 30));
        row7Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout9 = new FlowLayout(FlowLayout.LEFT);
        flowLayout9.setAlignOnBaseline(true);
        row7Panel.setLayout(flowLayout9);
        locoDetailPanel.add(row7Panel);

        row8Panel.setMinimumSize(new Dimension(380, 30));
        row8Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout8 = new FlowLayout(FlowLayout.LEFT);
        flowLayout8.setAlignOnBaseline(true);
        row8Panel.setLayout(flowLayout8);
        locoDetailPanel.add(row8Panel);

        row9Panel.setMinimumSize(new Dimension(380, 30));
        row9Panel.setPreferredSize(new Dimension(380, 30));
        row9Panel.setLayout(new FlowLayout(FlowLayout.LEFT));
        locoDetailPanel.add(row9Panel);
        locoDetailPanel.add(filler2);

        buttonPanel.setPreferredSize(new Dimension(380, 40));
        FlowLayout flowLayout10 = new FlowLayout();
        flowLayout10.setAlignOnBaseline(true);
        buttonPanel.setLayout(flowLayout10);
        locoDetailPanel.add(buttonPanel);

        centerSplitPane.setRightComponent(locoDetailPanel);

        centerPanel.add(centerSplitPane, BorderLayout.CENTER);

        add(centerPanel, BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new Dimension(1000, 50));
        bottomPanel.setRequestFocusEnabled(false);
        bottomPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));

        deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setEnabled(false);
        deleteBtn.setMaximumSize(new Dimension(100, 36));
        deleteBtn.setMinimumSize(new Dimension(100, 36));
        deleteBtn.setPreferredSize(new Dimension(100, 36));
        deleteBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(deleteBtn);
        bottomPanel.add(filler1);

        saveBtn.setIcon(new ImageIcon(getClass().getResource("/media/save-24.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setMaximumSize(new Dimension(100, 36));
        saveBtn.setMinimumSize(new Dimension(100, 36));
        saveBtn.setPreferredSize(new Dimension(100, 36));
        saveBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(saveBtn);

        add(bottomPanel, BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

  private void newBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
      this.locoTableModel.refresh();
      alignLocoTable();
      Logger.trace("Create new Loco...");

      this.selectedLocomotive = new LocomotiveBean();
      this.selectedLocomotive.setId(locoTableModel.getRowCount() + 1L);
      this.selectedLocomotive.setName("new Loco " + (locoTableModel.getRowCount() + 1));
      this.selectedLocomotive.setvMin(0);
      this.selectedLocomotive.setTachoMax(0);
      this.setComponentValues(selectedLocomotive);
  }//GEN-LAST:event_newBtnActionPerformed

    private LocomotiveBean getLocomotiveFromPersistentStore(LocomotiveBean locomotive) {
        LocomotiveBean loco;
        if (locomotive.getId() != null) {
            loco = PersistenceFactory.getService().getLocomotive(locomotive.getId());
        } else {
            loco = PersistenceFactory.getService().getLocomotive(locomotive.getAddress(), locomotive.getDecoderType());
        }
        return loco;
    }

    private void selectLoco(int row) {
        LocomotiveBean loc = locoTableModel.getControllableDeviceAt(row);
        if (loc != null) {
            //Logger.trace("Selected row: " + row + ", Id: " + loc.getId() + " Address: " + loc.getAddress() + " Decoder: " + loc.getDecoderType());
            selectedLocomotive = getLocomotiveFromPersistentStore(loc);
            //locoDetailPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createCompoundBorder(), "Edit " + selectedLocomotive.getName()));
            setComponentValues(selectedLocomotive);
        } else {
            Logger.trace("No loc found @ row " + row);
        }
    }

  private void locoTableMouseClicked(MouseEvent evt) {//GEN-FIRST:event_locoTableMouseClicked
      JTable source = (JTable) evt.getSource();
      int row = source.rowAtPoint(evt.getPoint());
      selectLoco(row);
  }//GEN-LAST:event_locoTableMouseClicked

  private void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
      if (this.selectedLocomotive != null) {
          LocomotiveBean loco = getLocomotiveFromPersistentStore(selectedLocomotive);
          loco = setLocomotiveValues(loco);
          Logger.trace("Save the Loco: " + this.selectedLocomotive);

          selectedLocomotive = this.selectedLocomotive = PersistenceFactory.getService().persist(loco);
          setComponentValues(selectedLocomotive);
          locoTableModel.refresh();
          alignLocoTable();
      }
  }//GEN-LAST:event_saveBtnActionPerformed

  private void deleteBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
      Logger.trace("Delete Loco: " + this.selectedLocomotive);
      TrackControllerFactory.getTrackController().remove(selectedLocomotive);
      this.selectedLocomotive = null;
      this.locoTableModel.refresh();
      this.setComponentValues(selectedLocomotive);
      alignLocoTable();

      this.selectLoco(0);
      this.locoTable.setRowSelectionInterval(0, 0);
  }//GEN-LAST:event_deleteBtnActionPerformed

    public void refresh() {
        this.selectedLocomotive = null;
        this.locoTableModel.refresh();
        alignLocoTable();
        if (this.locoTable.getRowCount() > 0) {
            this.selectLoco(0);
            this.locoTable.setRowSelectionInterval(0, 0);
        }
    }

    private void synchronize() {
        TrackControllerFactory.getTrackController().synchronizeLocomotivesWithController();

        refresh();
    }

  private void refreshBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
      refresh();
  }//GEN-LAST:event_refreshBtnActionPerformed

    private void synchronizeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_synchronizeBtnActionPerformed
        synchronize();
    }//GEN-LAST:event_synchronizeBtnActionPerformed

    protected LocomotiveBean setLocomotiveValues(LocomotiveBean loco) {
        boolean show = this.showCB.isSelected();
        boolean commuter = this.commuterCB.isSelected();
        String name = this.nameTF.getText();

        Integer length = (Integer) this.lengthSpinner.getValue();

        LocomotiveBean loc;
        if (loco != null) {
            loc = loco;
        } else {
            loc = new LocomotiveBean();
        }

        //loc.setName(name);
        loc.setLength(length);
        loc.setShow(show);
        loc.setCommuter(commuter);

        return loc;
    }

    protected void setComponentValues(LocomotiveBean loco) {
        if (loco != null) {
            if (loco.getLocIcon() != null) {
                this.imageLbl.setIcon(new ImageIcon(loco.getLocIcon()));
                this.imageLbl.setText("");
            } else {
                this.imageLbl.setText(loco.getIcon());
            }

            this.addressSpinner.setValue(loco.getAddress());
            this.decoderCB.setSelectedItem(loco.getDecoderTypeString());
            this.nameTF.setText(loco.getName());

            if(loco.getLength() != null) {
              this.lengthSpinner.setValue(loco.getLength());
            } else {
              this.lengthSpinner.setValue(0);
            }  
            this.commuterCB.setSelected(loco.isCommuter());
            this.showCB.setSelected(loco.isShow());

        } else {
            this.imageLbl.setText("ICON");

            this.addressSpinner.setValue(0);
            this.decoderCB.setSelectedItem("mm_prg");
            this.nameTF.setText("");

            this.lengthSpinner.setValue(0);
            this.commuterCB.setSelected(false);
            this.showCB.setSelected(true);
        }
    }

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.error("Can't set the LookAndFeel: " + ex);
        }
        java.awt.EventQueue.invokeLater(() -> {

            LocomotivePreferencesPanel testPanel = new LocomotivePreferencesPanel();
            JFrame testFrame = new JFrame();
            JDialog testDialog = new JDialog(testFrame, true);

            testDialog.add(testPanel);

            testDialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            testDialog.pack();
            testDialog.setLocationRelativeTo(null);

            testDialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel addressLbl;
    private JSpinner addressSpinner;
    private JPanel bottomPanel;
    private JPanel buttonPanel;
    private JPanel centerPanel;
    private JSplitPane centerSplitPane;
    private JCheckBox commuterCB;
    private JComboBox<String> decoderCB;
    private JLabel decoderLabel;
    private JButton deleteBtn;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private Box.Filler filler3;
    private JLabel imageLbl;
    private JLabel lengthLbl;
    private JSpinner lengthSpinner;
    private JPanel locoDetailPanel;
    private JTable locoTable;
    private JScrollPane locoTableScrollPane;
    private JLabel nameLbl;
    private JTextField nameTF;
    private JButton newBtn;
    private JButton refreshBtn;
    private JPanel row1Panel;
    private JPanel row2Panel;
    private JPanel row3Panel;
    private JPanel row4Panel;
    private JPanel row5Panel;
    private JPanel row6Panel;
    private JPanel row7Panel;
    private JPanel row8Panel;
    private JPanel row9Panel;
    private JButton saveBtn;
    private LocomotiveBean selectedLocomotive;
    private JCheckBox showCB;
    private JButton synchronizeBtn;
    private JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
