/*
 * Copyright 2023 Frans Jacobs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jcs.ui.options;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.tinylog.Logger;

/**
 *
 * @author frans
 */
public class OptionDialog extends javax.swing.JDialog {

  /**
   * Creates new form NewJDialog
   *
   * @param parent
   * @param modal
   */
  public OptionDialog(Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    init();
  }

  private void init() {
    //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/media/jcs-train-64.png")));
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    topPanel = new JPanel();
    centerPanel = new JPanel();
    prefsTP = new JTabbedPane();
    locomotivePanel = new LocomotivePreferencesPanel();
    propertiesPanel = new PropertiesPanel();
    signalPanel = new SignalPreferencesPanel();
    turnoutPanel = new TurnoutPreferencesPanel();
    controllerInfoPanel1 = new ControllerInfoPanel();
    southPanel = new JPanel();
    closeBtn = new JButton();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Options");
    setAlwaysOnTop(true);
    setMinimumSize(new Dimension(1024, 750));
    setName("Options"); // NOI18N
    setPreferredSize(new Dimension(1024, 750));

    topPanel.setMinimumSize(new Dimension(1024, 20));
    topPanel.setName("topPanel"); // NOI18N
    topPanel.setPreferredSize(new Dimension(1024, 20));
    getContentPane().add(topPanel, BorderLayout.PAGE_START);

    centerPanel.setMinimumSize(new Dimension(1021, 750));
    centerPanel.setName("centerPanel"); // NOI18N
    centerPanel.setLayout(new BorderLayout());

    prefsTP.setName("prefsTP"); // NOI18N
    prefsTP.addChangeListener(new ChangeListener() {
      public void stateChanged(ChangeEvent evt) {
        prefsTPStateChanged(evt);
      }
    });

    locomotivePanel.setName("locomotivePanel"); // NOI18N
    prefsTP.addTab("Locomotives", locomotivePanel);

    propertiesPanel.setName("propertiesPanel"); // NOI18N
    prefsTP.addTab("Properties", propertiesPanel);

    signalPanel.setName("signalPanel"); // NOI18N
    prefsTP.addTab("Signals", signalPanel);

    turnoutPanel.setName("turnoutPanel"); // NOI18N
    prefsTP.addTab("Turnouts", turnoutPanel);

    controllerInfoPanel1.setName("controllerInfoPanel1"); // NOI18N
    prefsTP.addTab("Controller", controllerInfoPanel1);

    centerPanel.add(prefsTP, BorderLayout.CENTER);
    prefsTP.getAccessibleContext().setAccessibleName("Locomotives");

    getContentPane().add(centerPanel, BorderLayout.CENTER);

    southPanel.setName("southPanel"); // NOI18N
    southPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));

    closeBtn.setIcon(new ImageIcon(getClass().getResource("/media/exit-24.png"))); // NOI18N
    closeBtn.setText("Close");
    closeBtn.setMaximumSize(new Dimension(100, 36));
    closeBtn.setMinimumSize(new Dimension(100, 36));
    closeBtn.setName("closeBtn"); // NOI18N
    closeBtn.setPreferredSize(new Dimension(100, 36));
    closeBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        closeBtnActionPerformed(evt);
      }
    });
    southPanel.add(closeBtn);

    getContentPane().add(southPanel, BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void closeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
    this.setVisible(false);
    this.dispose();

  }//GEN-LAST:event_closeBtnActionPerformed

  private void prefsTPStateChanged(ChangeEvent evt) {//GEN-FIRST:event_prefsTPStateChanged
    Component c = this.prefsTP.getSelectedComponent();

    if (c instanceof LocomotivePreferencesPanel) {
      this.locomotivePanel.refresh();
    } else if (c instanceof TurnoutPreferencesPanel) {
      //this.turnoutPanel.refresh();
    } else if (c instanceof SignalPreferencesPanel) {
      //this.signalPanel.refresh();
    } else if (c instanceof PropertiesPanel) {
      //this.propertiesPanel.refresh();
    }

    Logger.debug("Refreshed " + (c != null ? c.getName() : ""));
  }//GEN-LAST:event_prefsTPStateChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.warn("Can't set the LookAndFeel: " + ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
      OptionDialog dialog = new OptionDialog(new javax.swing.JFrame(), true);
      dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      dialog.setVisible(true);
    });
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JPanel centerPanel;
  private JButton closeBtn;
  private ControllerInfoPanel controllerInfoPanel1;
  private LocomotivePreferencesPanel locomotivePanel;
  private JTabbedPane prefsTP;
  private PropertiesPanel propertiesPanel;
  private SignalPreferencesPanel signalPanel;
  private JPanel southPanel;
  private JPanel topPanel;
  private TurnoutPreferencesPanel turnoutPanel;
  // End of variables declaration//GEN-END:variables
}
