/*
 * Copyright (C) 2019 frans.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package jcs.ui.options;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import jcs.entities.AccessoryBean;
import jcs.persistence.PersistenceFactory;
import jcs.controller.ControllerFactory;
import jcs.ui.options.table.SignalTableModel;
import org.tinylog.Logger;

/**
 *
 * @author frans
 */
public class SignalPreferencesPanel extends JPanel {

  private final SignalTableModel signalTableModel;

  public SignalPreferencesPanel() {
    signalTableModel = new SignalTableModel();
    initComponents();
    alignSignalTable();

    //Select the first row
    if (signalTableModel.getRowCount() > 0) {
      selectSignal(0);
      this.signalTable.setRowSelectionInterval(0, 0);
    }
  }

  private void alignSignalTable() {
    this.signalTable.getColumnModel().getColumn(0).setPreferredWidth(40);
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
    this.signalTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);

    this.signalTable.getColumnModel().getColumn(3).setPreferredWidth(40);
    this.signalTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
  }

  private AccessoryBean getAccessoryFromTrackService(AccessoryBean turnout) {
    return PersistenceFactory.getService().getAccessory(turnout.getId());
  }

  private void selectSignal(int row) {
    AccessoryBean t = this.signalTableModel.getControllableDeviceAt(row);
    if (t != null) {
      this.selectedSignal = getAccessoryFromTrackService(t);
      setComponentValues(selectedSignal);
    } else {
      Logger.trace("No Signal found @ row " + row);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("deprecation")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectedSignal = new AccessoryBean();
        topPanel = new JPanel();
        synchronizeBtn = new JButton();
        refreshBtn = new JButton();
        newBtn = new JButton();
        centerPanel = new JPanel();
        centerSplitPane = new JSplitPane();
        signalTableScrollPane = new JScrollPane();
        signalTable = new JTable();
        signalDetailPanel = new JPanel();
        row1Panel = new JPanel();
        idLbl = new JLabel();
        idSpinner = new JSpinner();
        row2Panel = new JPanel();
        nameLbl = new JLabel();
        nameTF = new JTextField();
        row3Panel = new JPanel();
        typeLbl = new JLabel();
        typeTF = new JTextField();
        row4Panel = new JPanel();
        switchTimeLbl = new JLabel();
        switchTimeSpinner = new JSpinner();
        row5Panel = new JPanel();
        decoderTypeLbl = new JLabel();
        decoderTypeTF = new JTextField();
        row6Panel = new JPanel();
        decoderLbl = new JLabel();
        decoderTF = new JTextField();
        row7Panel = new JPanel();
        positionLbl = new JLabel();
        positionSpinner = new JSpinner();
        row8Panel = new JPanel();
        row9Panel = new JPanel();
        filler2 = new Box.Filler(new Dimension(0, 90), new Dimension(0, 90), new Dimension(32767, 300));
        buttonPanel = new JPanel();
        deleteBtn = new JButton();
        filler1 = new Box.Filler(new Dimension(50, 0), new Dimension(200, 0), new Dimension(150, 32767));
        saveBtn = new JButton();
        bottomPanel = new JPanel();

        setMinimumSize(new Dimension(1000, 600));
        setPreferredSize(new Dimension(1000, 600));
        setLayout(new BorderLayout());

        topPanel.setMinimumSize(new Dimension(1000, 50));
        topPanel.setPreferredSize(new Dimension(1000, 50));
        topPanel.setRequestFocusEnabled(false);
        FlowLayout flowLayout1 = new FlowLayout(FlowLayout.RIGHT);
        flowLayout1.setAlignOnBaseline(true);
        topPanel.setLayout(flowLayout1);

        synchronizeBtn.setIcon(new ImageIcon(getClass().getResource("/media/CS2-3-Sync.png"))); // NOI18N
        synchronizeBtn.setToolTipText("Synchronize with CS3");
        synchronizeBtn.setMaximumSize(new Dimension(40, 40));
        synchronizeBtn.setMinimumSize(new Dimension(40, 40));
        synchronizeBtn.setPreferredSize(new Dimension(40, 40));
        synchronizeBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                synchronizeBtnActionPerformed(evt);
            }
        });
        topPanel.add(synchronizeBtn);

        refreshBtn.setIcon(new ImageIcon(getClass().getResource("/media/refresh-24.png"))); // NOI18N
        refreshBtn.setToolTipText("Refresh");
        refreshBtn.setMargin(new Insets(2, 2, 2, 2));
        refreshBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        topPanel.add(refreshBtn);

        newBtn.setIcon(new ImageIcon(getClass().getResource("/media/add-24.png"))); // NOI18N
        newBtn.setToolTipText("Add");
        newBtn.setMaximumSize(new Dimension(40, 40));
        newBtn.setMinimumSize(new Dimension(40, 40));
        newBtn.setPreferredSize(new Dimension(40, 40));
        newBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        topPanel.add(newBtn);

        add(topPanel, BorderLayout.NORTH);

        centerPanel.setMinimumSize(new Dimension(1000, 500));
        centerPanel.setPreferredSize(new Dimension(1000, 500));
        centerPanel.setLayout(new BorderLayout());

        centerSplitPane.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        centerSplitPane.setDividerLocation(500);
        centerSplitPane.setDoubleBuffered(true);
        centerSplitPane.setMinimumSize(new Dimension(1000, 500));
        centerSplitPane.setPreferredSize(new Dimension(1000, 500));

        signalTableScrollPane.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        signalTableScrollPane.setPreferredSize(new Dimension(500, 500));

        signalTable.setModel(signalTableModel);
        signalTable.setDoubleBuffered(true);
        signalTable.setGridColor(new Color(204, 204, 204));
        signalTable.setPreferredSize(new Dimension(480, 470));
        signalTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        signalTable.getTableHeader().setReorderingAllowed(false);
        signalTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                signalTableMouseClicked(evt);
            }
        });
        signalTableScrollPane.setViewportView(signalTable);

        centerSplitPane.setLeftComponent(signalTableScrollPane);

        signalDetailPanel.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        signalDetailPanel.setMinimumSize(new Dimension(490, 500));
        signalDetailPanel.setPreferredSize(new Dimension(390, 540));
        signalDetailPanel.setLayout(new BoxLayout(signalDetailPanel, BoxLayout.Y_AXIS));

        row1Panel.setMinimumSize(new Dimension(380, 30));
        row1Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout2 = new FlowLayout(FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        row1Panel.setLayout(flowLayout2);

        idLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        idLbl.setLabelFor(idSpinner);
        idLbl.setText("Address / ID");
        idLbl.setPreferredSize(new Dimension(120, 16));
        row1Panel.add(idLbl);

        idSpinner.setModel(new SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(256L), Long.valueOf(1L)));
        idSpinner.setDoubleBuffered(true);
        idSpinner.setEditor(new JSpinner.NumberEditor(idSpinner, ""));
        idSpinner.setMinimumSize(new Dimension(70, 26));
        idSpinner.setName(""); // NOI18N
        idSpinner.setNextFocusableComponent(nameTF);
        idSpinner.setPreferredSize(new Dimension(70, 26));
        row1Panel.add(idSpinner);

        signalDetailPanel.add(row1Panel);

        row2Panel.setMinimumSize(new Dimension(380, 30));
        row2Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout3 = new FlowLayout(FlowLayout.LEFT);
        flowLayout3.setAlignOnBaseline(true);
        row2Panel.setLayout(flowLayout3);

        nameLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        nameLbl.setLabelFor(nameTF);
        nameLbl.setText("Name");
        nameLbl.setPreferredSize(new Dimension(120, 16));
        row2Panel.add(nameLbl);

        nameTF.setMinimumSize(new Dimension(150, 26));
        nameTF.setPreferredSize(new Dimension(150, 26));
        row2Panel.add(nameTF);

        signalDetailPanel.add(row2Panel);

        row3Panel.setMinimumSize(new Dimension(380, 30));
        row3Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout4 = new FlowLayout(FlowLayout.LEFT);
        flowLayout4.setAlignOnBaseline(true);
        row3Panel.setLayout(flowLayout4);

        typeLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        typeLbl.setLabelFor(typeTF);
        typeLbl.setText("Type");
        typeLbl.setPreferredSize(new Dimension(120, 16));
        row3Panel.add(typeLbl);

        typeTF.setMinimumSize(new Dimension(150, 26));
        typeTF.setPreferredSize(new Dimension(150, 26));
        row3Panel.add(typeTF);

        signalDetailPanel.add(row3Panel);

        row4Panel.setMinimumSize(new Dimension(380, 30));
        row4Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout5 = new FlowLayout(FlowLayout.LEFT);
        flowLayout5.setAlignOnBaseline(true);
        row4Panel.setLayout(flowLayout5);

        switchTimeLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        switchTimeLbl.setText("Switch Time");
        switchTimeLbl.setMaximumSize(new Dimension(120, 16));
        switchTimeLbl.setMinimumSize(new Dimension(120, 16));
        switchTimeLbl.setPreferredSize(new Dimension(120, 16));
        row4Panel.add(switchTimeLbl);

        switchTimeSpinner.setModel(new SpinnerNumberModel(0, 0, 5000, 1));
        switchTimeSpinner.setDoubleBuffered(true);
        switchTimeSpinner.setEditor(new JSpinner.NumberEditor(switchTimeSpinner, ""));
        switchTimeSpinner.setMinimumSize(new Dimension(70, 26));
        switchTimeSpinner.setName(""); // NOI18N
        switchTimeSpinner.setNextFocusableComponent(nameTF);
        switchTimeSpinner.setPreferredSize(new Dimension(70, 26));
        row4Panel.add(switchTimeSpinner);

        signalDetailPanel.add(row4Panel);

        row5Panel.setMinimumSize(new Dimension(380, 30));
        FlowLayout flowLayout6 = new FlowLayout(FlowLayout.LEFT);
        flowLayout6.setAlignOnBaseline(true);
        row5Panel.setLayout(flowLayout6);

        decoderTypeLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        decoderTypeLbl.setText("Decoder Type");
        decoderTypeLbl.setToolTipText("");
        decoderTypeLbl.setMaximumSize(new Dimension(120, 16));
        decoderTypeLbl.setMinimumSize(new Dimension(120, 16));
        decoderTypeLbl.setPreferredSize(new Dimension(120, 16));
        row5Panel.add(decoderTypeLbl);

        decoderTypeTF.setMinimumSize(new Dimension(150, 26));
        decoderTypeTF.setPreferredSize(new Dimension(150, 26));
        row5Panel.add(decoderTypeTF);

        signalDetailPanel.add(row5Panel);

        row6Panel.setMinimumSize(new Dimension(380, 30));
        row6Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout7 = new FlowLayout(FlowLayout.LEFT);
        flowLayout7.setAlignOnBaseline(true);
        row6Panel.setLayout(flowLayout7);

        decoderLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        decoderLbl.setText("Decoder");
        decoderLbl.setMaximumSize(new Dimension(120, 16));
        decoderLbl.setMinimumSize(new Dimension(120, 16));
        decoderLbl.setPreferredSize(new Dimension(120, 16));
        row6Panel.add(decoderLbl);

        decoderTF.setMinimumSize(new Dimension(150, 26));
        decoderTF.setPreferredSize(new Dimension(150, 26));
        row6Panel.add(decoderTF);

        signalDetailPanel.add(row6Panel);

        row7Panel.setMinimumSize(new Dimension(380, 30));
        row7Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout8 = new FlowLayout(FlowLayout.LEFT);
        flowLayout8.setAlignOnBaseline(true);
        row7Panel.setLayout(flowLayout8);

        positionLbl.setHorizontalAlignment(SwingConstants.TRAILING);
        positionLbl.setText("Position");
        positionLbl.setMaximumSize(new Dimension(120, 16));
        positionLbl.setMinimumSize(new Dimension(120, 16));
        positionLbl.setPreferredSize(new Dimension(120, 16));
        row7Panel.add(positionLbl);

        positionSpinner.setModel(new SpinnerNumberModel(0, 0, 4, 1));
        positionSpinner.setDoubleBuffered(true);
        positionSpinner.setEditor(new JSpinner.NumberEditor(positionSpinner, ""));
        positionSpinner.setMinimumSize(new Dimension(70, 26));
        positionSpinner.setName(""); // NOI18N
        positionSpinner.setNextFocusableComponent(nameTF);
        positionSpinner.setPreferredSize(new Dimension(70, 26));
        row7Panel.add(positionSpinner);

        signalDetailPanel.add(row7Panel);

        row8Panel.setMinimumSize(new Dimension(380, 30));
        FlowLayout flowLayout9 = new FlowLayout(FlowLayout.LEFT);
        flowLayout9.setAlignOnBaseline(true);
        row8Panel.setLayout(flowLayout9);
        signalDetailPanel.add(row8Panel);

        row9Panel.setPreferredSize(new Dimension(380, 30));
        FlowLayout flowLayout10 = new FlowLayout(FlowLayout.LEFT);
        flowLayout10.setAlignOnBaseline(true);
        row9Panel.setLayout(flowLayout10);
        signalDetailPanel.add(row9Panel);
        signalDetailPanel.add(filler2);

        buttonPanel.setMinimumSize(new Dimension(380, 40));
        buttonPanel.setPreferredSize(new Dimension(380, 40));
        FlowLayout flowLayout11 = new FlowLayout();
        flowLayout11.setAlignOnBaseline(true);
        buttonPanel.setLayout(flowLayout11);

        deleteBtn.setIcon(new ImageIcon(getClass().getResource("/media/delete-24.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setMaximumSize(new Dimension(100, 36));
        deleteBtn.setMinimumSize(new Dimension(100, 36));
        deleteBtn.setPreferredSize(new Dimension(100, 36));
        deleteBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(deleteBtn);
        buttonPanel.add(filler1);

        saveBtn.setIcon(new ImageIcon(getClass().getResource("/media/save-24.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setMaximumSize(new Dimension(100, 36));
        saveBtn.setMinimumSize(new Dimension(100, 36));
        saveBtn.setPreferredSize(new Dimension(100, 36));
        saveBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(saveBtn);

        signalDetailPanel.add(buttonPanel);

        centerSplitPane.setRightComponent(signalDetailPanel);

        centerPanel.add(centerSplitPane, BorderLayout.CENTER);

        add(centerPanel, BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new Dimension(1014, 50));
        bottomPanel.setRequestFocusEnabled(false);

        GroupLayout bottomPanelLayout = new GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(bottomPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(bottomPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(bottomPanel, BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


  private void newBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
    signalTableModel.refresh();
    alignSignalTable();

    Logger.debug("Create new Signal...");
    selectedSignal = new AccessoryBean();
    Long idl = signalTableModel.getRowCount() + 1l;

    selectedSignal.setName("W " + idl);
    selectedSignal.setId(idl);
    selectedSignal.setPosition(0);

    setComponentValues(selectedSignal);
    Logger.debug("Created new Signal..." + this.selectedSignal);
  }//GEN-LAST:event_newBtnActionPerformed

  private void signalTableMouseClicked(MouseEvent evt) {//GEN-FIRST:event_signalTableMouseClicked
    JTable source = (JTable) evt.getSource();
    int row = source.rowAtPoint(evt.getPoint());

    AccessoryBean t = this.signalTableModel.getControllableDeviceAt(row);
    if (t != null) {
      Logger.debug("Selected row: " + row + ", Signal ID: " + t.getId());
      //Refresh from repo
      this.selectedSignal = PersistenceFactory.getService().getAccessory(t.getId());
      this.setComponentValues(this.selectedSignal);
    }
  }//GEN-LAST:event_signalTableMouseClicked

  private void saveBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    this.selectedSignal = setSignalValues();
    Logger.debug("Save the Signal: " + this.selectedSignal);

    AccessoryBean t = PersistenceFactory.getService().getAccessory(selectedSignal.getId());
    if (t != null) {
      this.selectedSignal.setId(t.getId());
      Logger.debug("Found signal with id " + t.getId());
    } else {
      this.selectedSignal.setPosition(0);
    }

    selectedSignal = PersistenceFactory.getService().persist(selectedSignal);
    setComponentValues(selectedSignal);
    signalTableModel.refresh();
    alignSignalTable();
  }//GEN-LAST:event_saveBtnActionPerformed

  private void deleteBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
    Logger.debug("Delete Signal: " + this.selectedSignal);
    PersistenceFactory.getService().remove(selectedSignal);
    signalTableModel.refresh();
    selectedSignal = null;
    setComponentValues(selectedSignal);
    alignSignalTable();
  }//GEN-LAST:event_deleteBtnActionPerformed

  public void refresh() {
    signalTableModel.refresh();
    alignSignalTable();
    //Select the first row
    if (signalTableModel.getRowCount() > 0) {
      selectSignal(0);
      this.signalTable.setRowSelectionInterval(0, 0);
    }
  }

  private void synchronize() {
    ControllerFactory.getController().synchronizeSignals();
    refresh();
  }

    private void synchronizeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_synchronizeBtnActionPerformed
      synchronize();
    }//GEN-LAST:event_synchronizeBtnActionPerformed

    private void refreshBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
      refresh();
    }//GEN-LAST:event_refreshBtnActionPerformed

  //Create Signal from fields  
  protected AccessoryBean setSignalValues() {
    Long id = (Long) this.idSpinner.getValue();
    Integer address = id.intValue();
    String name = nameTF.getText();
    String type = typeTF.getText();
    Integer switchTime = (Integer) this.switchTimeSpinner.getValue();
    String decoderType = this.decoderTypeTF.getText();
    String decoder = this.decoderTF.getText();
    Integer position = (Integer) this.positionSpinner.getValue();

    AccessoryBean signal = new AccessoryBean(id, address, name, type, position, switchTime, decoderType, decoder);

    return signal;
  }

  protected void setComponentValues(AccessoryBean signal) {
    if (signal != null) {
      this.idSpinner.setValue(signal.getId());
      this.nameTF.setText(signal.getName());
      this.typeTF.setText(signal.getType());
      this.switchTimeSpinner.setValue(signal.getSwitchTime());
      this.decoderTypeTF.setText(signal.getDecoderType());
      this.decoderTF.setText(signal.getDecoder());
      this.positionSpinner.setValue(signal.getPosition());
    } else {
      this.idSpinner.setValue(0);
      this.nameTF.setText("");
      this.typeTF.setText("");
      this.switchTimeSpinner.setValue(0);
      this.decoderTypeTF.setText("");
      this.decoderTF.setText("");
      this.positionSpinner.setValue(0);
    }
  }

  public static void main(String args[]) {
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
      Logger.error("Can't set the LookAndFeel: " + ex);
    }
    java.awt.EventQueue.invokeLater(() -> {

      SignalPreferencesPanel testPanel = new SignalPreferencesPanel();
      JFrame testFrame = new JFrame();
      JDialog testDialog = new JDialog(testFrame, true);

      testDialog.add(testPanel);

      testDialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
          System.exit(0);
        }
      });
      testDialog.pack();
      testDialog.setLocationRelativeTo(null);

      testDialog.setVisible(true);
    });
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel bottomPanel;
    private JPanel buttonPanel;
    private JPanel centerPanel;
    private JSplitPane centerSplitPane;
    private JLabel decoderLbl;
    private JTextField decoderTF;
    private JLabel decoderTypeLbl;
    private JTextField decoderTypeTF;
    private JButton deleteBtn;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private JLabel idLbl;
    private JSpinner idSpinner;
    private JLabel nameLbl;
    private JTextField nameTF;
    private JButton newBtn;
    private JLabel positionLbl;
    private JSpinner positionSpinner;
    private JButton refreshBtn;
    private JPanel row1Panel;
    private JPanel row2Panel;
    private JPanel row3Panel;
    private JPanel row4Panel;
    private JPanel row5Panel;
    private JPanel row6Panel;
    private JPanel row7Panel;
    private JPanel row8Panel;
    private JPanel row9Panel;
    private JButton saveBtn;
    private AccessoryBean selectedSignal;
    private JPanel signalDetailPanel;
    private JTable signalTable;
    private JScrollPane signalTableScrollPane;
    private JLabel switchTimeLbl;
    private JSpinner switchTimeSpinner;
    private JButton synchronizeBtn;
    private JPanel topPanel;
    private JLabel typeLbl;
    private JTextField typeTF;
    // End of variables declaration//GEN-END:variables
}
